import {describe,it,expect} from "vitest";
import {randomUUID,createHmac} from "node:crypto";
import {authorize,commandSchema,createTaskSchema,messageDraft,OperationsError,patchTaskSchema,taskKind,WRITE_COMMANDS,type Actor,type SignedClaims} from "./contracts.js";
import {INTERNAL_TASK_KINDS,isMessageTaskKind,MESSAGE_ATTACHMENT_KINDS,MESSAGE_TASK_KINDS,TASK_KINDS} from "./action-kinds.js";
import {signRequest,verifyRequest} from "./auth.js";
import {assertCompletion,digest,requestDigest} from "./policy.js";
const key="isolated-test-signing-key-not-production-0123456789";
const owner:Actor={id:"owner-test",role:"owner",kind:"human",workspace:"egc"};
const claims=():SignedClaims=>({v:1,iss:"portal",aud:"egc-operations",iat:Math.floor(Date.now()/1000),nonce:randomUUID(),actor:owner,request:{requestId:randomUUID(),body:{command:"status"}}});
const task={title:"Call synthetic customer",assignedUserId:"owner-test",dueAt:"2026-09-20T10:00:00-06:00",completionCondition:"Record attempt and result"};
const draft={channel:"sms" as const,recipient:"+15555550100",subject:"",body:"Synthetic message",sendWindowStart:"2026-09-20T08:00:00-06:00",sendWindowEnd:"2026-09-20T18:00:00-06:00"};
const errorCode=(fn:()=>unknown,code:string)=>{try{fn();throw new Error("Expected denial");}catch(e){expect(e).toBeInstanceOf(OperationsError);expect((e as OperationsError).code).toBe(code);}};
describe("signed principal and authorization",()=>{
 it("round trips exact server-authenticated claims",()=>{const c=claims();expect(verifyRequest(signRequest(c,key),{portal:key})).toEqual(c);});
 it("rejects body or identity tampering",()=>{const t=signRequest(claims(),key).split('.');const p=JSON.parse(Buffer.from(t[0]!,"base64url").toString());p.actor.id="forged";errorCode(()=>verifyRequest(Buffer.from(JSON.stringify(p)).toString("base64url")+'.'+t[1],{portal:key}),"invalid_operations_signature");});
 it("rejects missing, invalid and huge signatures",()=>{for(const t of [undefined,{},"a","a.b.c","a.!","x".repeat(200001)])expect(()=>verifyRequest(t,{portal:key})).toThrow();});
 it("never accepts the MCP key for portal claims",()=>{errorCode(()=>verifyRequest(signRequest(claims(),key),{mcp:key}),"issuer_not_configured");});
 it("rejects expired and future envelopes",()=>{for(const delta of [-120,120]){const c=claims();c.iat+=delta;errorCode(()=>verifyRequest(signRequest(c,key),{portal:key}),"operations_signature_expired");}});
 it("rejects wrong audience",()=>{const c=claims();c.aud="egc-portal";errorCode(()=>verifyRequest(signRequest(c,key),{portal:key}),"invalid_operations_audience");});
 it("rejects extra identity fields even under a valid MAC",()=>{const c={...claims(),approver:"forged"};const p=Buffer.from(JSON.stringify(c)).toString("base64url"),t=p+'.'+createHmac('sha256',key).update(p).digest('base64url');errorCode(()=>verifyRequest(t,{portal:key}),"invalid_operations_request");});
 it("blocks crew and wrong workspace",()=>{errorCode(()=>authorize({...owner,role:"crew"},{command:"status"},"egc"),"role_forbidden");errorCode(()=>authorize({...owner,workspace:"other"},{command:"status"},"egc"),"workspace_forbidden");});
 it("integrations can modify internal tasks, never pretend to approve as human",()=>{const actor:Actor={id:"grant-1",kind:"integration",role:"integration",workspace:"egc"};const command={command:"task.complete" as const,taskId:randomUUID(),revision:1,outcome:"Recorded actual outcome"};expect(()=>authorize(actor,command,"egc")).not.toThrow();errorCode(()=>authorize(actor,{command:"task.reject",taskId:randomUUID(),revision:1,reason:"No"},"egc"),"human_manager_approval_required");});
 it("disallows inconsistent role/kind claims",()=>{errorCode(()=>authorize({...owner,kind:"integration"},{command:"status"},"egc"),"invalid_actor");});
 it("requires strong configured keys",()=>{errorCode(()=>signRequest(claims(),"short"),"signing_key_not_configured");});
});
describe("strict action contracts",()=>{
 it("requires an owner, due time and completion evidence definition",()=>{for(const k of ['assignedUserId','dueAt','completionCondition']){const copy={...task} as Record<string,unknown>;delete copy[k];expect(createTaskSchema.safeParse(copy).success).toBe(false);}});
 it("accepts a dated callback without lead age or booked filters",()=>{expect(createTaskSchema.parse({...task,kind:"callback"}).kind).toBe("callback");});
 it("requires review time for external waits",()=>{expect(createTaskSchema.safeParse({...task,waitingOn:"customer"}).success).toBe(false);expect(createTaskSchema.safeParse({...task,waitingOn:"provider",reviewAt:task.dueAt}).success).toBe(true);});
 it("does not accept naive times, invalid timezone or fabricated portal identities",()=>{for(const c of [{dueAt:"2026-09-20T10:00:00"},{timeZone:"Not/AZone"},{portalJobId:"../secret"},{portalVisitId:"visit-without-record"}])expect(createTaskSchema.safeParse({...task,...c}).success).toBe(false);});
 it("requires a complete exact draft only for message actions",()=>{expect(createTaskSchema.safeParse({...task,kind:"followup_message"}).success).toBe(false);expect(createTaskSchema.safeParse({...task,draft}).success).toBe(false);expect(createTaskSchema.safeParse({...task,kind:"followup_message",draft}).success).toBe(true);});
 it("rejects invalid recipients and nonpositive send windows",()=>{for(const c of [{recipient:"555 invalid"},{sendWindowEnd:draft.sendWindowStart},{channel:"email",recipient:"not mail"}])expect(createTaskSchema.safeParse({...task,kind:"followup_message",draft:{...draft,...c}}).success).toBe(false);});
 it("rejects raw approval/completion fields on edits and creates",()=>{expect(createTaskSchema.safeParse({...task,approvalStatus:"approved"}).success).toBe(false);expect(commandSchema.safeParse({command:"task.edit",taskId:randomUUID(),revision:1,changes:{status:"completed"}}).success).toBe(false);});
 it("requires revision and stable request command boundaries",()=>{expect(commandSchema.safeParse({command:"task.complete",taskId:randomUUID(),outcome:"done"}).success).toBe(false);expect(commandSchema.safeParse({command:"send_sms",recipient:draft.recipient,body:"test"}).success).toBe(false);});
 it("cannot call internal completion proof a payment or delivery",()=>{expect(()=>assertCompletion("callback")).not.toThrow();errorCode(()=>assertCompletion("followup_message"),"message_completion_requires_provider_evidence");errorCode(()=>assertCompletion("verify_deposit"),"deposit_completion_requires_verified_payment");});
 it("fingerprints exact payload values but not key order",()=>{expect(digest({a:1,b:2})).toBe(digest({b:2,a:1}));expect(digest({price:72500})).not.toBe(digest({price:75000}));});
});
const attachment={kind:"portal_quote" as const,url:"https://easygaragecleaning.com/portal/quote/synthetic-1",label:"Your quote",refId:"quote:synthetic-1"};
const parseMessage=(kind:string,extra:Record<string,unknown>={})=>createTaskSchema.safeParse({...task,kind,draft:{...draft,...extra}});
describe("action kinds v2",()=>{
 it("partitions every kind into exactly one of message or internal",()=>{expect([...TASK_KINDS].sort()).toEqual([...MESSAGE_TASK_KINDS,...INTERNAL_TASK_KINDS].sort());expect(MESSAGE_TASK_KINDS.filter(k=>(INTERNAL_TASK_KINDS as readonly string[]).includes(k))).toEqual([]);expect(taskKind.options).toEqual([...TASK_KINDS]);});
 it("keeps every v1 kind and adds the v2 kinds",()=>{for(const kind of ["manual","callback","prepare_quote","followup_message","review_notes","verify_deposit","job_readiness","send_before_afters","send_insurance_certificate","send_quote","send_product_options","schedule_job","answer_question","deposit_reminder"])expect(TASK_KINDS).toContain(kind);expect(TASK_KINDS).toHaveLength(14);});
 it("classifies message kinds exactly",()=>{expect([...MESSAGE_TASK_KINDS].sort()).toEqual(["answer_question","deposit_reminder","followup_message","send_before_afters","send_insurance_certificate","send_product_options","send_quote"]);for(const kind of ["schedule_job","callback","verify_deposit","manual"])expect(isMessageTaskKind(kind)).toBe(false);for(const value of [undefined,null,1,"Send_quote","send_quote "])expect(isMessageTaskKind(value)).toBe(false);});
 it("parses each message kind with its exact draft and defaults attachments to none",()=>{for(const kind of MESSAGE_TASK_KINDS){const parsed=parseMessage(kind);expect(parsed.success).toBe(true);expect(parsed.data?.kind).toBe(kind);expect(parsed.data?.draft?.attachments).toEqual([]);}});
 it("parses each internal kind without a draft",()=>{for(const kind of INTERNAL_TASK_KINDS){const parsed=createTaskSchema.safeParse({...task,kind});expect(parsed.success).toBe(true);expect(parsed.data?.draft).toBeNull();}});
 it("rejects message kinds without a draft and internal kinds with one",()=>{for(const kind of MESSAGE_TASK_KINDS){expect(createTaskSchema.safeParse({...task,kind}).success).toBe(false);expect(createTaskSchema.safeParse({...task,kind,draft:null}).success).toBe(false);}for(const kind of INTERNAL_TASK_KINDS)expect(createTaskSchema.safeParse({...task,kind,draft}).success).toBe(false);});
 it("rejects unknown kinds",()=>{for(const kind of ["send_invoice","sendQuote","","book_job"])expect(createTaskSchema.safeParse({...task,kind}).success).toBe(false);});
 it("accepts every attachment kind with an https URL and keeps the exact values",()=>{const attachments=MESSAGE_ATTACHMENT_KINDS.map((kind,i)=>({kind,url:`https://easygaragecleaning.com/a/${i}?v=1#top`,label:`Synthetic ${kind}`,refId:`ref-${i}`}));const parsed=parseMessage("send_quote",{attachments});expect(parsed.success).toBe(true);expect(parsed.data?.draft?.attachments).toEqual(attachments);expect(messageDraft.parse({...draft,attachments:[{kind:"url",url:"https://example.com/",label:"Link"}]}).attachments[0]?.refId).toBeNull();});
 it("rejects non-https, scripted, credentialed and malformed attachment URLs",()=>{for(const url of ["http://easygaragecleaning.com/q","javascript:alert(1)","JAVASCRIPT:alert(1)","data:text/html,hi","ftp://example.com/f","//example.com/q","/portal/quote/1","https://","https://user:pass@example.com/q","https://example.com/a b","https://example.com/\nq","https://example.com/"+"a".repeat(1981),""," https://example.com/q"])expect(parseMessage("send_quote",{attachments:[{...attachment,url}]}).success,url).toBe(false);});
 it("bounds attachment count, label, refId, kind and extra fields",()=>{const many=Array.from({length:11},(_,i)=>({...attachment,url:`https://example.com/${i}`}));expect(parseMessage("send_before_afters",{attachments:many.slice(0,10)}).success).toBe(true);for(const attachments of [many,[{...attachment,label:""}],[{...attachment,label:"x".repeat(121)}],[{...attachment,refId:"x".repeat(181)}],[{...attachment,refId:"../secret"}],[{...attachment,kind:"invoice_pdf"}],[{...attachment,signedUrl:"https://example.com/s"}],[{kind:"url",label:"No link"}],"https://example.com/q",[attachment,attachment]])expect(parseMessage("send_before_afters",{attachments}).success).toBe(false);expect(parseMessage("send_quote",{attachments:[{...attachment,url:"https://example.com/"+"a".repeat(1980),label:"x".repeat(120),refId:"x".repeat(180)}]}).success).toBe(true);});
 it("edits may replace a message draft with attachments",()=>{const parsed=commandSchema.safeParse({command:"task.edit",taskId:randomUUID(),revision:1,changes:{draft:{...draft,attachments:[attachment]}}});expect(parsed.success).toBe(true);expect(patchTaskSchema.safeParse({draft:{...draft,attachments:[{...attachment,url:"http://example.com"}]}}).success).toBe(false);});
 it("blocks staff attestation for every message kind but not internal work",()=>{for(const kind of MESSAGE_TASK_KINDS)errorCode(()=>assertCompletion(kind),"message_completion_requires_provider_evidence");for(const kind of INTERNAL_TASK_KINDS.filter(k=>k!=="verify_deposit"))expect(()=>assertCompletion(kind)).not.toThrow();errorCode(()=>assertCompletion("verify_deposit"),"deposit_completion_requires_verified_payment");});
});
describe("canonical attachment URLs",()=>{
 const urlOf=(url:string)=>{const parsed=parseMessage("send_quote",{attachments:[{...attachment,url}]});return parsed.success?parsed.data.draft!.attachments[0]!.url:null;};
 it("stores the parsed URL's canonical href for every accepted spelling",()=>{for(const [raw,canonical] of [["HTTPS://EXAMPLE.COM/x","https://example.com/x"],["https:example.com/x","https://example.com/x"],["https:/example.com/x","https://example.com/x"],["https://example.com\\evil","https://example.com/evil"],["https://Example.com/a/../b?q=1#f","https://example.com/b?q=1#f"],["https://example.com","https://example.com/"],["https://ΑΒΓ.com/x","https://xn--mxacd.com/x"],["https://easygaragecleaning.com/portal/quote/synthetic-1","https://easygaragecleaning.com/portal/quote/synthetic-1"]])expect(urlOf(raw),raw).toBe(canonical);});
 it("is idempotent because MCP parses a task before the API parses it again",()=>{const first=parseMessage("send_quote",{attachments:[{...attachment,url:"HTTPS://Example.COM\\A/./b"}]});expect(first.success).toBe(true);const again=parseMessage("send_quote",{attachments:first.data!.draft!.attachments});expect(again.data?.draft?.attachments).toEqual(first.data?.draft?.attachments);expect(first.data?.draft?.attachments[0]?.url).toBe("https://example.com/A/b");});
 it("treats spellings of one link as duplicates",()=>{for(const pair of [["https://A.com/x","https://a.com/x"],["https://a.com\\x","https://a.com/x"],["https:a.com/x","https://a.com/x"]])expect(parseMessage("send_quote",{attachments:pair.map((url,i)=>({...attachment,url,refId:`ref-${i}`}))}).success,pair.join(" ")).toBe(false);});
 it("rejects invisible format characters, private hosts and over-long canonical forms",()=>{for(const url of ["https://example.com/​x","https://exa​mple.com/x","https://example.com/‮gpj.exe","https://example.com/﻿x","https://⁠example.com/","https://localhost/q","https://LOCALHOST./q","https://api.localhost/q","https://127.0.0.1/q","https://2130706433/q","https://127.1/q","https://10.0.0.8/q","https://[::1]/q","https://[2001:db8::1]/q","https://intranet/q","https://user@example.com/q","https://example.com/"+"é".repeat(995)])expect(urlOf(url),JSON.stringify(url)).toBeNull();});
});
describe("task.send contract",()=>{
 const send={command:"task.send",taskId:"00000000-0000-4000-8000-000000000002",revision:1,previewHash:"a".repeat(64),confirm:true};
 it("requires explicit confirmation, the exact preview hash and a valid optional draft",()=>{
  expect(commandSchema.safeParse(send).success).toBe(true);expect(commandSchema.safeParse({...send,draft:{...draft,attachments:[attachment]}}).success).toBe(true);
  for(const bad of [{...send,confirm:false},{...send,confirm:undefined},{...send,confirm:"true"},{...send,previewHash:"A".repeat(64)},{...send,previewHash:undefined},{...send,revision:0},{...send,draft:{...draft,recipient:"555"}},{...send,draft:{...draft,attachments:[{...attachment,url:"http://example.com/q"}]}},{...send,recipient:"+15555550100"},{...send,actorId:"forged"}])expect(commandSchema.safeParse(bad).success).toBe(false);
 });
 it("is a write only a signed-in person with a business role may confirm",()=>{
  const parsed=commandSchema.parse(send);expect(WRITE_COMMANDS.has("task.send")).toBe(true);
  errorCode(()=>authorize({id:"grant-1",kind:"integration",role:"integration",workspace:"egc"},parsed,"egc"),"human_send_confirmation_required");
  for(const role of ["owner","manager","sales"] as const)expect(()=>authorize({...owner,role},parsed,"egc")).not.toThrow();
  for(const role of ["crew","crew_lead"] as const)errorCode(()=>authorize({...owner,role},parsed,"egc"),"role_forbidden");
 });
 it("digests an edited draft the same with a missing or empty attachment list, but not the same as no edit",()=>{
  const digestOf=(value:object)=>requestDigest(owner,commandSchema.parse(value));
  expect(digestOf({...send,draft})).toBe(digestOf({...send,draft:{...draft,attachments:[]}}));expect(digestOf({...send,draft})).not.toBe(digestOf(send));expect(digestOf({...send,draft:{...draft,attachments:[attachment]}})).not.toBe(digestOf({...send,draft}));
 });
});
describe("request digest across the attachments default",()=>{
 const legacyDigest=(command:Record<string,unknown>)=>digest({actor:{id:owner.id,kind:owner.kind,role:owner.role,workspace:owner.workspace},command});
 const parse=(value:unknown)=>commandSchema.parse(value);
 const create={command:"task.create",task:{...task,kind:"followup_message",draft}};
 it("hashes a parsed pre-v2 draft (no attachments key) exactly as the old service did",()=>{const parsed=parse(create);expect((parsed as {task:{draft:{attachments:unknown}}}).task.draft.attachments).toEqual([]);const {attachments:_,...legacy}=(parsed as {task:{draft:Record<string,unknown>}}).task.draft;expect(requestDigest(owner,parsed)).toBe(legacyDigest({...parsed,task:{...(parsed as {task:object}).task,draft:legacy}}));});
 it("treats a missing and an empty attachment list identically for creates and edits",()=>{expect(requestDigest(owner,parse(create))).toBe(requestDigest(owner,parse({...create,task:{...create.task,draft:{...draft,attachments:[]}}})));const edit=(changes:object)=>parse({command:"task.edit",taskId:"00000000-0000-4000-8000-000000000001",revision:3,changes});expect(requestDigest(owner,edit({draft}))).toBe(requestDigest(owner,edit({draft:{...draft,attachments:[]}})));expect(requestDigest(owner,edit({title:"Only a title"}))).toBe(legacyDigest(edit({title:"Only a title"})));expect(requestDigest(owner,edit({draft:null}))).toBe(legacyDigest(edit({draft:null})));});
 it("still distinguishes real attachments, other payload changes and other actors",()=>{const base=requestDigest(owner,parse(create));expect(requestDigest(owner,parse({...create,task:{...create.task,draft:{...draft,attachments:[attachment]}}}))).not.toBe(base);expect(requestDigest(owner,parse({...create,task:{...create.task,draft:{...draft,body:"Different synthetic body"}}}))).not.toBe(base);expect(requestDigest({...owner,id:"manager-test",role:"manager"},parse(create))).not.toBe(base);const internal=parse({command:"task.create",task:{...task,kind:"schedule_job"}});expect(requestDigest(owner,internal)).toBe(legacyDigest(internal));});
});
