# Service page content definitions
NO_ITEMS = [
    "Liquid paint, gasoline, or solvents",
    "Asbestos-containing materials",
    "Medical waste and sharps",
    "Live ammunition or firearms",
    "Large quantities of motor oil",
]

SERVICES = [
    {
        "slug": "junk-removal-fort-collins-co.html",
        "title": "Junk Removal Fort Collins CO | Easy Garage Cleaning",
        "desc": "Fort Collins junk removal — single items to full loads. Appliances, furniture, mattresses, boxes. Flat-rate quotes, text photos for estimate. Same-day available.",
        "h1": "Junk Removal Fort Collins CO",
        "hero_em": "Without the franchise runaround",
        "hero_sub": "That pile in the garage corner? The old couch in the basement? We haul it — flat-rate, fully insured, and usually same-day in Fort Collins. Text photos for a quote in 5 minutes.",
        "sms": "Hi! I need junk removal in Fort Collins.",
        "stype": "Junk Removal",
        "problem_title": "Junk shouldn't steal <em>your weekend</em>",
        "problem_sub": "Fort Collins homeowners call us when the pile gets too big for the curb and too heavy for one trip to Larimer County Landfill.",
        "problems": [("🚛", "No truck rental", "Skip the U-Haul, tarps, and three trips to the dump."), ("💸", "No hourly surprises", "Franchise haulers clock you. We quote flat before we load."), ("📦", "Garage overflow", "Boxes, broken gear, and deferred items — gone in one visit."), ("♻️", "Donation handled", "Usable stuff goes to ReStore and ARC — receipt in your name.")],
        "yes_title": "What we <em>remove</em> in Fort Collins",
        "yes": ["Furniture, mattresses, and box springs", "Appliances — fridges, washers, dryers", "Boxes, bins, and household clutter", "Exercise equipment and tools", "Yard debris and outdoor furniture", "Electronics (e-waste recycled properly)"],
        "ba": ("Junk pile — Fort Collins", "Garage corner haul", "Appliance pickup — Midtown"),
        "cta": "Book junk removal <em>today</em>",
        "form_subject": "Junk Removal Quote - Fort Collins",
        "items_ph": "Describe junk to remove — e.g. old couch, boxes, broken grill",
        "related": [("/garage-cleanouts-fort-collins-co.html", "Garage Cleanouts"), ("/furniture-removal-fort-collins-co.html", "Furniture Removal"), ("/appliance-removal-fort-collins-co.html", "Appliance Removal"), ("/mattress-removal-fort-collins-co.html", "Mattress Removal"), ("/loveland-garage-cleanout.html", "Loveland"), ("/", "Home")],
        "faqs": [
            ("How much does junk removal cost in Fort Collins?", "Most jobs fall into four ranges: single-item pickup ($99–$150), small loads ($250–$400), medium loads ($400–$650), and large hauls ($650+). Text photos for your exact flat-rate quote."),
            ("Do you offer same-day junk removal in Fort Collins?", "Yes — when our schedule allows. We respond within 5 minutes and often book same-day or next-day in Fort Collins."),
            ("What items can you not haul?", "We cannot take liquid paint, gasoline, asbestos, medical waste, or live ammunition. See our blog guide for Fort Collins disposal options."),
            ("Do you haul from inside the garage?", "Yes. We carry items from garage, basement, or anywhere on the ground floor. Point us to what's going."),
            ("Is there a minimum load size?", "No minimum for photo quotes. Single-item pickups start around $99–$150 depending on item and access."),
            ("Do you donate usable junk?", "Yes — furniture and household goods in good shape go to Habitat ReStore, ARC, and Goodwill. You get the tax receipt."),
            ("How do I get a quote with photos?", "Text photos to (970) 999-1818 or use the form on this page. Wide shots of the full pile work best."),
            ("Are you licensed and insured in Fort Collins?", "Yes. Easy Garage Cleaning LLC is a Colorado-registered LLC with general liability and commercial auto insurance."),
            ("Do you serve Loveland and Windsor too?", "Yes — Fort Collins is home base, but we serve Loveland, Windsor, Timnath, and Wellington daily."),
            ("What happens to my junk after pickup?", "Donations first, then Larimer County Landfill or recycling for the rest. We never dump illegally."),
        ],
    },
    {
        "slug": "garage-cleanouts-fort-collins-co.html",
        "title": "Garage Cleanouts Fort Collins CO | Easy Garage Cleaning",
        "desc": "Full garage cleanouts in Fort Collins — haul-out, sweep, donate usable items. Flat-rate pricing from $400–650 for most garages. Text photos for a free quote.",
        "h1": "Garage Cleanouts Fort Collins CO",
        "hero_em": "Reclaim your garage",
        "hero_sub": "The easiest way to reclaim your garage. We empty, haul, donate, and sweep — so you can park inside again. Locally owned by Zac Bezenek, not a franchise call center.",
        "sms": "Hi! I need a garage cleanout in Fort Collins.",
        "stype": "Garage Cleanout",
        "problem_title": "Your garage became a <em>storage unit</em>",
        "problem_sub": "Northern Colorado winters make parking outside painful. Most Fort Collins garages fill slowly — until there's no room for the car.",
        "problems": [("🚗", "Car parked outside", "Hail, snow, and frost while boxes fill the bay."), ("⏰", "Weekends lost", "Dump runs and sorting eat Saturdays you'll never get back."), ("😤", "Overwhelmed", "Years of accumulation — you don't know where to start."), ("💸", "Surprise fees", "Hourly franchise billing adds up fast on big garages.")],
        "yes_title": "Full cleanout — <em>what goes</em>",
        "yes": ["Everything you mark for removal", "Furniture, appliances, and boxes", "Old sports gear and holiday decor", "Broken tools and shop clutter", "Yard equipment stored in garage", "Leftover renovation materials"],
        "ba": ("Two-car garage — Fort Collins", "Single-car cleanout — Fossil Creek", "Move-out garage — Harmony"),
        "cta": "Book your garage <em>cleanout today</em>",
        "form_subject": "Garage Cleanout Quote - Fort Collins",
        "items_ph": "Describe your garage — e.g. full two-car, packed with boxes and old furniture",
        "related": [("/junk-removal-fort-collins-co.html", "Junk Removal"), ("/garage-cleaning-fort-collins-co.html", "Garage Cleaning"), ("/garage-organization-fort-collins-co.html", "Garage Organization"), ("/storage-unit-cleanout-fort-collins-co.html", "Storage Unit Cleanout"), ("/blog/how-to-prepare-for-garage-cleanout.html", "Prep Guide"), ("/", "Home")],
        "faqs": [
            ("How much does a garage cleanout cost in Fort Collins?", "Most single-car or moderate two-car garages fall in the $400–$650 range. Packed two-car garages or estate situations start at $650+. Text photos for your exact quote."),
            ("What's included in a garage cleanout?", "Labor, hauling, dump fees, donation drop-offs, and a floor sweep. Usable items go to ReStore or ARC with a tax receipt in your name."),
            ("Do I need to sort before you arrive?", "No. Mark what stays, point to what's going. We handle sorting, carrying, and loading."),
            ("How long does a garage cleanout take?", "Most single-car garages take 2–4 hours. Full two-car garages typically 3–5 hours depending on volume."),
            ("Can you clean out attached and detached garages?", "Yes — both in Fort Collins. Detached garages and workshops are common in Old Town and Midtown."),
            ("Do you offer same-day garage cleanouts?", "Often yes. Text photos and we'll confirm availability within 5 minutes."),
            ("What if I want to keep some items?", "We do a 15-minute walkthrough first. You tell us what's staying — we only haul what you approve."),
            ("Do you sweep the garage floor after?", "Yes. A basic sweep is included so you walk into a clear, usable space."),
            ("Are garage cleanouts flat-rate?", "Yes. No hourly billing. The price we quote before the job is the price you pay."),
            ("Do you handle estate garage cleanouts?", "Yes. Multi-space and estate cleanouts are quoted individually — usually $650+ depending on volume."),
        ],
    },
    {
        "slug": "garage-cleaning-fort-collins-co.html",
        "title": "Garage Cleaning Fort Collins CO | Easy Garage Cleaning",
        "desc": "Post-cleanout garage cleaning in Fort Collins — sweep, dust, and reset your space. Pair with our cleanout service or book standalone. Flat-rate quotes.",
        "h1": "Garage Cleaning Fort Collins CO",
        "hero_em": "Beyond just hauling junk",
        "hero_sub": "After the junk is gone, dust and cobwebs remain. We sweep, wipe surfaces, and reset your Fort Collins garage so it feels truly clean — not just empty.",
        "sms": "Hi! I need garage cleaning in Fort Collins.",
        "stype": "Garage Cleaning",
        "problem_title": "Empty isn't the same as <em>clean</em>",
        "problem_sub": "You've cleared the clutter but the floor is dusty, cobwebs hang in corners, and oil stains mark where the old mower sat.",
        "problems": [("🕸️", "Dust and cobwebs", "Years of accumulation in corners and rafters."), ("🛢️", "Oil and stain spots", "Old equipment left marks on concrete."), ("🧹", "No time to deep clean", "You got the junk out — now who sweeps?"), ("✨", "Want a fresh start", "Clean garage = easier to organize and maintain.")],
        "yes_title": "Garage cleaning <em>includes</em>",
        "yes": ["Full floor sweep and debris removal", "Dusting shelves and ledges", "Wiping accessible surfaces", "Cobweb removal in reachable areas", "Bagging remaining loose trash", "Final walkthrough with you"],
        "ba": ("Post-cleanout sweep — Fort Collins", "Dusty single-car garage", "Clean two-car reset — Midtown"),
        "cta": "Book garage <em>cleaning today</em>",
        "form_subject": "Garage Cleaning Quote - Fort Collins",
        "items_ph": "Describe garage size and condition — e.g. two-car, dusty after cleanout",
        "show_items": False,
        "related": [("/garage-cleanouts-fort-collins-co.html", "Garage Cleanouts"), ("/garage-organization-fort-collins-co.html", "Garage Organization"), ("/junk-removal-fort-collins-co.html", "Junk Removal"), ("/", "Home")],
        "faqs": [
            ("Do you offer garage cleaning without a cleanout?", "Yes — if the junk is already gone, we can come sweep and reset the space. Most clients pair cleaning with our cleanout service."),
            ("How much does garage cleaning cost in Fort Collins?", "Standalone cleaning typically runs $150–$300 depending on garage size. Bundled with a cleanout, it's often included or discounted."),
            ("Do you pressure wash garage floors?", "We focus on sweep and wipe service. Heavy oil stain removal or pressure washing can be quoted separately."),
            ("What cleaning supplies do you use?", "We bring brooms, dusters, bags, and basic cleaning supplies. No harsh chemicals unless you request them."),
            ("How long does garage cleaning take?", "Most single-car garages take 1–2 hours. Two-car garages 2–3 hours depending on condition."),
            ("Can you clean detached garages?", "Yes — detached garages, workshops, and sheds in Fort Collins are all serviceable."),
            ("Is garage cleaning included in a cleanout?", "A basic floor sweep is included with every cleanout. Deep cleaning is an add-on — ask when you quote."),
            ("Do I need to move my car out?", "Ideally yes — an empty garage cleans faster and more thoroughly."),
            ("Do you remove spider webs in rafters?", "We clear reachable cobwebs and dust. Very high rafters may need a ladder — we'll note that in the quote."),
            ("Can I book cleaning after another company hauls junk?", "Absolutely. Send photos of the empty garage and we'll quote the cleaning separately."),
        ],
    },
    {
        "slug": "furniture-removal-fort-collins-co.html",
        "title": "Furniture Removal Fort Collins CO | Easy Garage Cleaning",
        "desc": "Furniture removal in Fort Collins — sofas, beds, dressers, tables hauled and donated. Flat-rate from $99–150 per item. Text photos for estimate.",
        "h1": "Furniture Removal Fort Collins CO",
        "hero_em": "Heavy lifting handled",
        "hero_sub": "That couch stuck in the garage? The dresser nobody wants? We carry it out, donate what's usable, and dispose of the rest — no per-item franchise surcharges.",
        "sms": "Hi! I need furniture removal in Fort Collins.",
        "stype": "Furniture Removal",
        "problem_title": "Bulky furniture <em>won't move itself</em>",
        "problem_sub": "Fort Collins garages and basements become furniture graveyards — too heavy to move alone, too big for regular trash pickup.",
        "problems": [("🛋️", "Stuck in the garage", "Couches and sectionals block the bay."), ("🚪", "Won't fit in your car", "Can't haul a dresser in a Subaru."), ("♻️", "Donation drop-off hassle", "Goodwill won't pick up your broken recliner."), ("💪", "Injury risk", "Heavy lifts without help or equipment.")],
        "yes_title": "Furniture we <em>remove</em>",
        "yes": ["Sofas, sectionals, and recliners", "Mattresses and bed frames", "Dressers, armoires, and wardrobes", "Dining tables and chairs", "Desks and office furniture", "Outdoor patio furniture"],
        "ba": ("Sectional removal — Fort Collins", "Garage dresser haul", "Donation pickup — Loveland"),
        "cta": "Book furniture removal <em>today</em>",
        "form_subject": "Furniture Removal Quote - Fort Collins",
        "items_ph": "List furniture items — e.g. sectional sofa, queen bed frame, dining table",
        "related": [("/mattress-removal-fort-collins-co.html", "Mattress Removal"), ("/junk-removal-fort-collins-co.html", "Junk Removal"), ("/garage-cleanouts-fort-collins-co.html", "Garage Cleanouts"), ("/", "Home")],
        "faqs": [
            ("How much does furniture removal cost in Fort Collins?", "Single pieces typically run $99–$150. Multiple items or a garage full of furniture falls in the $250–$650 range depending on volume."),
            ("Do you remove furniture from upstairs?", "Ground floor and garage yes. Second-floor removals depend on access — send photos and we'll quote accurately."),
            ("Will you donate my old furniture?", "If it's in usable condition, yes — Habitat ReStore, ARC, or Goodwill. You get the donation receipt."),
            ("Do you disassemble furniture?", "Basic disassembly (bed frames, tables) when needed for safe removal. Complex built-ins may require a carpenter."),
            ("Can you remove a couch from my garage?", "Yes — garage furniture removal is one of our most common calls in Fort Collins."),
            ("Is there a surcharge for heavy items?", "No per-item surcharges. Weight is factored into your flat-rate quote upfront."),
            ("Do I need to wrap or bag furniture?", "No prep needed. We protect floors and walls during carry-out."),
            ("How fast can you pick up furniture?", "Same-day and next-day often available. Text photos for fastest scheduling."),
            ("What if my furniture is moldy or broken?", "We still haul it — it goes to disposal instead of donation. No judgment, just removal."),
            ("Do you remove office furniture from home garages?", "Yes — desks, filing cabinets, and chairs from home offices and garages."),
        ],
    },
    {
        "slug": "appliance-removal-fort-collins-co.html",
        "title": "Appliance Removal Fort Collins CO | Easy Garage Cleaning",
        "desc": "Appliance removal in Fort Collins — fridges, washers, dryers, water heaters hauled and recycled. Working units donated to ReStore. Flat-rate quotes.",
        "h1": "Appliance Removal Fort Collins CO",
        "hero_em": "Old appliances gone fast",
        "hero_sub": "That dead fridge in the garage? The washer you replaced three years ago? We haul appliances in Fort Collins — working units to ReStore, the rest recycled properly.",
        "sms": "Hi! I need appliance removal in Fort Collins.",
        "stype": "Appliance Removal",
        "problem_title": "Old appliances <em>collect dust</em> forever",
        "problem_sub": "Fort Collins garages hide retired fridges, washers, and water heaters — too heavy to move, too awkward for curbside pickup.",
        "problems": [("🔌", "Dead fridge in the garage", "Taking up a full parking spot."), ("💧", "Water heater upgrade leftover", "Still sitting on a pallet in the corner."), ("♻️", "Recycling confusion", "Larimer County rules vary by appliance type."), ("💪", "200+ pounds alone", "You need equipment and a second set of hands.")],
        "yes_title": "Appliances we <em>remove</em>",
        "yes": ["Refrigerators and freezers", "Washers and dryers", "Dishwashers and ranges", "Water heaters", "Microwaves and dehumidifiers", "Window AC units"],
        "ba": ("Fridge removal — Fort Collins", "Washer/dryer haul", "Water heater pickup"),
        "cta": "Book appliance removal <em>today</em>",
        "form_subject": "Appliance Removal Quote - Fort Collins",
        "items_ph": "List appliances — e.g. side-by-side fridge, electric dryer",
        "related": [("/junk-removal-fort-collins-co.html", "Junk Removal"), ("/blog/what-to-do-with-old-appliances-fort-collins.html", "Appliance Disposal Guide"), ("/garage-cleanouts-fort-collins-co.html", "Garage Cleanouts"), ("/", "Home")],
        "faqs": [
            ("How much does appliance removal cost in Fort Collins?", "Single appliances typically $99–$150. Multiple units or combined with other junk may fall in the $250–$400 range."),
            ("Do you remove refrigerators with freon?", "Yes — we haul fridges and freezers and ensure proper recycling per Colorado regulations."),
            ("Will you donate working appliances?", "Working fridges, washers, and dryers often go to Habitat ReStore — you get the tax receipt."),
            ("Do I need to unplug appliances before you arrive?", "Yes — please unplug and disconnect water lines if possible. We can handle basic disconnection in most cases."),
            ("Can you remove appliances from a garage?", "Yes — garage appliance removal is extremely common in Fort Collins."),
            ("Do you take commercial appliances?", "Residential appliances only. Commercial units require a custom quote."),
            ("What about built-in appliances?", "Built-in dishwashers and ovens may need disconnection — send photos for an accurate quote."),
            ("Is appliance removal same-day?", "Often yes for single items. Text photos for fastest confirmation."),
            ("Do you recycle appliances?", "Yes — metal and components go to certified recyclers, not illegal dumping."),
            ("Can appliances be part of a garage cleanout?", "Absolutely — appliances are included in full garage cleanout quotes at no per-item surcharge."),
        ],
    },
    {
        "slug": "mattress-removal-fort-collins-co.html",
        "title": "Mattress Removal Fort Collins CO | Easy Garage Cleaning",
        "desc": "Mattress and box spring removal in Fort Collins. No per-item surcharges — flat-rate from $99–150. Recycled properly. Text photos for estimate.",
        "h1": "Mattress Removal Fort Collins CO",
        "hero_em": "No mattress left behind",
        "hero_sub": "Old mattresses stuffed in the garage or leaning against the wall? We haul mattresses and box springs in Fort Collins — flat-rate, no franchise per-item fees.",
        "sms": "Hi! I need mattress removal in Fort Collins.",
        "stype": "Mattress Removal",
        "problem_title": "Mattresses are <em>awkward to dispose of</em>",
        "problem_sub": "They won't fit in your car, curbside won't take them, and they take up precious garage space.",
        "problems": [("🛏️", "Garage space hog", "Mattress leaning against the wall for months."), ("🚗", "Won't fit in your vehicle", "Even folded, a king won't fit in a sedan."), ("💸", "Franchise surcharges", "National haulers charge extra per mattress."), ("♻️", "Landfill fees", "Larimer County charges extra — we handle it.")],
        "yes_title": "Mattress removal <em>includes</em>",
        "yes": ["Mattresses — twin through king", "Box springs and foundations", "Adjustable bed bases", "Mattress toppers bundled with mattress", "Multiple mattresses in one trip", "Stairs and garage carry-out"],
        "ba": ("King mattress — Fort Collins", "Garage mattress stack", "Box spring removal"),
        "cta": "Book mattress removal <em>today</em>",
        "form_subject": "Mattress Removal Quote - Fort Collins",
        "items_ph": "Mattress size and quantity — e.g. queen mattress + box spring in garage",
        "related": [("/furniture-removal-fort-collins-co.html", "Furniture Removal"), ("/junk-removal-fort-collins-co.html", "Junk Removal"), ("/garage-cleanouts-fort-collins-co.html", "Garage Cleanouts"), ("/", "Home")],
        "faqs": [
            ("How much does mattress removal cost in Fort Collins?", "Single mattresses typically $99–$150 including box spring. Multiple mattresses quoted as a small load ($250–$400)."),
            ("Do you charge extra per mattress?", "No per-item surcharges. Multiple mattresses are quoted as one flat load price."),
            ("Can you remove a mattress from my garage?", "Yes — garage mattress removal is one of our most common single-item pickups."),
            ("Do you recycle mattresses?", "Yes — mattresses go to recycling facilities that comply with Colorado disposal rules."),
            ("Will you take stained or torn mattresses?", "Yes — condition doesn't matter. They go to recycling/disposal, not donation."),
            ("Do you remove adjustable bed frames?", "Yes — adjustable bases and foundations are included in mattress removal quotes."),
            ("How do I prepare for mattress pickup?", "Clear a path from the mattress to our truck. We'll handle the rest."),
            ("Same-day mattress removal?", "Often available for single items. Text photos for fastest booking."),
            ("Can mattresses be part of a garage cleanout?", "Yes — included in full cleanout quotes with no extra per-mattress fee."),
            ("Do you remove mattress from upstairs?", "Ground floor and garage yes. Second floor depends on access — send photos."),
        ],
    },
    {
        "slug": "storage-unit-cleanout-fort-collins-co.html",
        "title": "Storage Unit Cleanout Fort Collins CO | Easy Garage Cleaning",
        "desc": "Storage unit cleanout in Fort Collins — empty the unit in one trip. Flat-rate quotes, donation coordination. Stop paying rent on stuff you'll never use.",
        "h1": "Storage Unit Cleanout Fort Collins CO",
        "hero_em": "Stop paying for clutter",
        "hero_sub": "Done paying $150/month for a unit full of stuff you'll never use? We empty Fort Collins storage units in one trip — haul, donate, and sweep so you can cancel the lease.",
        "sms": "Hi! I need a storage unit cleanout in Fort Collins.",
        "stype": "Storage Unit Cleanout",
        "problem_title": "Storage units become <em>money pits</em>",
        "problem_sub": "Fort Collins has storage facilities along Harmony, College, and near I-25 — many hold years of forgotten belongings.",
        "problems": [("💳", "Monthly rent adds up", "$100–200/month for stuff you forgot about."), ("📦", "Overwhelming volume", "A 10x10 packed wall-to-wall — where do you start?"), ("🚛", "No truck big enough", "Your SUV can't fit three years of accumulation."), ("⏰", "Auction deadline", "Unit going to auction — need it empty fast.")],
        "yes_title": "Storage unit cleanout <em>covers</em>",
        "yes": ["Full unit empty-out in one visit", "Furniture, boxes, and bins", "Appliances and electronics", "Donation sorting and drop-off", "Dump runs for non-donatable items", "Broom-clean sweep before lock-up"],
        "ba": ("10x10 unit — Fort Collins", "Climate-controlled cleanout", "Auction save — Harmony Rd"),
        "cta": "Book storage unit <em>cleanout today</em>",
        "form_subject": "Storage Unit Cleanout Quote - Fort Collins",
        "items_ph": "Unit size and location — e.g. 10x15 on Harmony, mostly boxes and furniture",
        "related": [("/garage-cleanouts-fort-collins-co.html", "Garage Cleanouts"), ("/junk-removal-fort-collins-co.html", "Junk Removal"), ("/blog/estate-cleanout-checklist-colorado.html", "Estate Checklist"), ("/", "Home")],
        "faqs": [
            ("How much does a storage unit cleanout cost in Fort Collins?", "A partially full 5x10 runs $250–$400. Full 10x10 units typically $400–$650. Packed 10x20 units start at $650+. Text photos of the open unit."),
            ("Do you clean out climate-controlled units?", "Yes — all Fort Collins storage facilities including Public Storage, Extra Space, and CubeSmart."),
            ("Can you meet me at the unit?", "Yes — you unlock, we empty. You don't need to stay for the whole job after the walkthrough."),
            ("What if I haven't seen inside in years?", "Common situation. We sort, haul, and donate — you approve what's trash vs. keep during walkthrough."),
            ("Do you handle auction deadline cleanouts?", "Yes — urgent cleanouts are prioritized when schedule allows. Call for same-day availability."),
            ("Is there a discount for emptying multiple units?", "Multi-unit cleanouts get a bundled flat-rate quote — text photos of each unit."),
            ("Do you donate items from storage units?", "Yes — usable furniture and household goods go to ReStore/ARC with your tax receipt."),
            ("Do I need to rent a truck?", "No — we bring the truck. One trip for most standard units."),
            ("What storage facilities do you serve?", "All Fort Collins-area facilities — Harmony corridor, College Ave, Mulberry, and Timnath locations."),
            ("Can you sweep the unit after emptying?", "Yes — broom-clean is included so you can return keys and cancel lease."),
        ],
    },
    {
        "slug": "yard-debris-removal-fort-collins-co.html",
        "title": "Yard Debris Removal Fort Collins CO | Easy Garage Cleaning",
        "desc": "Yard debris removal in Fort Collins — branches, lawn equipment, outdoor furniture, and garage-adjacent clutter hauled away. Flat-rate quotes.",
        "h1": "Yard Debris Removal Fort Collins CO",
        "hero_em": "Yard clutter cleared fast",
        "hero_sub": "Branches from last year's storm, old patio furniture in the garage, a broken mower you'll never fix — we haul yard debris across Fort Collins in one trip.",
        "sms": "Hi! I need yard debris removal in Fort Collins.",
        "stype": "Yard Debris Removal",
        "problem_title": "Yard debris <em>piles up</em> fast",
        "problem_sub": "Fort Collins windstorms drop branches. Garage corners collect rusted lawn gear. Green waste bins aren't enough.",
        "problems": [("🌿", "Storm branch piles", "Too much for weekly yard waste pickup."), ("🚜", "Dead lawn equipment", "Broken mower taking garage space."), ("🪑", "Old patio furniture", "Cracked chairs nobody sits in."), ("🏠", "Garage overflow", "Yard stuff migrated indoors for winter.")],
        "yes_title": "Yard debris we <em>haul</em>",
        "yes": ["Tree branches and brush piles", "Lawn mowers and trimmers", "Patio furniture and grills", "Planters, pots, and garden decor", "Fencing sections and lumber", "Garage-stored outdoor equipment"],
        "ba": ("Branch pile — Fort Collins", "Garage mower removal", "Patio furniture haul"),
        "cta": "Book yard debris removal <em>today</em>",
        "form_subject": "Yard Debris Removal Quote - Fort Collins",
        "items_ph": "Describe yard debris — e.g. branch pile, old mower, patio set in garage",
        "related": [("/junk-removal-fort-collins-co.html", "Junk Removal"), ("/garage-cleanouts-fort-collins-co.html", "Garage Cleanouts"), ("/appliance-removal-fort-collins-co.html", "Appliance Removal"), ("/", "Home")],
        "faqs": [
            ("How much does yard debris removal cost in Fort Collins?", "Small piles and single items: $99–$250. Large branch piles or multiple items: $250–$400. Full garage + yard combo: $400–$650+."),
            ("Do you take tree branches?", "Yes — branches, brush, and storm debris. Very large logs may need a custom quote."),
            ("Can you remove yard debris from my garage?", "Yes — lawn equipment and outdoor furniture stored in garages is extremely common."),
            ("Do you take gas-powered lawn equipment?", "Yes — mowers, trimmers, blowers. Please drain fuel if possible; we can't haul full gas cans."),
            ("Is yard debris different from junk removal?", "Same crew, same flat-rate approach. Yard debris is just our label for outdoor/garage-adjacent items."),
            ("Do you take dirt or rocks?", "Small amounts yes. Large soil/rock loads need a custom quote due to weight."),
            ("Can you haul fencing materials?", "Yes — old fence sections, posts, and lumber from Fort Collins properties."),
            ("Same-day yard debris pickup?", "Often available for smaller loads. Text photos of the pile."),
            ("Do you compost or recycle yard waste?", "Green waste goes to appropriate Larimer County facilities — not mixed with landfill trash."),
            ("Can yard debris be part of a garage cleanout?", "Yes — outdoor items in the garage are included in full cleanout quotes."),
        ],
    },
    {
        "slug": "garage-organization-fort-collins-co.html",
        "title": "Garage Organization Fort Collins CO | Easy Garage Cleaning",
        "desc": "Garage organization in Fort Collins — zone layouts, shelving plans, labeled bins after cleanout. Keep your garage functional long-term. Flat-rate quotes.",
        "h1": "Garage Organization Fort Collins CO",
        "hero_em": "Keep it organized",
        "hero_sub": "Clearing junk is step one. We help Fort Collins homeowners set up zones, shelving, and labeled bins so the garage stays functional — not a clutter magnet again.",
        "sms": "Hi! I need garage organization help in Fort Collins.",
        "stype": "Garage Organization",
        "problem_title": "Clean today, <em>cluttered again</em> tomorrow",
        "problem_sub": "Without a system, Fort Collins garages refill within a year. Organization is how you protect the investment of a cleanout.",
        "problems": [("📦", "No zones", "Everything mixed — tools next to holiday decor."), ("🗂️", "No shelving plan", "Floor space wasted, walls empty."), ("🏷️", "Unlabeled bins", "Mystery boxes you'll never open."), ("🔄", "Relapse in 6 months", "Without a system, clutter creeps back.")],
        "yes_title": "Organization <em>services</em>",
        "yes": ["Zone planning — tools, sports, seasonal", "Shelving layout recommendations", "Bin labeling and categorization", "Keep vs. donate sorting during cleanout", "Wall hook and rack placement advice", "Maintenance tips for Northern Colorado homes"],
        "ba": ("Organized two-car — Fort Collins", "Zone layout — Fossil Creek", "Shelving reset — Midtown"),
        "cta": "Book garage organization <em>today</em>",
        "form_subject": "Garage Organization Quote - Fort Collins",
        "items_ph": "Describe your garage goals — e.g. two-car, need zones for tools and sports gear",
        "show_items": False,
        "related": [("/garage-cleanouts-fort-collins-co.html", "Garage Cleanouts"), ("/garage-cleaning-fort-collins-co.html", "Garage Cleaning"), ("/blog/garage-organizing-ideas-two-car-garage.html", "Organizing Ideas"), ("/", "Home")],
        "faqs": [
            ("Do you sell shelving and bins?", "We recommend layouts and can install basic shelving you purchase. We don't markup products — labor-only on organization."),
            ("How much does garage organization cost in Fort Collins?", "Organization add-on after cleanout: $200–$400 depending on garage size. Standalone organization (junk already gone): $250–$500."),
            ("Is organization included in a cleanout?", "Basic sorting into keep/donate/haul is included. Full zone setup and labeling is an add-on service."),
            ("Do you organize two-car garages?", "Yes — two-car garages are our specialty. We plan zones for both bays."),
            ("Can you organize without removing junk first?", "We strongly recommend cleanout first. Organizing around junk wastes time and money."),
            ("What organization systems do you recommend?", "Wall-mounted racks for bikes/tools, clear bins for seasonal, overhead storage for rarely-used items."),
            ("How long does garage organization take?", "Typically 2–4 hours after the space is cleared and clean."),
            ("Do you label bins?", "Yes — we label categories so everyone in the household knows where things go."),
            ("Can you organize a workshop area?", "Yes — tool zones, workbench placement, and lumber storage are common requests."),
            ("Will you help maintain organization long-term?", "We give you a simple maintenance checklist. Re-organize visits available on request."),
        ],
    },
]

CITIES = [
    {
        "slug": "junk-removal-loveland-co.html",
        "title": "Junk Removal Loveland CO | Easy Garage Cleaning",
        "desc": "Junk removal in Loveland, CO — flat-rate hauling from Centerra to Downtown. Text photos for a free quote in 5 minutes. Locally owned, same-day available.",
        "h1": "Junk Removal Loveland CO",
        "city": "Loveland",
        "service": "junk removal",
        "intro": "Loveland sits 20 minutes south of our Fort Collins home base — close enough for same-day service, local enough that you're not calling a Denver franchise. From Centerra townhomes to Mariana Butte ranch homes, we haul junk with flat-rate pricing and donation receipts.",
        "neighborhoods": "Centerra, Downtown Loveland, Mariana Butte, Boyd Lake, Namaqua, Wilson Ave corridor, and east-side neighborhoods off Boise Avenue.",
        "faqs": [
            ("How much does junk removal cost in Loveland?", "Same ranges as Fort Collins: $99–$150 single item, $250–$400 small load, $400–$650 medium, $650+ large. No Loveland travel surcharge."),
            ("Do you serve Centerra and Mariana Butte?", "Yes — all Loveland neighborhoods including Centerra, Mariana Butte, Boyd Lake, and Downtown."),
            ("How fast can you come to Loveland?", "Same-day and next-day often available. Loveland is a quick drive down US-287 from Fort Collins."),
            ("Are you insured in Loveland?", "Yes — fully licensed and insured for all Larimer County jobs."),
            ("Do you donate items from Loveland jobs?", "Yes — Habitat ReStore Loveland area, ARC, and Goodwill with tax receipt in your name."),
            ("What junk do you remove in Loveland?", "Furniture, appliances, mattresses, boxes, yard debris, garage contents — single items to full loads."),
            ("Is there a travel fee for Loveland?", "No hidden travel fees for Loveland — it's in our core service area."),
            ("Can I text photos for a Loveland quote?", "Yes — text to (970) 999-1818. We respond within 5 minutes during business hours."),
        ],
        "related_city": "/garage-cleanouts-loveland-co.html",
        "related_label": "Garage Cleanouts Loveland",
    },
    {
        "slug": "garage-cleanouts-loveland-co.html",
        "title": "Garage Cleanouts Loveland CO | Easy Garage Cleaning",
        "desc": "Garage cleanouts in Loveland, CO — full haul-out, sweep, and donation drop-off. Flat-rate $400–650 for most garages. Free quote in 5 minutes.",
        "h1": "Garage Cleanouts Loveland CO",
        "city": "Loveland",
        "service": "garage cleanout",
        "intro": "Loveland garages fill fast — bikes, camping gear, Centerra move-in boxes, and decades of accumulation in older Downtown homes. We empty the full garage, donate what's usable, sweep the floor, and hand you a flat-rate invoice with no surprises.",
        "neighborhoods": "Centerra, Downtown Loveland, Mariana Butte, Boyd Lake, Namaqua, Fairgrounds area, and Sculptor's Highway corridor.",
        "faqs": [
            ("How much does a garage cleanout cost in Loveland?", "Most single-car or moderate two-car garages: $400–$650. Packed garages or estate situations: $650+. Text photos for exact quote."),
            ("What's included in a Loveland garage cleanout?", "Full haul-out, donation coordination, dump fees, and floor sweep. Flat-rate — no hourly billing."),
            ("Do you serve all Loveland zip codes?", "Yes — 80537, 80538, and surrounding Larimer County addresses."),
            ("How long does a Loveland cleanout take?", "Single-car: 2–4 hours. Two-car: 3–5 hours depending on volume."),
            ("Can you do same-day garage cleanouts in Loveland?", "Often yes — text photos for fastest scheduling."),
            ("Do I need to be home?", "Present for 15-minute walkthrough. After that, many clients leave us to finish."),
            ("Do you donate from Loveland cleanouts?", "Yes — ReStore, ARC, Goodwill. Tax receipt in your name."),
            ("Are you local or a franchise?", "Local Fort Collins LLC — owner Zac Bezenek on every job."),
        ],
        "related_city": "/junk-removal-loveland-co.html",
        "related_label": "Junk Removal Loveland",
    },
    {
        "slug": "junk-removal-windsor-co.html",
        "title": "Junk Removal Windsor CO | Easy Garage Cleaning",
        "desc": "Junk removal in Windsor, CO — flat-rate hauling for Raindance, Pelican Lakes, and downtown Windsor. Text photos for estimate. Same-day available.",
        "h1": "Junk Removal Windsor CO",
        "city": "Windsor",
        "service": "junk removal",
        "intro": "Windsor is one of our busiest routes — 15 minutes east of Fort Collins with growing neighborhoods and garages full of move-in leftovers. We haul junk across Windsor with the same flat-rate, photo-quote process as Fort Collins.",
        "neighborhoods": "Raindance, Pelican Lakes, Boardwalk Park, downtown Windsor, Water Valley, and east Windsor new construction areas.",
        "faqs": [
            ("How much does junk removal cost in Windsor?", "$99–$150 single item, $250–$400 small, $400–$650 medium, $650+ large. No Windsor travel fee."),
            ("Do you serve Raindance and Pelican Lakes?", "Yes — all Windsor neighborhoods including master-planned communities."),
            ("How fast can you get to Windsor?", "Same-day and next-day frequently available — Windsor is 15 minutes from our base."),
            ("Are you insured in Windsor?", "Yes — fully licensed and insured throughout Larimer and Weld County border areas."),
            ("What do you haul in Windsor?", "Garage junk, furniture, appliances, mattresses, yard debris, and storage contents."),
            ("Can I get a photo quote for Windsor?", "Yes — text photos to (970) 999-1818 for a 5-minute flat-rate response."),
            ("Do you donate usable items?", "Yes — with tax receipt. Usable goods go to ReStore and ARC."),
            ("Is Windsor in your service area?", "Yes — core service area with no travel surcharge."),
        ],
        "related_city": "/garage-cleanouts-windsor-co.html",
        "related_label": "Garage Cleanouts Windsor",
    },
    {
        "slug": "garage-cleanouts-windsor-co.html",
        "title": "Garage Cleanouts Windsor CO | Easy Garage Cleaning",
        "desc": "Garage cleanouts in Windsor, CO — full empty-out, donation, and sweep. Flat-rate pricing. Locally owned Fort Collins crew, 15 min away.",
        "h1": "Garage Cleanouts Windsor CO",
        "city": "Windsor",
        "service": "garage cleanout",
        "intro": "Windsor's newer homes have big three-car garages that become storage magnets. Older downtown Windsor properties hide decades of tools and clutter. We do full garage cleanouts — haul, donate, sweep — with flat-rate quotes before we start.",
        "neighborhoods": "Raindance, Pelican Lakes, Water Valley, Boardwalk Park, downtown Windsor, and east-side development corridors.",
        "faqs": [
            ("How much does a garage cleanout cost in Windsor?", "Most garages: $400–$650. Large three-car or packed garages: $650+. Photo quote for exact price."),
            ("Do you clean out three-car garages in Windsor?", "Yes — common in Raindance and Pelican Lakes. Quoted by volume, not hourly."),
            ("What's included?", "Labor, hauling, dump fees, donations, and floor sweep. All-inclusive flat rate."),
            ("Same-day Windsor cleanouts?", "Often available — text photos to check today's schedule."),
            ("Do you serve Weld County side of Windsor?", "Yes — all Windsor addresses in our service area."),
            ("Owner on every job?", "Yes — Zac Bezenek, local owner, on every Windsor cleanout."),
            ("Donation receipts?", "Included — Habitat ReStore and ARC drop-offs with your tax receipt."),
            ("How do I book?", "Text photos or use the quote form — 5-minute callback during business hours."),
        ],
        "related_city": "/junk-removal-windsor-co.html",
        "related_label": "Junk Removal Windsor",
    },
    {
        "slug": "junk-removal-wellington-co.html",
        "title": "Junk Removal Wellington CO | Easy Garage Cleaning",
        "desc": "Junk removal in Wellington, CO — flat-rate hauling for acreage properties, barns, and garages. Text photos for quote. No travel surcharge.",
        "h1": "Junk Removal Wellington CO",
        "city": "Wellington",
        "service": "junk removal",
        "intro": "Wellington properties are bigger — acreage, barns, outbuildings, and garages that accumulate years of ranch gear. We're 15 minutes north of Fort Collins and haul junk across Wellington with flat-rate pricing sized to the job, not the hour.",
        "neighborhoods": "Downtown Wellington, Crystal Lakes, Wellington Heights, acreage properties along CR 7, and north Larimer County rural addresses.",
        "faqs": [
            ("How much does junk removal cost in Wellington?", "Same core ranges: $99–$150 single item to $650+ for large property hauls. Acreage jobs quoted by photo."),
            ("Do you serve rural Wellington addresses?", "Yes — including acreage, barns, and outbuildings. Send photos of access paths."),
            ("Is there a travel fee for Wellington?", "No — Wellington is in our core Northern Colorado service area."),
            ("Can you haul ranch equipment and barn junk?", "Yes — old fencing, farm equipment, and barn clutter are common Wellington jobs."),
            ("Same-day junk removal in Wellington?", "Often available — call or text for today's schedule."),
            ("Do you donate from Wellington jobs?", "Yes — usable household goods to ReStore/ARC with tax receipt."),
            ("Are you insured for rural properties?", "Yes — general liability and commercial auto on every job."),
            ("How do I get a quote?", "Text photos to (970) 999-1818 — include access info for long driveways if relevant."),
        ],
        "related_city": "/garage-cleanouts-wellington-co.html",
        "related_label": "Garage Cleanouts Wellington",
    },
    {
        "slug": "garage-cleanouts-wellington-co.html",
        "title": "Garage Cleanouts Wellington CO | Easy Garage Cleaning",
        "desc": "Garage cleanouts in Wellington, CO — barns, shops, and residential garages emptied in one trip. Flat-rate quotes. Locally owned crew from Fort Collins.",
        "h1": "Garage Cleanouts Wellington CO",
        "city": "Wellington",
        "service": "garage cleanout",
        "intro": "Wellington garages and shop buildings collect ranch equipment, seasonal gear, and years of 'I'll deal with it later.' We empty residential garages, pole barns, and workshop spaces — haul, donate, sweep — with upfront flat-rate pricing.",
        "neighborhoods": "Downtown Wellington, Crystal Lakes, acreage along CR 7 and CR 9, and north county rural properties.",
        "faqs": [
            ("How much does a garage cleanout cost in Wellington?", "$400–$650 for standard residential garages. Large shops/barns: $650+ depending on volume."),
            ("Do you clean out barns and pole buildings?", "Yes — common on Wellington acreage. Photo quote includes access and volume assessment."),
            ("What's included?", "Full empty-out, hauling, donations, disposal, and sweep. Flat-rate, all-inclusive."),
            ("Rural property access?", "We serve long driveways and rural addresses — note access in your quote request."),
            ("Same-day Wellington service?", "Available when schedule allows — text photos for fastest response."),
            ("Estate cleanouts in Wellington?", "Yes — multi-building property cleanouts quoted individually from $650+."),
            ("Donation coordination?", "Included — tax receipt provided for usable donations."),
            ("Who does the work?", "Owner Zac Bezenek and crew — local Fort Collins LLC, not a franchise."),
        ],
        "related_city": "/junk-removal-wellington-co.html",
        "related_label": "Junk Removal Wellington",
    },
]

PROJECTS = [
    {
        "slug": "projects/fort-collins-garage-cleanout-old-town.html",
        "title": "Project: Old Town Fort Collins Garage Cleanout | Easy Garage Cleaning",
        "desc": "Before/after case study — packed single-car garage in Old Town Fort Collins cleared in one afternoon. Flat-rate garage cleanout by Easy Garage Cleaning.",
        "h1": "Old Town Fort Collins Garage Cleanout",
        "city": "Fort Collins",
        "neighborhood": "Old Town",
        "job_type": "Full garage cleanout",
        "time": "3.5 hours",
        "problem": "Client couldn't park in their Old Town single-car garage for two years. Boxes, old furniture, camping gear, and tools filled the bay wall-to-wall.",
        "removed": "12 boxes, sectional couch, queen mattress, camping gear, 3 bookshelves, broken lawnmower, and miscellaneous household junk.",
        "result": "Empty garage with swept floor — client parked inside same evening. Usable items donated to Habitat ReStore with tax receipt.",
    },
    {
        "slug": "projects/loveland-storage-unit-cleanout.html",
        "title": "Project: Loveland Storage Unit Cleanout | Easy Garage Cleaning",
        "desc": "Case study — 10x10 storage unit in Loveland emptied in one trip. Client cancelled $165/month lease. Flat-rate cleanout.",
        "h1": "Loveland Storage Unit Cleanout",
        "city": "Loveland",
        "neighborhood": "Harmony corridor",
        "job_type": "Storage unit cleanout",
        "time": "2 hours",
        "problem": "Client paying $165/month for a 10x10 unit filled with move-in boxes and furniture they hadn't opened in 4 years.",
        "removed": "30+ boxes, dining table set, desk, lamps, holiday decor, and old electronics.",
        "result": "Unit broom-clean and keys returned. Client cancelled lease — saving $1,980/year. Donation receipt for usable furniture.",
    },
    {
        "slug": "projects/windsor-garage-junk-removal.html",
        "title": "Project: Windsor Garage Junk Removal | Easy Garage Cleaning",
        "desc": "Case study — Raindance Windsor two-car garage junk removal. Appliances, furniture, and boxes cleared same day.",
        "h1": "Windsor Garage Junk Removal",
        "city": "Windsor",
        "neighborhood": "Raindance",
        "job_type": "Garage junk removal",
        "time": "4 hours",
        "problem": "Raindance two-car garage used as storage since move-in. Old fridge, kids' outgrown sports gear, and contractor leftovers blocked both bays.",
        "removed": "Refrigerator, washer, 8 furniture pieces, sports equipment, and 2 truckloads of boxes and debris.",
        "result": "Both bays clear — family parked both cars inside. Working washer donated to ReStore.",
    },
]
