/* Business records stay server-side. No localStorage, public account lookup or analytics. */
(() => {
'use strict';
const $ = id => document.getElementById(id), esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const params = new URLSearchParams(location.search), staff = params.get('staff') === '1';
let account = staff ? params.get('account') || '' : '', data = null, tab = 'overview', listNext = '', listHistory = [], listCursor = '';
const money = v => v == null ? 'Not issued' : Number(v).toLocaleString('en-US', { style: 'currency', currency: 'USD' });
const pretty = v => String(v || '').replaceAll('_',' '), id = () => crypto.randomUUID().replaceAll('-','');
const stamp = v => v ? new Date(v).toLocaleString('en-US', {dateStyle:'medium', timeStyle:'short'}) : '';
function toast(message, bad = false) { $('notice').textContent = message; $('notice').className = 'show' + (bad ? ' error' : ''); clearTimeout(toast.timer); toast.timer = setTimeout(() => $('notice').className = '', 7000); }
function endpoint() { const p = new URLSearchParams(); if (staff) { p.set('staff','1'); if (account) p.set('account',account); if (!account && listCursor) p.set('cursor',listCursor); } return '/api/business-hub' + (p.size ? '?' + p : ''); }
async function api(payload) {
 const r = await fetch(endpoint(), { method: payload ? 'POST' : 'GET', credentials:'same-origin', cache:'no-store', headers: payload ? {'Content-Type':'application/json','X-EGC-Business':'1'} : {}, ...(payload ? {body:JSON.stringify(payload)} : {}) });
 const body = await r.json().catch(() => ({error:'The service returned an unreadable response. Please retry.'})); if (!r.ok) throw Object.assign(new Error(body.error || 'Request failed.'), {status:r.status}); return body;
}
function setAccount(value) { account = value; const p = new URLSearchParams(); if (staff) p.set('staff','1'); if (account) p.set('account',account); history.replaceState(null,'',location.pathname + (p.size ? '?' + p : '')); }
function field(label,name,type='text',value='',required=false,max=180) { return `<label>${esc(label)}<input name="${esc(name)}" type="${type}" value="${esc(value)}" maxlength="${max}" ${required?'required':''}></label>`; }
function area(label,name,value='',required=false,max=1600) { return `<label>${esc(label)}<textarea name="${name}" maxlength="${max}" ${required?'required':''}>${esc(value)}</textarea></label>`; }
function propSelect() { return `<label>Property<select name="propertyId" required><option value="">Select a property</option>${data.properties.map(p=>`<option value="${p.id}">${esc(p.name)} · ${esc(p.address)}</option>`).join('')}</select></label>`; }
function propName(value) { return data.properties.find(p=>p.id===value)?.name || 'Property'; }
const pill = value => `<span class="pill">${esc(pretty(value))}</span>`;
const empty = text => `<p class="empty">${esc(text)}</p>`;
function invite(result) { const url = new URL('/business-hub',location.origin); url.hash = 'invite=' + result.invite; $('invite-url').value = url.href; $('invite-recipient').textContent = 'For ' + result.email + '. This link opens only their company account.'; $('invite-dialog').showModal(); }
async function load() {
 try { data = await api(); $('gate').hidden=true; $('app').hidden=false; $('all-accounts').hidden=!staff||!account; render(); }
 catch (error) { data=null; $('app').hidden=true; $('gate').hidden=false; $('gate-status').textContent=error.message; if (error.status!==401&&error.status!==403) toast(error.message,true); }
}
function projectsTable(items, invoices=false) {
 if(!items.length) return empty(invoices?'No invoices have been issued for the linked projects.':'No projects have been shared with this company yet. Submit a request to get started.');
 return `<div class="table-wrap"><table><thead><tr><th>Property / project</th><th>${invoices?'Invoice':'Status / date'}</th><th>${invoices?'Balance':'Quote'}</th><th></th></tr></thead><tbody>${items.map(p=>p.unavailable?`<tr><td>${esc(propName(p.propertyId))}</td><td colspan="3">Project unavailable. Contact EGC; no balance assumed.</td></tr>`:`<tr><td><strong>${esc(propName(p.propertyId))}</strong><small>${esc(p.service)}</small></td><td>${invoices?esc(p.invoiceNumber):pill(p.status)}<small>${invoices?esc(p.dueDate?'Due '+p.dueDate:pretty(p.invoiceStatus)):esc(p.date?p.date+' '+p.time:'Date not confirmed')}</small></td><td>${p.paymentNeedsReview&&invoices?'Payment under review':money(invoices?p.balance:p.total)}<small>${invoices?(p.paid!=null?'Recorded paid: '+money(p.paid):''):esc(pretty(p.quoteStatus))}</small></td><td>${!staff?`<button data-open="${esc(p.jobId)}" ${p.quoteStatus==='not_issued'?'disabled title="EGC will release the project after sharing its quote"':''}>${invoices?'View / pay':'Open project'}</button>`:''}${invoices&&p.receiptUrl?` <a class="action" href="${esc(p.receiptUrl)}" target="_blank" rel="noopener noreferrer">Receipt</a>`:''}${staff&&data.viewer.permissions.link?`<button data-unlink="${esc(p.jobId)}">Remove access</button>`:''}</td></tr>`).join('')}</tbody></table></div>`;
}
function requestsList(items) {
 return items.length?items.slice().reverse().map(r=>`<article class="request"><header><div><strong>${esc(r.service)}</strong><small>${esc(propName(r.propertyId))} · ${esc(stamp(r.createdAt))}</small></div>${pill(r.status)}</header><p>${esc(r.scope)}</p><small>Preferred date: ${esc(r.preferredDate||'Flexible')} · Payer: ${esc(r.payer)}${r.purchaseOrder?' · PO '+esc(r.purchaseOrder):''}</small>${r.onsiteContact?`<small>On-site contact: ${esc(r.onsiteContact)}</small>`:''}${staff?`<div class="request-actions"><button data-request="${r.id}" data-status="reviewing">Mark reviewing</button><button data-request="${r.id}" data-status="awaiting_customer">Awaiting client</button><button data-request="${r.id}" data-status="closed">Close request</button></div>`:''}</article>`).join(''):empty('No service requests yet. New requests appear here after they are saved.');
}
function overview() {
 const active = data.requests.filter(r=>r.status!=='closed').length, issued = data.projects.filter(p=>p.invoiceNumber && p.balance!=null), balance=issued.reduce((s,p)=>s+p.balance,0);
 return `<div class="metrics"><div class="metric"><span>Saved properties</span><strong>${data.properties.length}</strong><small>This company account</small></div><div class="metric"><span>Open requests</span><strong>${active}</strong><small>Not all are booked jobs</small></div><div class="metric"><span>Shared projects</span><strong>${data.projects.filter(p=>!p.unavailable).length}</strong><small>Authorized projects only</small></div><div class="metric"><span>Issued invoice balance</span><strong>${money(balance)}</strong><small>${data.coverage.unavailable||data.coverage.paymentReview?'Available verified records only':'Excludes unissued quotes'}</small></div></div><div class="grid"><section class="card"><div class="card-head"><h2>Your latest requests</h2><button data-tab="requests">All requests</button></div>${requestsList(data.requests.slice(-3))}</section><section class="card"><h2>Your business rates</h2><div class="rate"><strong>10%</strong><p>Partner service savings<small>Eligible cleanout, removal, cleaning and organization services.</small></p></div><div class="rate"><strong>15%</strong><p>Coordinated properties<small>Three or more properties approved together and serviced within 30 days.</small></p></div><p class="small">Discounts do not stack. The full-service reset base has a $450 minimum after discounts; standalone services have a $99 minimum. Products, specialty handling, access charges and the fixed $139 curbside offer are excluded. Your accepted quote controls.</p><p class="small">Full-service projects: 50% upfront and 50% on completion. Credit terms require a written agreement.</p></section></div><section class="card"><h2>Projects at a glance</h2>${projectsTable(data.projects.slice(0,5))}</section>`;
}
function propertyForm(p={}) { return `<form data-form="property"><input type="hidden" name="propertyId" value="${esc(p.id||'')}">${field('Property name','name','text',p.name,true,100)}${field('Full property address','address','text',p.address,true,300)}${field('Site contact','contact','text',p.contact,false,150)}${area('Parking and access notes (do not enter permanent codes)','access',p.access,false,800)}<button class="primary">${p.id?'Save property changes':'Add property'}</button></form>`; }
function properties() { return `<div class="grid"><section class="card"><h2>Company properties</h2>${data.properties.length?data.properties.map(p=>`<article class="property"><h3>${esc(p.name)}</h3><p>${esc(p.address)}</p>${p.contact?`<p>${esc(p.contact)}</p>`:''}${p.access?`<p>${esc(p.access)}</p>`:''}${data.viewer.permissions.request?`<details><summary>Edit property</summary>${propertyForm(p)}</details>`:''}</article>`).join(''):empty('Add the first property to create a service request.')}</section>${data.viewer.permissions.request?`<section class="card"><h2>Add a property</h2>${propertyForm()}</section>`:''}</div>`; }
function requests() { return `<div class="grid"><section class="card"><h2>Service requests</h2>${requestsList(data.requests)}</section>${data.viewer.permissions.request?`<section class="card"><h2>Request service</h2><p class="small">This sends a request to EGC account management. It does not reserve a time or authorize a charge. EGC confirms scope, pricing and scheduling.</p>${data.properties.length?`<form data-form="request" data-id="${id()}">${propSelect()}<label>Service<select name="service"><option>Garage cleanout and reset</option><option>Junk / furniture / appliance removal</option><option>Property or storage cleanout</option><option>Cleaning and organization</option><option>Storage installation</option><option>Recurring maintenance</option><option>Other property service</option></select></label>${area('What should be done? What stays and what goes?','scope','',true)}${field('Preferred service date (not a confirmed appointment)','preferredDate','date')}${field('Purchase order / reference (optional)','purchaseOrder','text','',false,100)}${field('On-site contact (optional)','onsiteContact','text','',false,160)}${field('Who will pay for this work?','payer','text',data.account.company,true,160)}<button class="primary">Submit service request</button></form>`:`<p>Add a property first.</p><button data-tab="properties">Add property</button>`}</section>`:''}</div>`; }
function projects() { return `<section class="card"><h2>Shared company projects</h2><p class="small">Only projects explicitly authorized for this business appear here. Quotes, approvals, payments and project photos open in the private project workspace with your company role.</p>${projectsTable(data.projects)}</section>${staff&&data.viewer.permissions.link?`<section class="card"><h2>Authorize and link an existing EGC project</h2><form data-form="link">${propSelect()}${field('Canonical EGC job ID','jobId','text','',true,120)}<label>Related request (optional)<select name="requestId"><option value="">No request link</option>${data.requests.map(r=>`<option value="${r.id}">${esc(propName(r.propertyId))} · ${esc(r.service)}</option>`).join('')}</select></label><label class="check"><input type="checkbox" name="sharingAuthorized" required><span>I verified that this company is authorized to access this project, its scope and billing. A referral alone is not permission to share.</span></label><button class="primary">Authorize project sharing</button></form><p class="small">This preserves the job's original source and financial records. It does not create or change an appointment.</p></section>`:''}`; }
function billing() { return `<section class="card"><div class="card-head"><h2>Issued invoices</h2><button id="export-invoices">Export invoice summary</button></div><p class="small">This is a cross-project invoice summary, not a new consolidated invoice. Payments and receipts stay with their original project. Only billing users and account administrators can pay.</p>${projectsTable(data.projects.filter(p=>p.invoiceNumber||p.unavailable),true)}</section>${data.viewer.permissions.team?`<section class="card"><h2>Billing contact and reference</h2><form data-form="account">${field('Billing email','billingEmail','email',data.account.billingEmail,true)}${field('Account / purchase-order reference','reference','text',data.account.reference,false,150)}<button class="primary">Save account details</button></form></section>`:''}`; }
function team() { return `<div class="grid"><section class="card"><h2>People with account access</h2><div class="table-wrap"><table><thead><tr><th>Person</th><th>Role / access</th><th></th></tr></thead><tbody>${data.members.map(m=>`<tr><td><strong>${esc(m.name)}</strong>${m.email?`<small>${esc(m.email)}</small>`:''}</td><td>${esc(pretty(m.role))}<small>${esc(m.status)}</small></td><td>${data.viewer.permissions.team&&m.status!=='revoked'?`<button data-revoke="${m.id}">Revoke access</button>`:''}</td></tr>`).join('')}</tbody></table></div><p class="small">Administrators manage the team, request work, approve and pay. Property managers request and approve work. Billing users pay. Viewers are read-only. Every role can see the projects explicitly shared with this company.</p></section>${data.viewer.permissions.team?`<section class="card"><h2>Invite a colleague</h2><form data-form="invite">${field('Full name','name','text','',true,100)}${field('Email address','email','email','',true)}<label>Account role<select name="role"><option value="manager">Property manager</option><option value="billing">Billing</option><option value="viewer">Read-only viewer</option><option value="admin">Account administrator</option></select></label><button class="primary">Create private invitation</button></form><p class="small">To replace another person's expired sign-in link, enter their existing email. The new invitation replaces their prior access and must be delivered privately. Only an EGC manager can restore the final administrator.</p></section>`:''}</div>`; }
function messages() { const writable=staff||data.viewer.role!=='viewer'; return `<section class="card"><h2>Account conversation</h2><p class="small">Messages here are visible to this company and its EGC account team. They are saved to the business hub, not sent as an SMS or email. For urgent timing changes, call Zoe.</p><div class="thread">${data.messages.length?data.messages.map(m=>`<article class="message ${m.fromStaff?'staff':''}"><b>${esc(m.author)}</b><small>${esc(stamp(m.at))}${m.requestId?' · Service request':''}</small><p>${esc(m.body)}</p></article>`).join(''):empty('No account messages yet.')}</div>${writable?`<form data-form="message" data-id="${id()}"><label>Related request (optional)<select name="requestId"><option value="">General account message</option>${data.requests.map(r=>`<option value="${r.id}">${esc(propName(r.propertyId))} · ${esc(r.service)}</option>`).join('')}</select></label>${area('Message to the account team','body','',true)}<button class="primary">Save message to account</button></form>`:''}</section>`; }
function accounts() { listNext=data.next||''; return `<div class="grid"><section class="card"><h2>Business accounts</h2>${data.limited?'<p class="coverage">Showing the first 50 assigned accounts. Ask a manager for the complete paged list.</p>':''}${data.accounts.length?`<div class="table-wrap"><table><thead><tr><th>Company</th><th>Properties</th><th>New requests</th><th></th></tr></thead><tbody>${data.accounts.map(a=>`<tr><td><strong>${esc(a.company)}</strong><small>${esc(a.status)}</small></td><td>${a.properties}</td><td>${a.requests}</td><td><button data-account="${a.id}">Open account</button></td></tr>`).join('')}</tbody></table></div>`:empty('No business accounts on this page. Create the first account below.')}<div class="request-actions">${listHistory.length?'<button id="previous-accounts">Previous page</button>':''}${listNext?'<button id="next-accounts">Next page</button>':''}</div></section><section class="card"><h2>Onboard a business client</h2><p class="small">Create a separate company workspace and a private invitation for its first administrator. Existing homeowner jobs are not shared automatically.</p><form data-form="create">${field('Company name','company','text','',true,150)}${field('First administrator name','name','text','',true,100)}${field('Administrator email','email','email','',true)}${field('Billing email (optional)','billingEmail','email')}<button class="primary">Create account and invitation</button></form></section></div>`; }
function render() {
 const list=staff&&!account, p=data.viewer?.permissions||{}, names={overview:'Overview',properties:'Properties',requests:'Service requests',projects:'Projects & quotes',billing:'Invoices & billing',team:'Team access',messages:'Messages'};
 $('company').innerHTML=list?'EGC account management<small>Authorized staff</small>':`${esc(data.account.company)}<small>${esc(data.viewer.name)} · ${esc(pretty(data.viewer.role))}</small>`;
 $('tabs').innerHTML=list?'<button aria-current="page">Business accounts</button>':Object.entries(names).map(([key,name])=>`<button data-tab="${key}" ${key===tab?'aria-current="page"':''}>${name}</button>`).join('');
 $('heading').textContent=list?'Business accounts':names[tab]; $('subheading').textContent=list?'Onboard clients, review requests and manage authorized project sharing.':'Company-level workspace · ' + (data.updatedAt?'Account updated '+stamp(data.updatedAt):'');
 $('workspace-kicker').textContent=staff?'EGC ACCOUNT MANAGEMENT':'BUSINESS PARTNERSHIPS';
 const c=data.coverage||{}; $('coverage').hidden=!(c.unavailable||c.paymentReview); $('coverage').textContent=`${c.unavailable||0} linked project(s) unavailable; ${c.paymentReview||0} payment record(s) awaiting review. Totals include only available, verified issued-invoice balances.`;
 $('content').innerHTML=list?accounts():({overview,properties,requests,projects,billing,team,messages}[tab]||overview)();
}
function exportInvoices() {
 const rows=[['Property','Job ID','Invoice','Status','Due date','Total','Recorded paid','Balance','Payment review']];
 data.projects.filter(p=>p.invoiceNumber||p.unavailable).forEach(p=>rows.push([propName(p.propertyId),p.jobId,p.invoiceNumber||'',p.unavailable?'Unavailable':p.invoiceStatus,p.dueDate||'',p.total??'',p.paid??'',p.balance??'',p.paymentNeedsReview?'Yes':'No']));
 const cell=v=>'"'+String(v).replace(/^[=+\-@\t\r]/,"'$&").replaceAll('"','""')+'"';
 const blob=new Blob(['\ufeff'+rows.map(r=>r.map(cell).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='EGC-issued-invoices.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);
}
document.addEventListener('click',async event=>{
 const button=event.target.closest('button'); if(!button) return;
 if(button.dataset.tab){tab=button.dataset.tab;render();return;}
 if(button.dataset.account){setAccount(button.dataset.account);tab='overview';await load();return;}
 if(button.id==='refresh'){await load();return;}
 if(button.id==='all-accounts'){setAccount('');await load();return;}
 if(button.id==='next-accounts'){listHistory.push(listCursor);listCursor=listNext;await load();return;}
 if(button.id==='previous-accounts'){listCursor=listHistory.pop()||'';await load();return;}
 if(button.id==='export-invoices'){exportInvoices();return;}
 if(button.id==='copy-invite'){try{await navigator.clipboard.writeText($('invite-url').value);toast('Private invitation copied.');}catch{$('invite-url').focus();$('invite-url').select();toast('Select and copy the invitation link.');}return;}
 let payload=null;
 if(button.dataset.open)payload={action:'open_project',jobId:button.dataset.open};
 if(button.dataset.revoke&&confirm('Revoke this person’s business and delegated project access?'))payload={action:'revoke_member',memberId:button.dataset.revoke};
 if(button.dataset.unlink&&confirm('Remove this company’s access to this project? The job itself will not be deleted.'))payload={action:'unlink_project',jobId:button.dataset.unlink};
 if(button.dataset.request)payload={action:'update_request',requestId:button.dataset.request,status:button.dataset.status};
 if(button.id==='logout')payload={action:'logout'};
 if(!payload)return; button.disabled=true;
 try{const result=await api(payload);if(payload.action==='open_project'){location.assign(result.url);return;}if(button.id==='logout'&&staff)await fetch('/api/hub-auth',{method:'DELETE',credentials:'same-origin'});await load();if(payload.action!=='logout')toast('Saved.');}
 catch(error){toast(error.message,true);}finally{button.disabled=false;}
});
document.addEventListener('submit',async event=>{
 const form=event.target;if(form.method==='dialog')return;event.preventDefault();const button=form.querySelector('button[type=submit],button.primary'); if(button)button.disabled=true;
 const values=Object.fromEntries(new FormData(form));
 try{
  if(form.id==='staff-login'){const result=await fetch('/api/hub-auth',{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json'},body:JSON.stringify(values)});const b=await result.json();if(!result.ok)throw new Error(b.error||'Sign-in failed.');form.reset();await load();return;}
  if(form.id==='invite-form'){await api({action:'redeem',invite:values.invite});form.reset();await load();return;}
  const kind=form.dataset.form,actions={property:'save_property',request:'request_service',invite:'invite_member',message:'message',account:'save_account',create:'create_account',link:'link_project'};
  const payload={...values,action:actions[kind]};if(!payload.action)return;
  if(kind==='request')payload.requestId=form.dataset.id;
  if(kind==='message')payload.messageId=form.dataset.id;
  if(kind==='link')payload.sharingAuthorized=Boolean(form.querySelector('[name=sharingAuthorized]').checked);
  const result=await api(payload);if(kind==='create'){setAccount(result.accountId);tab='overview';}await load();if(result.invite)invite(result);else toast(kind==='request'?'Request saved. EGC still needs to confirm pricing and the service date.':kind==='message'?'Message saved in this account.':'Saved.');
 }catch(error){toast(error.message,true);if(form.id==='staff-login'||form.id==='invite-form')$('gate-status').textContent=error.message;}finally{if(button)button.disabled=false;}
});
if(staff){$('staff-login').hidden=false;$('invite-form').hidden=true;$('gate-title').textContent='EGC account management';$('gate-copy').textContent='Use your existing EGC staff sign-in. Business managers manage all accounts; sales staff see the accounts they onboard.';$('gate-kicker').textContent='STAFF ACCESS';$('staff-entry').href='/business-hub';$('staff-entry').textContent='Back to business client sign-in';}
const fragment=new URLSearchParams(location.hash.slice(1)),invitation=fragment.get('invite');
if(location.hash)history.replaceState(null,'',location.pathname+location.search);
if(invitation&&!staff){$('invite-code').value=invitation;$('gate-title').textContent='Your business invitation';$('gate-copy').textContent='Open the account using this private invitation. Only continue if it was sent to you.';}
else load();
})();
