/* EGC Operating System — HighLevel is CRM; this hub runs the service. */
(function(){
'use strict';
const S={active:'today',installed:false,integrations:{},ghl:{loading:true,error:'',pipelines:[],opportunities:[]},walks:{loading:true,error:'',events:[]}};
const $=s=>document.querySelector(s),all=s=>Array.from(document.querySelectorAll(s));
const esc=v=>String(v==null?'':v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=v=>Number(v||0).toLocaleString('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0});
const day=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'America/Denver',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const dateLabel=v=>{try{return new Date(v).toLocaleDateString('en-US',{weekday:'short',month:'short',day:'numeric',timeZone:'America/Denver'})}catch{return v||'TBD'}};
const timeLabel=v=>{try{return new Date(v).toLocaleTimeString('en-US',{hour:'numeric',minute:'2-digit',timeZone:'America/Denver'})}catch{return''}};
const icons={today:'M4 5h16v15H4zM8 3v4m8-4v4M4 10h16',pipeline:'M4 6h4v12H4zm6 3h4v9h-4zm6-5h4v14h-4z',walkthroughs:'M4 4h16v16H4zM8 2v4m8-4v4M7 11h4m-4 4h7',delivery:'M3 6h12v11H3zm12 4h4l2 3v4h-6M7 19a2 2 0 1 0 0-4 2 2 0 0 0 0 4Zm11 0a2 2 0 1 0 0-4 2 2 0 0 0 0 4Z',scorecard:'M4 19V9m5 10V5m5 14v-7m5 7V3',proof:'M4 5h4l2-2h4l2 2h4v15H4zM12 9a4 4 0 1 0 0 8 4 4 0 0 0 0-8Z',playbook:'M5 4h11a3 3 0 0 1 3 3v13H8a3 3 0 0 1-3-3zm0 0v13a3 3 0 0 0 3 3',settings:'M12 15.5a3.5 3.5 0 1 0 0-7 3.5 3.5 0 0 0 0 7Zm0-12v2m0 13v2m8.5-8.5h-2m-13 0h-2m14.5-6-1.5 1.5m-9 9L6 18m12 0-1.5-1.5m-9-9L6 6',external:'M14 4h6v6m0-6-9 9M10 6H4v14h14v-6'};
const svg=n=>`<svg viewBox="0 0 24 24" aria-hidden="true"><path d="${icons[n]||icons.today}"/></svg>`;
const nav=[['RUN THE DAY','today','Today'],['RUN THE DAY','pipeline','HighLevel pipeline'],['RUN THE DAY','walkthroughs','Walkthroughs'],['RUN THE DAY','delivery','Job delivery'],['GROW THE ENGINE','scorecard','Scorecard'],['GROW THE ENGINE','proof','Proof library'],['GROW THE ENGINE','playbook','EGC playbook'],['SYSTEM','settings','Integrations']];

function install(){const dash=$('#dashboard');if(!dash||dash.classList.contains('ops-installed'))return;dash.classList.add('ops-installed');let group='';const shell=document.createElement('div');shell.className='ops-shell';shell.innerHTML=`<aside class="ops-rail" id="ops-rail"><div class="ops-brand"><span class="ops-brand-mark">EGC</span><span><strong>Field Command</strong><small>RUN THE PROMISE</small></span></div><nav class="ops-nav" aria-label="Employee hub">${nav.map(n=>{const h=n[0]!==group?`<div class="ops-nav-label">${group=n[0]}</div>`:'';return h+`<button data-ops-tab="${n[1]}" onclick="opsGo('${n[1]}')">${svg(n[1])}<span>${n[2]}</span></button>`}).join('')}</nav><div class="ops-rail-foot"><a href="https://app.gohighlevel.com/" target="_blank" rel="noopener">${svg('external')}<span>Open HighLevel<small>CRM · conversations · automation</small></span></a><a href="/crew/">${svg('delivery')}<span>Open crew tools<small>Field execution</small></span></a></div></aside><section class="ops-workspace"><header class="ops-topbar"><button class="ops-menu" type="button" aria-label="Open menu" onclick="document.getElementById('ops-rail').classList.toggle('open')">${svg('playbook')}</button><div class="ops-context"><span id="ops-kicker">RUN THE DAY</span><strong id="ops-title">Today</strong></div><div class="ops-system"><span id="ops-sync-dot"></span><span id="ops-sync-label">Checking HighLevel</span><button onclick="opsRefresh()">Refresh</button></div></header><main id="ops-main" class="ops-main"></main></section>`;dash.appendChild(shell);document.addEventListener('click',e=>{if(innerWidth<=860&&!e.target.closest('.ops-rail')&&!e.target.closest('.ops-menu'))$('#ops-rail')?.classList.remove('open')});S.installed=true;loadAll();go('today')}
const head=(k,t,c,a='')=>`<div class="ops-page-head"><div><span class="ops-eyebrow">${esc(k)}</span><h1>${esc(t)}</h1><p>${esc(c)}</p></div><div class="ops-page-actions">${a}</div></div>`;
const action=(l,h,s='')=>`<a class="ops-button ${s}" href="${h}">${l}</a>`;
const badge=(t,s='')=>`<span class="ops-status ${s}">${esc(t||'—')}</span>`;
const empty=(t,c,a='')=>`<div class="ops-empty"><span>EGC</span><h3>${esc(t)}</h3><p>${esc(c)}</p>${a}</div>`;
const jobs=()=>typeof jobsCache==='undefined'?[]:jobsCache;
const jobStage=j=>typeof getPipelineStatus==='function'?getPipelineStatus(j):(j.pipelineStatus||j.status||'scheduled');
const isToday=v=>Boolean(v)&&String(v).slice(0,10)===day();
const todayJobs=()=>jobs().filter(j=>isToday(j.date||j.startTime));
const openJobs=()=>jobs().filter(j=>!['completed','paid','cancelled'].includes(jobStage(j)));

async function loadAll(){await Promise.all([loadIntegrations(),loadGhl(),loadWalks()]);render()}
async function loadIntegrations(){try{const r=await fetch('/api/integration-status',{cache:'no-store'}),j=await r.json();if(r.ok)S.integrations=j.status||{}}catch{}}
async function loadGhl(){S.ghl.loading=true;S.ghl.error='';sync();try{const r=await fetch('/api/highlevel?view=command',{cache:'no-store'}),j=await r.json();if(!r.ok)throw new Error(j.code==='HIGHLEVEL_NOT_CONFIGURED'?'not-configured':j.error||'unavailable');S.ghl={loading:false,error:'',pipelines:j.pipelines||[],opportunities:j.opportunities||[]}}catch(e){S.ghl.loading=false;S.ghl.error=e.message||'unavailable'}sync();render()}
async function loadWalks(){S.walks.loading=true;S.walks.error='';try{const r=await fetch('/api/highlevel?view=walkthroughs&date='+day(),{cache:'no-store'}),j=await r.json();if(!r.ok)throw new Error(j.code==='HIGHLEVEL_NOT_CONFIGURED'?'not-configured':j.error||'unavailable');S.walks={loading:false,error:'',events:(j.events||[]).filter(e=>isToday(e.startTime))}}catch(e){S.walks.loading=false;S.walks.error=e.message||'unavailable'}render()}
function sync(){const d=$('#ops-sync-dot'),l=$('#ops-sync-label');if(!d||!l)return;d.className=S.ghl.loading?'loading':S.ghl.error?'off':'on';l.textContent=S.ghl.loading?'Checking HighLevel':S.ghl.error==='not-configured'?'HighLevel key needed':S.ghl.error?'HighLevel unavailable':'HighLevel connected'}
function stageName(o){for(const p of S.ghl.pipelines){const s=(p.stages||[]).find(x=>x.id===o.pipelineStageId);if(s)return s.name||'Open'}return o.status||'Open'}
function go(name){S.active=name;all('[data-ops-tab]').forEach(b=>b.classList.toggle('active',b.dataset.opsTab===name));$('#ops-rail')?.classList.remove('open');const n=nav.find(x=>x[1]===name)||nav[0];if($('#ops-kicker'))$('#ops-kicker').textContent=n[0];if($('#ops-title'))$('#ops-title').textContent=n[2];render()}
window.opsGo=go;window.opsRefresh=loadAll;
function render(){const host=$('#ops-main');if(host&&views[S.active])host.innerHTML=views[S.active]()}
function notConfigured(what){return empty('HighLevel connection is the remaining blocker',`The ${what} is built and ready. Add a HighLevel private-integration token and location ID in Cloudflare to activate live data.`,`<button class="ops-button primary" onclick="opsGo('settings')">Show setup fields</button>`)}

function metrics(){const opp=S.ghl.opportunities,total=opp.reduce((a,o)=>a+Number(o.monetaryValue||0),0),ready=todayJobs().filter(j=>(j.notes||j.scope||j.walkthroughNotes)&&Number(j.priceQuoted||j.total||0)).length;return`<div class="ops-metrics"><article><span>Open HighLevel pipeline</span><strong>${S.ghl.error?'—':opp.length}</strong><small>${S.ghl.error?'Connect once; keep CRM in HighLevel':money(total)+' open value'}</small></article><article><span>Walkthroughs today</span><strong>${S.walks.error?'—':S.walks.events.length}</strong><small>Sell the plan, not the cleanout</small></article><article><span>Jobs today</span><strong>${todayJobs().length}</strong><small>${ready} handoff-ready · ${todayJobs().length-ready} need attention</small></article><article class="accent"><span>Target average ticket</span><strong>$1,400</strong><small>Win on contribution, not close rate alone</small></article></div>`}
function flywheel(){const rows=[['01','Lead response','HIGHLEVEL','Respond fast; sell the free walkthrough.'],['02','Walkthrough','FIELD','Diagnose pain, design outcome, lock scope and price.'],['03','Crew handoff','EGC HUB','Carry every promise, hazard, keep item and photo forward.'],['04','Reveal','FIELD','Final walkthrough, surprise gift, collect, ask for review.'],['05','Proof loop','GROWTH','Publish the transformation and feed the winning hook.']];return`<section class="ops-card ops-fly"><div class="ops-card-head"><div><span class="ops-eyebrow">THE OPERATING LOOP</span><h2>One promise, carried all the way through</h2></div>${badge('Walkthrough-first','info')}</div><div class="ops-fly-row">${rows.map(r=>`<article><b>${r[0]}</b><span>${r[2]}</span><h3>${r[1]}</h3><p>${r[3]}</p></article>`).join('')}</div></section>`}
function agenda(){const rows=[...S.walks.events.map(x=>({...x,kind:'Walkthrough',at:x.startTime})),...todayJobs().map(x=>({...x,kind:'Job',at:x.date+'T'+(x.time||'08:00')}))].sort((a,b)=>String(a.at).localeCompare(String(b.at)));if(!rows.length)return empty('No field events found today',S.ghl.error==='not-configured'?'Add the HighLevel API key and location ID to load walkthroughs. Jobs saved in the hub appear automatically.':'HighLevel walkthroughs and delivery jobs appear here.',action('Open HighLevel','https://app.gohighlevel.com/','ghost'));return`<div class="ops-agenda">${rows.map(r=>`<article><time>${timeLabel(r.at)||'TBD'}</time><div><span>${r.kind}</span><strong>${esc(r.name||r.customer||r.title||'Customer')}</strong><p>${esc(r.address||r.addr||'Address not recorded')}</p></div><a href="${r.kind==='Walkthrough'?'/crew/gameplan.html':'/crew/prejob.html'}">${r.kind==='Walkthrough'?'Start Game Plan':'Open crew brief'} →</a></article>`).join('')}</div>`}
function attention(){const x=[];if(S.ghl.error==='not-configured')x.push(['HighLevel is not connected','Add the API key and location ID in Cloudflare.','settings']);openJobs().slice(0,5).forEach(j=>{if(!j.notes&&!j.scope&&!j.walkthroughNotes)x.push([`${j.customer||'Job'} has no crew brief`,'Carry the walkthrough promise into delivery.','delivery']);else if(!Number(j.priceQuoted||j.total||0))x.push([`${j.customer||'Job'} has no locked total`,'Confirm the flat rate before the crew rolls.','delivery'])});if(!x.length)x.push(['The handoff queue is clean','Review today’s appointments, then protect content capture.','walkthroughs']);return`<div class="ops-attention">${x.map(i=>`<button onclick="opsGo('${i[2]}')"><i></i><div><strong>${esc(i[0])}</strong><small>${esc(i[1])}</small></div><b>→</b></button>`).join('')}</div>`}

const views={
today(){return head(dateLabel(new Date()).toUpperCase(),'Run today without dropping the promise','HighLevel owns the relationship. This workspace owns the walkthrough, handoff, delivery, and proof.',action('Start a walkthrough','/crew/gameplan.html','primary')+action('Open HighLevel','https://app.gohighlevel.com/','dark'))+metrics()+flywheel()+`<div class="ops-columns"><section class="ops-card span-7"><div class="ops-card-head"><div><span class="ops-eyebrow">TODAY'S RUN</span><h2>Field agenda</h2></div>${badge(S.walks.loading?'Syncing':'HighLevel calendar','info')}</div>${agenda()}</section><section class="ops-card span-5"><div class="ops-card-head"><div><span class="ops-eyebrow">PROTECT THE EXPERIENCE</span><h2>Needs attention</h2></div></div>${attention()}</section></div>`},
pipeline(){const rows=S.ghl.opportunities;let body;if(S.ghl.loading)body=empty('Loading the HighLevel pipeline','This view is read-only by design. Follow-up and pipeline movement stay in HighLevel.');else if(S.ghl.error)body=notConfigured('pipeline');else if(!rows.length)body=empty('No open opportunities','New opportunities will appear here from HighLevel. Keep lead creation and nurture in the CRM.');else{const g={};rows.forEach(o=>(g[stageName(o)]||=[]).push(o));body=`<div class="ops-pipeline">${Object.entries(g).map(([st,os])=>`<section><header><strong>${esc(st)}</strong><span>${os.length}</span></header>${os.map(o=>`<article><div><strong>${esc(o.contact?.name||o.name||'Unnamed opportunity')}</strong>${badge(o.status||'open')}</div><p>${esc(o.contact?.phone||o.contact?.email||o.source||'No contact detail returned')}</p><footer><b>${money(o.monetaryValue)}</b><span>${esc(o.source||'HighLevel')}</span></footer></article>`).join('')}</section>`).join('')}</div>`}return head('CRM MIRROR','HighLevel pipeline','A read-only field view. Manage stages, conversations, forms, nurture, and automations in HighLevel.',action('Work in HighLevel','https://app.gohighlevel.com/','primary'))+`<div class="ops-boundary"><strong>System boundary</strong><span>HighLevel = contacts, conversations, appointments, pipeline, automations.</span><span>EGC Hub = walkthrough, scope, crew handoff, proof, unit economics.</span></div>${body}`},
walkthroughs(){let q=S.walks.loading?empty('Loading today’s walkthroughs','Reading the HighLevel walkthrough calendar.'):S.walks.error?notConfigured('walkthrough calendar'):S.walks.events.length?`<div class="ops-walk-list">${S.walks.events.map(e=>`<article><div class="ops-date-block"><strong>${timeLabel(e.startTime)}</strong><span>${dateLabel(e.startTime)}</span></div><div>${badge(e.status,'info')}<h3>${esc(e.name||e.title||'Walkthrough')}</h3><p>${esc(e.address||e.phone||e.email||'Open HighLevel for details')}</p></div><a href="/crew/gameplan.html">Start Game Plan →</a></article>`).join('')}</div>`:empty('No walkthroughs on today’s calendar','HighLevel appointments will appear here. Manual Game Plan starts always remain available.',action('Start manual walkthrough','/crew/gameplan.html','primary'));return head('SELL THE DIAGNOSIS','Walkthrough command','The ad and phone call sell the free walkthrough. The walkthrough diagnoses the pain, builds the outcome, and earns the premium job.',action('Start Game Plan','/crew/gameplan.html','primary'))+`<div class="ops-columns"><section class="ops-card span-7"><div class="ops-card-head"><div><span class="ops-eyebrow">TODAY</span><h2>HighLevel appointments</h2></div></div>${q}</section><section class="ops-card span-5 ops-script"><span class="ops-eyebrow">THE STANDARD</span><h2>Do not quote before discovery</h2><ol><li><b>Why now?</b><span>What changed, and what is the garage costing them?</span></li><li><b>What does “done” mean?</b><span>Cars parked, storage zones, move deadline, or clean slate?</span></li><li><b>Lock the rules.</b><span>Keep/remove method, valuables, exclusions, hazards, disposal.</span></li><li><b>Design the result.</b><span>Show proof, select the value ladder, scope crew and truck.</span></li><li><b>Close the driveway.</b><span>Repeat the promise, lock flat rate, collect 20%, save to HighLevel.</span></li></ol></section></div><section class="ops-card ops-promise"><div><span class="ops-eyebrow">THE HANDOFF TEST</span><h2>Could tomorrow’s crew explain the customer’s “why” before knocking?</h2><p>If not, the walkthrough is not complete. The customer should never retell the story.</p></div><a href="/crew/gameplan.html">Open the guided walkthrough →</a></section>`},
delivery(){const rows=openJobs();return head('FIELD EXECUTION','Deliver the premium promise','Big-company professionalism with small-company personalization—from arrival text to surprise ending.',action('Pre-job playbook','/crew/prejob.html','dark')+action('Post-job playbook','/crew/postjob.html','primary'))+`<div class="ops-service-strip">${[['Before arrival','Named crew, photo, vehicle, ETA'],['At the door','Re-walk scope and protect keep items'],['During the job','Sort rules, property protection, matching-angle content'],['At the reveal','Silence first, fix anything, gift, payment, review']].map((x,i)=>`<article><span>0${i+1}</span><strong>${x[0]}</strong><p>${x[1]}</p></article>`).join('')}</div><section class="ops-card"><div class="ops-card-head"><div><span class="ops-eyebrow">OPEN JOBS</span><h2>Crew handoff queue</h2></div>${badge(rows.length+' active','info')}</div>${rows.length?`<div class="ops-job-list">${rows.map(j=>{const ready=(j.notes||j.scope||j.walkthroughNotes)&&Number(j.priceQuoted||j.total||0);return`<article><div><span class="ops-readiness ${ready?'ready':'warn'}">${ready?'HANDOFF READY':'NEEDS BRIEF'}</span><h3>${esc(j.customer||'Unnamed job')}</h3><p>${dateLabel(j.date)} · ${esc(j.address||'No address')} · ${esc(j.assignedTo||'Unassigned')}</p></div><div class="ops-job-price"><strong>${money(j.priceQuoted||j.total)}</strong><span>${esc(jobStage(j).replace('_',' '))}</span></div><div class="ops-job-actions"><a href="/crew/prejob.html">Pre-job</a><a href="/crew/postjob.html">Closeout</a></div></article>`}).join('')}</div>`:empty('No open delivery jobs','Completed walkthroughs save to HighLevel. Schedule the delivery record only after the customer commits.')}</section>`},
scorecard(){const d=scoreData(),c=scoreCalc(d);return head('UNIT ECONOMICS','Contribution scorecard','The business wins on contribution dollars per lead and per crew-hour—not vanity CPL, revenue, or close rate.',`<button class="ops-button primary" onclick="opsSaveScorecard()">Save scorecard</button>`)+`<div class="ops-metrics score">${[['Cost per lead',c.cpl,'Quality over cheap leads'],['Walkthrough set rate',c.setRate,'Target: 50%'],['Qualified close rate',c.closeRate,'~70% can beat 95% at better price'],['Average ticket',c.aov,'Target: $1,400'],['Contribution / job',c.perJob,'After direct costs and ads'],['Contribution / lead',c.perLead,'North-star acquisition metric']].map((x,i)=>`<article class="${i===5?'accent':''}"><span>${x[0]}</span><strong>${x[1]}</strong><small>${x[2]}</small></article>`).join('')}</div><div class="ops-columns"><section class="ops-card span-7"><div class="ops-card-head"><div><span class="ops-eyebrow">THIS PERIOD</span><h2>Enter the numbers once</h2></div>${badge('Saved on this device','info')}</div><form class="ops-score-form" id="ops-score-form">${scoreFields(d)}</form></section><section class="ops-card span-5"><span class="ops-eyebrow">DECISION RULES</span><h2>What the numbers should change</h2><div class="ops-rules"><div><b>If set rate is low</b><span>Fix speed-to-lead, walkthrough positioning, reminders, and HighLevel follow-up.</span></div><div><b>If close rate is ~95%</b><span>Test price and value ladder. Near-perfect close can mean underpricing.</span></div><div><b>If AOV is low</b><span>Sell cleanout → deep clean → organization → shelving → full transformation.</span></div><div><b>If contribution / lead is weak</b><span>Inspect hook quality, labor, disposal, route density, and offer—not CPL alone.</span></div></div></section></div>`},
proof(){const cells=[['Before','Same doorway, vertical wide, worst zone, 5+ photos.'],['Process','Sorting, donation care, crew personality, approved moments.'],['After','Match every before angle before the reveal.'],['Reaction','Let the homeowner react first; capture with permission.'],['Receipt','Donation receipt photographed and delivered.'],['Publish','3 useful pieces/day across short-form channels.']];return head('THE PROOF LOOP','Turn every job into the next job','The website, reviews, and ads should prove the transformation instead of merely explaining it.',action('Open post-job capture','/crew/postjob.html','primary'))+`<section class="ops-proof-grid">${cells.map((x,i)=>`<article><span>0${i+1}</span><h2>${x[0]}</h2><p>${x[1]}</p></article>`).join('')}</section><div class="ops-columns"><section class="ops-card span-7"><span class="ops-eyebrow">DAILY CONTENT MIX</span><h2>Three pieces, three jobs</h2><div class="ops-content-bars"><div><span>Transformation / portfolio</span><i></i><b>1/day</b></div><div><span>Personality / entertaining</span><i></i><b>1/day</b></div><div><span>Engagement / education</span><i></i><b>1/day</b></div></div></section><section class="ops-card span-5"><span class="ops-eyebrow">AD TEST DISCIPLINE</span><h2>One ad, one hook</h2><p class="ops-body">Keep audience, offer, form, and budget constant. Change the hook. Run 3–5 day waves; judge lead quality, jobs, and contribution.</p><div class="ops-hook-list"><span>Can’t park in your garage?</span><span>A 3-hour garage reset</span><span>Send photos; we’ll quote it</span><span>Remove junk + organize what stays</span><span>Fort Collins cleanouts made easy</span></div></section></div>`},
playbook(){const rows=[['Positioning','Sell the free walkthrough in the ad and on the phone. The walkthrough sells the job.'],['Pricing','$1,400 target AOV; flat by value and scope, not hours. Minimum-job guardrail: roughly $499–$699.'],['Value ladder','Cleanout only → deep clean → organization → shelving → full transformation.'],['Experience','Big-company professionalism + small-company personalization. Named arrival, continuity, surprise ending.'],['Crew standard','$20/hr crew; $23/hr lead baseline. Lead owns communication, scope, payment, and closeout.'],['Profit','Owned truck removes roughly $150–$200 rental cost/job. Track contribution per crew-hour.'],['Follow-up','Day 0, 1, 3, 7, 14, 30, then 60/90. HighLevel owns the automations.'],['Growth','Fast response, qualification, neighborhood saturation, referrals, reactivation, selective B2B.'],['Retention','Six-month check-in and Garage Guard after a premium first experience.']];return head('BUSINESS MODEL','The EGC playbook','Operating decisions this hub enforces—not generic field-service defaults.')+`<section class="ops-thesis"><span>THE FLYWHEEL</span><h2>Better hook → free walkthrough → premium plan → remarkable delivery → proof → easier sale</h2><p>If a feature does not improve set rate, contribution, continuity, experience, or proof, it is noise.</p></section><div class="ops-decision-grid">${rows.map((x,i)=>`<article><span>${String(i+1).padStart(2,'0')}</span><h3>${x[0]}</h3><p>${x[1]}</p></article>`).join('')}</div>`},
settings(){const items=[['HighLevel','CRM source of truth','highlevel','HIGHLEVEL_API_KEY + HIGHLEVEL_LOCATION_ID'],['Firebase','EGC job and field records','firebase','Existing web configuration'],['Quo','Business-line texts','quo','QUO_API_KEY'],['Google Drive','Agreements and proof','google','Google OAuth credentials'],['OpenAI','After visualization and copilot','openai','OPENAI_API_KEY'],['Stripe','Deposits and Garage Guard','stripe','Stripe secrets'],['Automations','Event relays and Meta signals','automations','Webhook destinations']];return head('SYSTEM','Integrations and ownership','No duplicate CRM. Credentials remain server-side in Cloudflare; this page exposes readiness only.',action('Open HighLevel','https://app.gohighlevel.com/','primary'))+`<div class="ops-columns"><section class="ops-card span-7"><span class="ops-eyebrow">CONNECTIONS</span><h2>Live system readiness</h2><div class="ops-integrations">${items.map(x=>`<article><div><strong>${x[0]}</strong><p>${x[1]}</p><code>${x[3]}</code></div>${badge(S.integrations[x[2]]?'Connected':'Needs setup',S.integrations[x[2]]?'good':'warn')}</article>`).join('')}</div></section><section class="ops-card span-5"><span class="ops-eyebrow">SOURCE OF TRUTH</span><h2>What lives where</h2><div class="ops-system-map"><div><b>HighLevel</b><span>Leads · contacts · conversations · calendars · pipeline · nurture</span></div><i>→</i><div><b>EGC Hub</b><span>Walkthrough plan · signed scope · job brief · checklists · proof</span></div><i>→</i><div><b>Accounting / payments</b><span>Invoices · deposits · payroll · books</span></div></div><p class="ops-note">Jobber is no longer presented as the operating center. Its legacy bridge can remain dormant until old data is retired.</p></section></div>`}
};

function scoreData(){const d={spend:0,leads:0,walkthroughs:0,quotes:0,jobs:0,revenue:0,labor:0,disposal:0,fuel:0,other:0,crewHours:0};try{return{...d,...JSON.parse(localStorage.getItem('egc_scorecard')||'{}')}}catch{return d}}
function scoreCalc(d){const n=k=>Number(d[k]||0),j=n('jobs'),l=n('leads'),con=n('revenue')-n('labor')-n('disposal')-n('fuel')-n('other')-n('spend');return{cpl:l?money(n('spend')/l):'—',setRate:l?Math.round(n('walkthroughs')/l*100)+'%':'—',closeRate:n('quotes')?Math.round(j/n('quotes')*100)+'%':'—',aov:j?money(n('revenue')/j):'—',perJob:j?money(con/j):'—',perLead:l?money(con/l):'—'}}
function scoreFields(d){const fs=[['spend','Ad spend'],['leads','Qualified leads'],['walkthroughs','Walkthroughs set'],['quotes','Quotes delivered'],['jobs','Jobs won'],['revenue','Collected revenue'],['labor','Direct labor'],['disposal','Dump / disposal'],['fuel','Fuel'],['other','Other direct cost'],['crewHours','Crew hours']];return fs.map(([k,l])=>`<label><span>${l}</span><div>${['spend','revenue','labor','disposal','fuel','other'].includes(k)?'<b>$</b>':''}<input type="number" min="0" step="0.01" name="${k}" value="${esc(d[k])}" inputmode="decimal"></div></label>`).join('')}
window.opsSaveScorecard=function(){const f=$('#ops-score-form');if(!f)return;const out={};new FormData(f).forEach((v,k)=>out[k]=Number(v||0));localStorage.setItem('egc_scorecard',JSON.stringify(out));render();if(typeof showToast==='function')showToast('Scorecard saved')};
const legacyBoot=window.bootDashboard;window.bootDashboard=function(){if(legacyBoot)legacyBoot();install();render()};install();
})();
