/* EGC Operating System — HighLevel is CRM; this hub runs the service. */
(function(){
'use strict';
const S={active:'today',installed:false,integrations:{},ghl:{loading:true,error:'',pipelines:[],opportunities:[]},walks:{loading:true,error:'',events:[]},weekAnchor:'',booking:null,contactResults:[]};
const $=s=>document.querySelector(s),all=s=>Array.from(document.querySelectorAll(s));
const esc=v=>String(v==null?'':v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=v=>Number(v||0).toLocaleString('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0});
const day=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'America/Denver',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const dateLabel=v=>{try{return new Date(v).toLocaleDateString('en-US',{weekday:'short',month:'short',day:'numeric',timeZone:'America/Denver'})}catch{return v||'TBD'}};
const timeLabel=v=>{try{return new Date(v).toLocaleTimeString('en-US',{hour:'numeric',minute:'2-digit',timeZone:'America/Denver'})}catch{return''}};
const icons={today:'M4 5h16v15H4zM8 3v4m8-4v4M4 10h16',schedule:'M4 5h16v15H4zM8 3v4m8-4v4M4 10h16M8 14h3m2 0h3',pipeline:'M4 6h4v12H4zm6 3h4v9h-4zm6-5h4v14h-4z',walkthroughs:'M4 4h16v16H4zM8 2v4m8-4v4M7 11h4m-4 4h7',delivery:'M3 6h12v11H3zm12 4h4l2 3v4h-6M7 19a2 2 0 1 0 0-4 2 2 0 0 0 0 4Zm11 0a2 2 0 1 0 0-4 2 2 0 0 0 0 4Z',scorecard:'M4 19V9m5 10V5m5 14v-7m5 7V3',proof:'M4 5h4l2-2h4l2 2h4v15H4zM12 9a4 4 0 1 0 0 8 4 4 0 0 0 0-8Z',playbook:'M5 4h11a3 3 0 0 1 3 3v13H8a3 3 0 0 1-3-3zm0 0v13a3 3 0 0 0 3 3',settings:'M12 15.5a3.5 3.5 0 1 0 0-7 3.5 3.5 0 0 0 0 7Zm0-12v2m0 13v2m8.5-8.5h-2m-13 0h-2m14.5-6-1.5 1.5m-9 9L6 18m12 0-1.5-1.5m-9-9L6 6',external:'M14 4h6v6m0-6-9 9M10 6H4v14h14v-6'};
const svg=n=>`<svg viewBox="0 0 24 24" aria-hidden="true"><path d="${icons[n]||icons.today}"/></svg>`;
const nav=[['RUN THE DAY','today','Today'],['RUN THE DAY','schedule','Schedule'],['RUN THE DAY','walkthroughs','Walkthroughs'],['RUN THE DAY','delivery','Job delivery'],['CRM','pipeline','HighLevel pipeline'],['GROW THE ENGINE','scorecard','Scorecard'],['GROW THE ENGINE','proof','Proof library'],['GROW THE ENGINE','playbook','EGC playbook'],['SYSTEM','settings','Integrations']];

function install(){const dash=$('#dashboard');if(!dash||dash.classList.contains('ops-installed'))return;dash.classList.add('ops-installed');let group='';const shell=document.createElement('div');shell.className='ops-shell';shell.innerHTML=`<aside class="ops-rail" id="ops-rail"><div class="ops-brand"><span class="ops-brand-mark">EGC</span><span><strong>Field Command</strong><small>RUN THE PROMISE</small></span></div><nav class="ops-nav" aria-label="Employee hub">${nav.map(n=>{const h=n[0]!==group?`<div class="ops-nav-label">${group=n[0]}</div>`:'';return h+`<button data-ops-tab="${n[1]}" onclick="opsGo('${n[1]}')">${svg(n[1])}<span>${n[2]}</span></button>`}).join('')}</nav><div class="ops-rail-foot"><a href="https://app.gohighlevel.com/" target="_blank" rel="noopener">${svg('external')}<span>Open HighLevel<small>CRM · conversations · automation</small></span></a><a href="/crew/">${svg('delivery')}<span>Open crew tools<small>Field execution</small></span></a></div></aside><section class="ops-workspace"><header class="ops-topbar"><button class="ops-menu" type="button" aria-label="Open menu" onclick="document.getElementById('ops-rail').classList.toggle('open')">${svg('playbook')}</button><div class="ops-context"><span id="ops-kicker">RUN THE DAY</span><strong id="ops-title">Today</strong></div><div class="ops-system"><span id="ops-sync-dot"></span><span id="ops-sync-label">Checking HighLevel</span><button onclick="opsRefresh()">Refresh</button></div></header><main id="ops-main" class="ops-main"></main></section>`;dash.appendChild(shell);document.addEventListener('click',e=>{if(innerWidth<=860&&!e.target.closest('.ops-rail')&&!e.target.closest('.ops-menu'))$('#ops-rail')?.classList.remove('open')});S.installed=true;loadAll();go('today')}
const head=(k,t,c,a='')=>`<div class="ops-page-head"><div><span class="ops-eyebrow">${esc(k)}</span><h1>${esc(t)}</h1><p>${esc(c)}</p></div><div class="ops-page-actions">${a}</div></div>`;
const action=(l,h,s='')=>`<a class="ops-button ${s}" href="${h}">${l}</a>`;
const badge=(t,s='')=>`<span class="ops-status ${s}">${esc(t||'—')}</span>`;
const empty=(t,c,a='')=>`<div class="ops-empty"><span>EGC</span><h3>${esc(t)}</h3><p>${esc(c)}</p>${a}</div>`;
const jobs=()=>typeof jobsCache==='undefined'?[]:jobsCache;
const jobStage=j=>typeof getPipelineStatus==='function'?getPipelineStatus(j):(j.pipelineStatus||j.status||'scheduled');
const isToday=v=>Boolean(v)&&String(v).slice(0,10)===day();
const todayJobs=()=>jobs().filter(j=>isToday(j.date||j.startTime)&&j.type!=='blocked');
const todayWalkthroughs=()=>todayJobs().filter(j=>j.type==='walkthrough');
const todayDelivery=()=>todayJobs().filter(j=>j.type!=='walkthrough');
const openJobs=()=>jobs().filter(j=>j.type!=='walkthrough'&&j.type!=='blocked'&&!['completed','paid','cancelled'].includes(jobStage(j)));

async function loadAll(){await Promise.all([loadIntegrations(),loadGhl(),loadWalks()]);render()}
async function loadIntegrations(){try{const r=await fetch('/api/integration-status',{cache:'no-store'}),j=await r.json();if(r.ok)S.integrations=j.status||{}}catch{}}
async function loadGhl(){S.ghl.loading=true;S.ghl.error='';sync();try{const r=await fetch('/api/highlevel?view=command',{cache:'no-store'}),j=await r.json();if(!r.ok)throw new Error(j.code==='HIGHLEVEL_NOT_CONFIGURED'?'not-configured':j.error||'unavailable');S.ghl={loading:false,error:'',pipelines:j.pipelines||[],opportunities:j.opportunities||[]}}catch(e){S.ghl.loading=false;S.ghl.error=e.message||'unavailable'}sync();render()}
async function loadWalks(){S.walks.loading=true;S.walks.error='';try{const r=await fetch('/api/highlevel?view=walkthroughs&date='+day(),{cache:'no-store'}),j=await r.json();if(!r.ok)throw new Error(j.code==='HIGHLEVEL_NOT_CONFIGURED'?'not-configured':j.error||'unavailable');S.walks={loading:false,error:'',events:(j.events||[]).filter(e=>isToday(e.startTime))}}catch(e){S.walks.loading=false;S.walks.error=e.message||'unavailable'}render()}
function sync(){const d=$('#ops-sync-dot'),l=$('#ops-sync-label');if(!d||!l)return;d.className=S.ghl.loading?'loading':S.ghl.error?'off':'on';l.textContent=S.ghl.loading?'Checking HighLevel':S.ghl.error==='not-configured'?'HighLevel key needed':S.ghl.error?'HighLevel unavailable':'HighLevel connected'}
function stageName(o){for(const p of S.ghl.pipelines){const s=(p.stages||[]).find(x=>x.id===o.pipelineStageId);if(s)return s.name||'Open'}return o.status||'Open'}
function go(name){S.active=name;all('[data-ops-tab]').forEach(b=>b.classList.toggle('active',b.dataset.opsTab===name));$('#ops-rail')?.classList.remove('open');const n=nav.find(x=>x[1]===name)||nav[0];if($('#ops-kicker'))$('#ops-kicker').textContent=n[0];if($('#ops-title'))$('#ops-title').textContent=n[2];render()}
window.opsGo=go;window.opsRefresh=loadAll;
function render(){const host=$('#ops-main');if(host&&views[S.active])host.innerHTML=views[S.active]()}
function notConfigured(what){return empty('HighLevel connection is the remaining blocker',`The ${what} is built and ready. Add a HighLevel private-integration token and location ID in Cloudflare to activate live data.`,`<button class="ops-button primary" onclick="opsGo('settings')">Show setup fields</button>`)}

function metrics(){const opp=S.ghl.opportunities,total=opp.reduce((a,o)=>a+Number(o.monetaryValue||0),0),deliveries=todayDelivery(),ready=deliveries.filter(j=>(j.notes||j.scope||j.walkthroughNotes)&&Number(j.priceQuoted||j.total||0)).length;return`<div class="ops-metrics"><article><span>Open HighLevel pipeline</span><strong>${S.ghl.error?'—':opp.length}</strong><small>${S.ghl.error?'Connect CRM when the key is ready':money(total)+' open value'}</small></article><article><span>Walkthroughs today</span><strong>${todayWalkthroughs().length}</strong><small>Scheduled in the EGC Hub</small></article><article><span>Jobs today</span><strong>${deliveries.length}</strong><small>${ready} handoff-ready · ${deliveries.length-ready} need attention</small></article><article class="accent"><span>Target average ticket</span><strong>$1,400</strong><small>Win on contribution, not close rate alone</small></article></div>`}
function flywheel(){const rows=[['01','Lead response','HIGHLEVEL','Respond fast; sell the free walkthrough.'],['02','Walkthrough','FIELD','Diagnose pain, design outcome, lock scope and price.'],['03','Crew handoff','EGC HUB','Carry every promise, hazard, keep item and photo forward.'],['04','Reveal','FIELD','Final walkthrough, surprise gift, collect, ask for review.'],['05','Proof loop','GROWTH','Publish the transformation and feed the winning hook.']];return`<section class="ops-card ops-fly"><div class="ops-card-head"><div><span class="ops-eyebrow">THE OPERATING LOOP</span><h2>One promise, carried all the way through</h2></div>${badge('Walkthrough-first','info')}</div><div class="ops-fly-row">${rows.map(r=>`<article><b>${r[0]}</b><span>${r[2]}</span><h3>${r[1]}</h3><p>${r[3]}</p></article>`).join('')}</div></section>`}
function agenda(){const rows=todayJobs().map(x=>({...x,kind:x.type==='walkthrough'?'Walkthrough':'Job',at:x.date+'T'+(x.time||'08:00')})).sort((a,b)=>String(a.at).localeCompare(String(b.at)));if(!rows.length)return empty('Nothing scheduled today','Add a walkthrough, job, or blocked time in the Hub schedule.',`<button class="ops-button primary" onclick="opsOpenBooking()">Schedule work</button>`);return`<div class="ops-agenda">${rows.map(r=>`<article><time>${timeLabel(r.at)||'TBD'}</time><div><span>${r.kind}</span><strong>${esc(r.customer||r.title||'Customer')}</strong><p>${esc(r.address||'Address not recorded')}</p></div><a href="${r.kind==='Walkthrough'?'/crew/gameplan.html':'/crew/prejob.html'}">${r.kind==='Walkthrough'?'Start walkthrough':'Open crew brief'} →</a></article>`).join('')}</div>`}
function attention(){const x=[];if(S.ghl.error==='not-configured')x.push(['HighLevel is not connected','Add the API key and location ID in Cloudflare.','settings']);openJobs().slice(0,5).forEach(j=>{if(!j.notes&&!j.scope&&!j.walkthroughNotes)x.push([`${j.customer||'Job'} has no crew brief`,'Carry the walkthrough promise into delivery.','delivery']);else if(!Number(j.priceQuoted||j.total||0))x.push([`${j.customer||'Job'} has no locked total`,'Confirm the flat rate before the crew rolls.','delivery'])});if(!x.length)x.push(['The handoff queue is clean','Review today’s appointments, then protect content capture.','walkthroughs']);return`<div class="ops-attention">${x.map(i=>`<button onclick="opsGo('${i[2]}')"><i></i><div><strong>${esc(i[0])}</strong><small>${esc(i[1])}</small></div><b>→</b></button>`).join('')}</div>`}

const isoDate=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
function weekStart(value=S.weekAnchor){const d=value?new Date(value+'T12:00:00'):new Date(),shift=(d.getDay()+6)%7;d.setDate(d.getDate()-shift);d.setHours(12,0,0,0);return d}
function weekDays(){const start=weekStart();return Array.from({length:7},(_,i)=>{const d=new Date(start);d.setDate(start.getDate()+i);return isoDate(d)})}
function eventTime(j){return j.time||String(j.startTime||'').slice(11,16)||'TBD'}
function scheduleGrid(){return`<div class="ops-week">${weekDays().map(date=>{const rows=jobs().filter(j=>String(j.date||j.startTime||'').slice(0,10)===date&&!['cancelled'].includes(jobStage(j))).sort((a,b)=>eventTime(a).localeCompare(eventTime(b)));const d=new Date(date+'T12:00:00');return`<section class="${date===day()?'today':''}"><header><span>${d.toLocaleDateString('en-US',{weekday:'short'})}</span><strong>${d.getDate()}</strong><button type="button" onclick="opsOpenBooking('${date}')" aria-label="Schedule on ${date}">+</button></header><div>${rows.length?rows.map(j=>`<article class="${esc(j.type||'job')}"><time>${esc(eventTime(j))}</time><strong>${esc(j.customer||j.title||j.serviceType||'Blocked time')}</strong><small>${esc(j.address||j.assignedTo||'')}</small><footer><span>${esc(j.type==='walkthrough'?'Walkthrough':j.type==='blocked'?'Blocked':'Job')}</span><button class="ops-edit-event" type="button" onclick="opsEditBooking('${esc(j.id)}')">Edit</button>${j.type==='blocked'?'':badge(j.syncStatus==='synced'?'Synced':j.syncStatus==='error'?'Sync failed':'Pending',j.syncStatus==='synced'?'good':j.syncStatus==='error'?'warn':'info')}</footer></article>`).join(''):`<button class="ops-day-empty" type="button" onclick="opsOpenBooking('${date}')">Add time</button>`}</div></section>`}).join('')}</div>`}
function bookingModal(){if(!S.booking)return'';const b=S.booking,results=S.contactResults||[];return`<div class="ops-modal" role="dialog" aria-modal="true" aria-label="Schedule work"><button class="ops-modal-scrim" type="button" onclick="opsCloseBooking()" aria-label="Close"></button><form class="ops-booking" onsubmit="opsSaveBooking(event)"><header><div><span class="ops-eyebrow">EGC HUB SCHEDULE</span><h2>${b.id?'Edit scheduled time':'Add scheduled time'}</h2><p>Saved here first, then synchronized to HighLevel.</p></div><button type="button" onclick="opsCloseBooking()">×</button></header><div class="ops-form-grid"><label><span>Type</span><select name="type" onchange="opsBookField('type',this.value)"><option value="walkthrough" ${b.type==='walkthrough'?'selected':''}>Free walkthrough</option><option value="job" ${b.type==='job'?'selected':''}>Customer job</option><option value="blocked" ${b.type==='blocked'?'selected':''}>Blocked time</option></select></label><label><span>Customer / label</span><input name="customer" required value="${esc(b.customer)}" oninput="opsBookField('customer',this.value)" placeholder="Customer name"></label><label class="wide"><span>Find CRM contact</span><div class="ops-contact-find"><input type="search" placeholder="Name, phone, or email" oninput="opsLookupContacts(this.value)"><em>HighLevel</em></div>${results.length?`<div class="ops-contact-results">${results.map((c,i)=>`<button type="button" onclick="opsPickContact(${i})"><b>${esc(c.name)}</b><span>${esc(c.phone||c.email||c.address)}</span></button>`).join('')}</div>`:''}</label><label><span>Mobile</span><input name="phone" value="${esc(b.phone)}" placeholder="(970) 555-0123"></label><label><span>Email</span><input name="email" type="email" value="${esc(b.email)}" placeholder="name@email.com"></label><label class="wide"><span>Address</span><input name="address" value="${esc(b.address)}" placeholder="Service address"></label><label><span>Date</span><input name="date" type="date" required value="${esc(b.date)}"></label><label><span>Start</span><input name="time" type="time" required value="${esc(b.time)}"></label><label><span>End</span><input name="endTime" type="time" required value="${esc(b.endTime)}"></label><label><span>Crew / owner</span><input name="assignedTo" value="${esc(b.assignedTo)}" placeholder="Zac + Tyler"></label><label class="wide"><span>Internal notes</span><textarea name="notes" placeholder="Access, expectations, crew notes…">${esc(b.notes)}</textarea></label><label class="wide ops-notify"><input name="notify" type="checkbox" ${b.notify?'checked':''}><span>Let HighLevel send confirmation and reminder workflows</span></label></div><footer><span id="ops-booking-status">Hub is the schedule of record.</span><div><button type="button" class="ops-button" onclick="opsCloseBooking()">Cancel</button><button class="ops-button primary">${b.id?'Update + sync':'Save + sync'}</button></div></footer></form></div>`}
function openBooking(date=day()){S.booking={type:'walkthrough',customer:'',phone:'',email:'',address:'',date,time:'09:00',endTime:'10:00',assignedTo:'',notes:'',notify:true,highlevelContactId:''};S.contactResults=[];render()}
window.opsOpenBooking=openBooking;window.opsCloseBooking=()=>{S.booking=null;S.contactResults=[];render()};window.opsBookField=(k,v)=>{if(S.booking)S.booking[k]=v};
window.opsEditBooking=id=>{const j=jobs().find(x=>x.id===id);if(!j)return;S.booking={id:j.id,type:j.type||'job',customer:j.customer||'',phone:j.phone||'',email:j.email||'',address:j.address||'',date:j.date||day(),time:j.time||'09:00',endTime:j.endTime||'10:00',assignedTo:j.assignedTo||'',notes:j.notes||'',notify:j.notify!==false,highlevelContactId:j.highlevelContactId||'',highlevelAppointmentId:j.highlevelAppointmentId||'',createdAt:j.createdAt||''};S.contactResults=[];render()};
let contactTimer;window.opsLookupContacts=q=>{clearTimeout(contactTimer);contactTimer=setTimeout(async()=>{if(!S.booking||String(q).trim().length<2){S.contactResults=[];return}try{const r=await fetch('/api/highlevel?view=contacts&q='+encodeURIComponent(String(q).trim())),j=await r.json();S.contactResults=r.ok?j.contacts||[]:[];render()}catch{S.contactResults=[]}},350)};
window.opsPickContact=i=>{const c=S.contactResults[i];if(!c||!S.booking)return;Object.assign(S.booking,{customer:c.name||S.booking.customer,phone:c.phone||'',email:c.email||'',address:c.address||'',highlevelContactId:c.id||''});S.contactResults=[];render()};
window.opsWeekMove=n=>{const d=weekStart();d.setDate(d.getDate()+Number(n)*7);S.weekAnchor=isoDate(d);render()};window.opsWeekToday=()=>{S.weekAnchor='';render()};
window.opsSaveBooking=async e=>{
  e.preventDefault();if(!S.booking)return;
  const form=e.currentTarget,fd=new FormData(form),status=$('#ops-booking-status'),button=form.querySelector('button.ops-button.primary'),b={...S.booking};
  fd.forEach((v,k)=>b[k]=v);b.notify=fd.has('notify');if(button){button.disabled=true;button.textContent='Saving…'}
  const id=b.id||'hub-'+Date.now().toString(36)+Math.random().toString(36).slice(2,6),now=new Date().toISOString(),job={id,type:b.type,serviceType:b.type==='walkthrough'?'Free walkthrough':b.type==='blocked'?'Blocked time':'Garage service',date:b.date,time:b.time,endTime:b.endTime,customer:b.customer,phone:b.phone||'',email:b.email||'',address:b.address||'',assignedTo:b.assignedTo||'',notes:b.notes||'',notify:b.notify,status:'scheduled',pipelineStatus:'scheduled',scheduleSource:'egc_hub',syncStatus:b.type==='blocked'?'local':'pending',highlevelContactId:b.highlevelContactId||'',highlevelAppointmentId:b.highlevelAppointmentId||'',createdAt:b.createdAt||now,updatedAt:now};
  try{
    if(typeof db==='undefined')throw new Error('Hub database unavailable');
    await db.collection('jobs').doc(id).set(job);
    if(typeof jobsCache!=='undefined')jobsCache=[...jobsCache.filter(x=>x.id!==id),job];
  }catch(err){if(status)status.textContent='The Hub schedule could not save. Check the connection and try again.';if(button){button.disabled=false;button.textContent='Retry save'}return}
  if(b.type==='blocked'){S.booking=null;render();if(typeof showToast==='function')showToast('Time blocked');return}
  try{
    if(status)status.textContent='Saved in Hub. Syncing HighLevel…';
    const start=new Date(`${b.date}T${b.time}`).toISOString(),end=new Date(`${b.date}T${b.endTime}`).toISOString(),r=await fetch('/api/highlevel',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({tool:'schedule',event_type:b.type,appointment_id:b.highlevelAppointmentId||'',start_time:start,end_time:end,title:b.type==='walkthrough'?'EGC Free Walkthrough':'EGC Garage Service',address:b.address,notes:b.notes,notify:b.notify,client:{name:b.customer,phone:b.phone,email:b.email,address:b.address,highlevel_contact_id:b.highlevelContactId}})}),j=await r.json();
    if(!r.ok||!j.ok)throw new Error(j.code||j.error||'HighLevel sync failed');
    const update={syncStatus:'synced',highlevelContactId:j.contactId||'',highlevelAppointmentId:j.appointmentId||'',automationTagSynced:j.automation?.tagSynced!==false,updatedAt:new Date().toISOString()};
    await db.collection('jobs').doc(id).set(update,{merge:true});if(typeof jobsCache!=='undefined')jobsCache=jobsCache.map(x=>x.id===id?{...x,...update}:x);
    S.booking=null;render();if(typeof showToast==='function')showToast('Scheduled and synced to HighLevel');
  }catch(err){
    const update={syncStatus:'error',syncError:String(err.message||err).slice(0,160),updatedAt:new Date().toISOString()};
    await db.collection('jobs').doc(id).set(update,{merge:true}).catch(()=>{});if(typeof jobsCache!=='undefined')jobsCache=jobsCache.map(x=>x.id===id?{...x,...update}:x);
    S.booking=null;render();if(typeof showToast==='function')showToast('Saved in Hub; HighLevel sync is pending');
  }
};

const views={
today(){return head(dateLabel(new Date()).toUpperCase(),'Run today without dropping the promise','The Hub owns today’s schedule and field execution. HighLevel owns CRM, conversations, and automation.',action('Schedule work','#','primary').replace('href="#"','href="#" onclick="opsOpenBooking();return false"')+action('Start a walkthrough','/crew/gameplan.html','dark'))+metrics()+flywheel()+`<div class="ops-columns"><section class="ops-card span-7"><div class="ops-card-head"><div><span class="ops-eyebrow">TODAY'S RUN</span><h2>Field agenda</h2></div>${badge('Hub schedule','info')}</div>${agenda()}</section><section class="ops-card span-5"><div class="ops-card-head"><div><span class="ops-eyebrow">PROTECT THE EXPERIENCE</span><h2>Needs attention</h2></div></div>${attention()}</section></div>${bookingModal()}`},
schedule(){const dates=weekDays(),start=new Date(dates[0]+'T12:00:00'),end=new Date(dates[6]+'T12:00:00'),pending=jobs().filter(j=>['pending','error'].includes(j.syncStatus)).length;return head('HUB SCHEDULE','Schedule the work here','Book walkthroughs, customer jobs, crews, and blocked time in one field-ready week. Customer appointments then sync to HighLevel for communication.',`<button class="ops-button" onclick="opsWeekToday()">Today</button><button class="ops-button primary" onclick="opsOpenBooking()">+ Schedule</button>`)+`<div class="ops-schedule-bar"><div><button onclick="opsWeekMove(-1)" aria-label="Previous week">←</button><button onclick="opsWeekMove(1)" aria-label="Next week">→</button><strong>${start.toLocaleDateString('en-US',{month:'long',day:'numeric'})} – ${end.toLocaleDateString('en-US',{month:'long',day:'numeric',year:'numeric'})}</strong></div><div>${badge(jobs().filter(j=>dates.includes(String(j.date||'').slice(0,10))).length+' scheduled','info')}${pending?badge(pending+' sync attention','warn'):badge('HighLevel sync clear','good')}</div></div><div class="ops-boundary"><strong>System boundary</strong><span>EGC Hub = dates, times, crews, job state.</span><span>HighLevel = contacts, confirmations, reminders, follow-up.</span></div>${scheduleGrid()}${bookingModal()}`},
pipeline(){const rows=S.ghl.opportunities;let body;if(S.ghl.loading)body=empty('Loading the HighLevel pipeline','This view is read-only by design. Follow-up and pipeline movement stay in HighLevel.');else if(S.ghl.error)body=notConfigured('pipeline');else if(!rows.length)body=empty('No open opportunities','New opportunities will appear here from HighLevel. Keep lead creation and nurture in the CRM.');else{const g={};rows.forEach(o=>(g[stageName(o)]||=[]).push(o));body=`<div class="ops-pipeline">${Object.entries(g).map(([st,os])=>`<section><header><strong>${esc(st)}</strong><span>${os.length}</span></header>${os.map(o=>`<article><div><strong>${esc(o.contact?.name||o.name||'Unnamed opportunity')}</strong>${badge(o.status||'open')}</div><p>${esc(o.contact?.phone||o.contact?.email||o.source||'No contact detail returned')}</p><footer><b>${money(o.monetaryValue)}</b><span>${esc(o.source||'HighLevel')}</span></footer></article>`).join('')}</section>`).join('')}</div>`}return head('CRM MIRROR','HighLevel pipeline','A read-only field view. Manage stages, conversations, forms, nurture, and automations in HighLevel.',action('Work in HighLevel','https://app.gohighlevel.com/','primary'))+`<div class="ops-boundary"><strong>System boundary</strong><span>HighLevel = leads, contacts, conversations, pipeline, automations.</span><span>EGC Hub = scheduling, walkthroughs, job state, crew handoff, proof.</span></div>${body}`},
walkthroughs(){const rows=todayWalkthroughs(),q=rows.length?`<div class="ops-walk-list">${rows.map(e=>`<article><div class="ops-date-block"><strong>${esc(eventTime(e))}</strong><span>${dateLabel((e.date||day())+'T12:00:00')}</span></div><div>${badge(e.syncStatus==='synced'?'HighLevel synced':'Hub scheduled',e.syncStatus==='synced'?'good':'info')}<h3>${esc(e.customer||'Walkthrough')}</h3><p>${esc(e.address||e.phone||e.email||'No address recorded')}</p></div><a href="/crew/gameplan.html">Start walkthrough →</a></article>`).join('')}</div>`:empty('No walkthroughs today','Schedule the walkthrough in the Hub, or start one manually when a customer is already in front of you.',`<button class="ops-button" onclick="opsOpenBooking()">Schedule walkthrough</button>`+action('Start manual walkthrough','/crew/gameplan.html','primary'));return head('SELL THE DIAGNOSIS','Walkthrough command','The phone call sells the free walkthrough. This short, photo-led visit defines the result, locks scope, and schedules the premium job.',action('Start walkthrough','/crew/gameplan.html','primary'))+`<div class="ops-columns"><section class="ops-card span-7"><div class="ops-card-head"><div><span class="ops-eyebrow">TODAY</span><h2>Hub walkthroughs</h2></div></div>${q}</section><section class="ops-card span-5 ops-script"><span class="ops-eyebrow">ONLY WHAT MATTERS</span><h2>See it. Photograph it. Define it.</h2><ol><li><b>Hear the outcome.</b><span>Why now, and what should the garage do when EGC leaves?</span></li><li><b>Photograph the work.</b><span>Doorway, both sides, worst area, access, and special handling.</span></li><li><b>Lock the boundaries.</b><span>What stays, what leaves, valuables, hazards, and access.</span></li><li><b>Select the finish.</b><span>Cleanout, deep clean, organization, shelving, or totes.</span></li><li><b>Approve and schedule.</b><span>The rate builds in the background; the Hub saves the job and HighLevel follows up.</span></li></ol></section></div>${bookingModal()}`},
delivery(){const rows=openJobs();return head('FIELD EXECUTION','Deliver the premium promise','Big-company professionalism with small-company personalization—from arrival text to surprise ending.',action('Pre-job playbook','/crew/prejob.html','dark')+action('Post-job playbook','/crew/postjob.html','primary'))+`<div class="ops-service-strip">${[['Before arrival','Named crew, photo, vehicle, ETA'],['At the door','Re-walk scope and protect keep items'],['During the job','Sort rules, property protection, matching-angle content'],['At the reveal','Silence first, fix anything, gift, payment, review']].map((x,i)=>`<article><span>0${i+1}</span><strong>${x[0]}</strong><p>${x[1]}</p></article>`).join('')}</div><section class="ops-card"><div class="ops-card-head"><div><span class="ops-eyebrow">OPEN JOBS</span><h2>Crew handoff queue</h2></div>${badge(rows.length+' active','info')}</div>${rows.length?`<div class="ops-job-list">${rows.map(j=>{const ready=(j.notes||j.scope||j.walkthroughNotes)&&Number(j.priceQuoted||j.total||0);return`<article><div><span class="ops-readiness ${ready?'ready':'warn'}">${ready?'HANDOFF READY':'NEEDS BRIEF'}</span><h3>${esc(j.customer||'Unnamed job')}</h3><p>${dateLabel(j.date)} · ${esc(j.address||'No address')} · ${esc(j.assignedTo||'Unassigned')}</p></div><div class="ops-job-price"><strong>${money(j.priceQuoted||j.total)}</strong><span>${esc(jobStage(j).replace('_',' '))}</span></div><div class="ops-job-actions"><a href="/crew/prejob.html">Pre-job</a><a href="/crew/postjob.html">Closeout</a></div></article>`}).join('')}</div>`:empty('No open delivery jobs','A completed walkthrough creates the Hub job and schedules the crew only after the customer commits.')}</section>`},
scorecard(){const d=scoreData(),c=scoreCalc(d);return head('UNIT ECONOMICS','Contribution scorecard','The business wins on contribution dollars per lead and per crew-hour—not vanity CPL, revenue, or close rate.',`<button class="ops-button primary" onclick="opsSaveScorecard()">Save scorecard</button>`)+`<div class="ops-metrics score">${[['Cost per lead',c.cpl,'Quality over cheap leads'],['Walkthrough set rate',c.setRate,'Target: 50%'],['Qualified close rate',c.closeRate,'~70% can beat 95% at better price'],['Average ticket',c.aov,'Target: $1,400'],['Contribution / job',c.perJob,'After direct costs and ads'],['Contribution / lead',c.perLead,'North-star acquisition metric']].map((x,i)=>`<article class="${i===5?'accent':''}"><span>${x[0]}</span><strong>${x[1]}</strong><small>${x[2]}</small></article>`).join('')}</div><div class="ops-columns"><section class="ops-card span-7"><div class="ops-card-head"><div><span class="ops-eyebrow">THIS PERIOD</span><h2>Enter the numbers once</h2></div>${badge('Saved on this device','info')}</div><form class="ops-score-form" id="ops-score-form">${scoreFields(d)}</form></section><section class="ops-card span-5"><span class="ops-eyebrow">DECISION RULES</span><h2>What the numbers should change</h2><div class="ops-rules"><div><b>If set rate is low</b><span>Fix speed-to-lead, walkthrough positioning, reminders, and HighLevel follow-up.</span></div><div><b>If close rate is ~95%</b><span>Test price and value ladder. Near-perfect close can mean underpricing.</span></div><div><b>If AOV is low</b><span>Sell cleanout → deep clean → organization → shelving → full transformation.</span></div><div><b>If contribution / lead is weak</b><span>Inspect hook quality, labor, disposal, route density, and offer—not CPL alone.</span></div></div></section></div>`},
proof(){const cells=[['Before','Same doorway, vertical wide, worst zone, 5+ photos.'],['Process','Sorting, donation care, crew personality, approved moments.'],['After','Match every before angle before the reveal.'],['Reaction','Let the homeowner react first; capture with permission.'],['Receipt','Donation receipt photographed and delivered.'],['Publish','3 useful pieces/day across short-form channels.']];return head('THE PROOF LOOP','Turn every job into the next job','The website, reviews, and ads should prove the transformation instead of merely explaining it.',action('Open post-job capture','/crew/postjob.html','primary'))+`<section class="ops-proof-grid">${cells.map((x,i)=>`<article><span>0${i+1}</span><h2>${x[0]}</h2><p>${x[1]}</p></article>`).join('')}</section><div class="ops-columns"><section class="ops-card span-7"><span class="ops-eyebrow">DAILY CONTENT MIX</span><h2>Three pieces, three jobs</h2><div class="ops-content-bars"><div><span>Transformation / portfolio</span><i></i><b>1/day</b></div><div><span>Personality / entertaining</span><i></i><b>1/day</b></div><div><span>Engagement / education</span><i></i><b>1/day</b></div></div></section><section class="ops-card span-5"><span class="ops-eyebrow">AD TEST DISCIPLINE</span><h2>One ad, one hook</h2><p class="ops-body">Keep audience, offer, form, and budget constant. Change the hook. Run 3–5 day waves; judge lead quality, jobs, and contribution.</p><div class="ops-hook-list"><span>Can’t park in your garage?</span><span>A 3-hour garage reset</span><span>Send photos; we’ll quote it</span><span>Remove junk + organize what stays</span><span>Fort Collins cleanouts made easy</span></div></section></div>`},
playbook(){const rows=[['Positioning','Sell the free walkthrough in the ad and on the phone. The walkthrough sells the job.'],['Pricing','$1,400 target AOV; flat by value and scope, not hours. Minimum-job guardrail: roughly $499–$699.'],['Value ladder','Cleanout only → deep clean → organization → shelving → full transformation.'],['Experience','Big-company professionalism + small-company personalization. Named arrival, continuity, surprise ending.'],['Crew standard','$20/hr crew; $23/hr lead baseline. Lead owns communication, scope, payment, and closeout.'],['Profit','Owned truck removes roughly $150–$200 rental cost/job. Track contribution per crew-hour.'],['Follow-up','Day 0, 1, 3, 7, 14, 30, then 60/90. HighLevel owns the automations.'],['Growth','Fast response, qualification, neighborhood saturation, referrals, reactivation, selective B2B.'],['Retention','Six-month check-in and Garage Guard after a premium first experience.']];return head('BUSINESS MODEL','The EGC playbook','Operating decisions this hub enforces—not generic field-service defaults.')+`<section class="ops-thesis"><span>THE FLYWHEEL</span><h2>Better hook → free walkthrough → premium plan → remarkable delivery → proof → easier sale</h2><p>If a feature does not improve set rate, contribution, continuity, experience, or proof, it is noise.</p></section><div class="ops-decision-grid">${rows.map((x,i)=>`<article><span>${String(i+1).padStart(2,'0')}</span><h3>${x[0]}</h3><p>${x[1]}</p></article>`).join('')}</div>`},
settings(){const items=[['HighLevel','CRM, conversations, and customer automations','highlevel','HIGHLEVEL_API_KEY + HIGHLEVEL_LOCATION_ID'],['Firebase','Hub schedule and field records','firebase','Existing web configuration'],['Quo','Fallback transactional texts','quo','QUO_API_KEY'],['Google Drive','Agreements and proof','google','Google OAuth credentials'],['OpenAI','Optional visual and copilot tools','openai','OPENAI_API_KEY'],['Stripe','Deposits and Garage Guard','stripe','Stripe secrets'],['Automations','Operational event relays','automations','Webhook destinations']];return head('SYSTEM','Integrations and ownership','The EGC Hub runs the schedule and work. HighLevel supplies CRM and customer communication. Credentials remain server-side.',action('Open HighLevel','https://app.gohighlevel.com/','primary'))+`<div class="ops-columns"><section class="ops-card span-7"><span class="ops-eyebrow">CONNECTIONS</span><h2>Live system readiness</h2><div class="ops-integrations">${items.map(x=>`<article><div><strong>${x[0]}</strong><p>${x[1]}</p><code>${x[3]}</code></div>${badge(S.integrations[x[2]]?'Connected':'Needs setup',S.integrations[x[2]]?'good':'warn')}</article>`).join('')}</div></section><section class="ops-card span-5"><span class="ops-eyebrow">SOURCE OF TRUTH</span><h2>What lives where</h2><div class="ops-system-map"><div><b>EGC Hub</b><span>Schedule · crew assignment · walkthrough · signed scope · job state · proof</span></div><i>↔</i><div><b>HighLevel CRM</b><span>Leads · contacts · conversations · pipeline · confirmations · reminders · nurture</span></div><i>→</i><div><b>Accounting / payments</b><span>Invoices · deposits · payroll · books</span></div></div><p class="ops-note">Scheduling starts in the Hub. Customer appointments sync to HighLevel with workflow tags: egc-walkthrough-scheduled, egc-job-scheduled, egc-walkthrough-complete, egc-job-complete, and egc-review-ready.</p></section></div>`}
};

function scoreData(){const d={spend:0,leads:0,walkthroughs:0,quotes:0,jobs:0,revenue:0,labor:0,disposal:0,fuel:0,other:0,crewHours:0};try{return{...d,...JSON.parse(localStorage.getItem('egc_scorecard')||'{}')}}catch{return d}}
function scoreCalc(d){const n=k=>Number(d[k]||0),j=n('jobs'),l=n('leads'),con=n('revenue')-n('labor')-n('disposal')-n('fuel')-n('other')-n('spend');return{cpl:l?money(n('spend')/l):'—',setRate:l?Math.round(n('walkthroughs')/l*100)+'%':'—',closeRate:n('quotes')?Math.round(j/n('quotes')*100)+'%':'—',aov:j?money(n('revenue')/j):'—',perJob:j?money(con/j):'—',perLead:l?money(con/l):'—'}}
function scoreFields(d){const fs=[['spend','Ad spend'],['leads','Qualified leads'],['walkthroughs','Walkthroughs set'],['quotes','Quotes delivered'],['jobs','Jobs won'],['revenue','Collected revenue'],['labor','Direct labor'],['disposal','Dump / disposal'],['fuel','Fuel'],['other','Other direct cost'],['crewHours','Crew hours']];return fs.map(([k,l])=>`<label><span>${l}</span><div>${['spend','revenue','labor','disposal','fuel','other'].includes(k)?'<b>$</b>':''}<input type="number" min="0" step="0.01" name="${k}" value="${esc(d[k])}" inputmode="decimal"></div></label>`).join('')}
window.opsSaveScorecard=function(){const f=$('#ops-score-form');if(!f)return;const out={};new FormData(f).forEach((v,k)=>out[k]=Number(v||0));localStorage.setItem('egc_scorecard',JSON.stringify(out));render();if(typeof showToast==='function')showToast('Scorecard saved')};
const legacyRefresh=window.refresh;window.refresh=function(){if(legacyRefresh)legacyRefresh();render()};
const legacyBoot=window.bootDashboard;window.bootDashboard=function(){if(legacyBoot)legacyBoot();install();render()};install();
})();
