(() => {
'use strict';
const $=id=>document.getElementById(id),params=new URLSearchParams(location.hash.slice(1));let invitation=params.get('invite')||'',reset=false;
history.replaceState(null,'',location.pathname);
async function call(payload){const response=await fetch('/api/staff-setup',{method:'POST',credentials:'same-origin',cache:'no-store',headers:{'Content-Type':'application/json','X-EGC-Staff-Setup':'1'},body:JSON.stringify(payload)});const body=await response.json();if(!response.ok)throw new Error(body.error||'Setup could not be completed.');return body;}
// A staff sign-in reset link (STAFF-ACCESS) sets a new password on an existing account: no work email, the employee
// account password rule, and a pointer to normal staff sign-in afterwards.
function resetMode(){document.title='Choose a new EGC password';const heading=document.querySelector('h1'),eyebrow=document.querySelector('.eyebrow'),hint=$('setup').querySelector('.small'),email=$('email');if(heading)heading.textContent='Choose a new password.';if(eyebrow)eyebrow.textContent='STAFF SIGN-IN RESET';email.required=false;email.closest('label').hidden=true;for(const id of ['password','confirm'])$(id).minLength=10;$('activate').textContent='Save my new password';if(hint)hint.textContent='Use at least 10 characters with an uppercase letter, a lowercase letter and a number. This link works once, for 24 hours from when your manager made it. Do not forward it.';const done=document.createElement('p'),next=document.createElement('p'),link=document.createElement('a');done.textContent='Your new password is saved. Sign in with your username and the password you just chose.';link.className='text-link';link.href='/staff-login';link.textContent='Go to staff sign-in';next.append(link);$('complete').replaceChildren(done,next);}
async function init(){try{if(!invitation)throw new Error('Open the private setup link in the email Zac sent you.');const account=await call({action:'inspect',invite:invitation});reset=account.kind==='reset';$('identity').textContent=account.name+' · Username: '+account.username;if(reset)resetMode();else $('email').value=account.email;$('status').textContent=(reset?'This link expires ':'This invitation expires ')+new Date(account.expiresAt).toLocaleString()+'.';$('setup').hidden=false;}catch(error){$('status').textContent=error.message;}}
$('setup').addEventListener('submit',async event=>{event.preventDefault();const password=$('password').value,confirmPassword=$('confirm').value;if(password!==confirmPassword){$('status').textContent='The two passwords do not match.';return;}$('activate').disabled=true;try{const result=await call(reset?{action:'reset',invite:invitation,password,confirmPassword}:{action:'redeem',invite:invitation,email:$('email').value,password,confirmPassword});invitation='';$('setup').reset();$('setup').hidden=true;$('complete').hidden=false;$('status').textContent=(reset?'New password saved. Your username is ':'Account activated. Your username is ')+result.username+'.';}catch(error){$('status').textContent=error.message;$('password').value='';$('confirm').value='';}finally{$('activate').disabled=false;}});
init();
})();
