import test from 'node:test';
import assert from 'node:assert/strict';
import { createBusinessHandler } from '../functions/_lib/business-hub-service.js';
import { rights, activeMember, requireLinkedJob, businessActor, parseBusinessActor, projectView, accountView, uid, digest } from '../functions/_lib/business-hub-core.js';
const origin='https://easygaragecleaning.com';
class MemoryStore {
  constructor(){this.records=new Map();this.clock=0;}
  async read(c,id){return structuredClone(this.records.get(c+'/'+id)||null);}
  async commit(changes){
    for(const w of changes){const old=this.records.get(w.collection+'/'+w.id);if(w.version ? old?._version!==w.version : Boolean(old))throw Object.assign(new Error('Conflict'),{status:409,publicMessage:'Conflict'});}
    for(const w of changes){const key=w.collection+'/'+w.id,old=this.records.get(key);this.records.set(key,{...(w.patch?old:{}),...structuredClone(w.data),id:w.id,_version:String(++this.clock)});}
  }
  async list(profile){return {accounts:[...this.records.entries()].filter(([k,v])=>k.startsWith('business_accounts/')&&(profile.businessAccess||v.ownerStaff===profile.user)).map(([,v])=>structuredClone(v)),next:''};}
  async jobs(ids){return new Map((await Promise.all(ids.map(i=>this.read('jobs',i)))).filter(Boolean).map(j=>[j.id,j]));}
}
function setup(){
 const store=new MemoryStore();let clock=Date.UTC(2026,8,23,18);let staff={user:'zacb',displayName:'Zac',businessAccess:true,role:'owner'};
 const handler=createBusinessHandler({store,getStaff:async()=>staff,finance:j=>({total:j.total||0,paid:j.paid||0,balance:(j.total||0)-(j.paid||0)}),needsReview:j=>Boolean(j.review),projectCookie:async(jobId,claims)=>`project=${jobId}:${claims.actorId}; HttpOnly; Secure`,clearProjectCookie:()=> 'project=; Max-Age=0',now:()=>clock});
 async function call(payload,{url='',cookie='',headers={}}={}){const request=new Request(origin+'/api/business-hub'+url,{method:payload?'POST':'GET',headers:{Origin:origin,'Content-Type':'application/json','X-EGC-Business':'1',Cookie:cookie,...headers},...(payload?{body:JSON.stringify(payload)}:{})});const res=await handler(request);return {status:res.status,data:await res.json(),cookie:res.headers.get('Set-Cookie')};}
 async function onboard(company='Client Company'){const created=await call({action:'create_account',company,name:'Client Admin',email:'admin@example.com'},{url:'?staff=1'});assert.equal(created.status,201);const accepted=await call({action:'redeem',invite:created.data.invite});assert.equal(accepted.status,200);return {accountId:created.data.accountId,invite:created.data.invite,cookie:accepted.cookie.split(';')[0],staffUrl:'?staff=1&account='+created.data.accountId};}
 return {store,call,onboard,setStaff:value=>staff=value,advance:ms=>clock+=ms};
}
test('private account onboarding, single-use invitation and HttpOnly cookie',async()=>{const h=setup(),a=await h.onboard();assert.match(a.cookie,/^__Host-egc_business=/);assert.equal((await h.call(null,{cookie:a.cookie})).data.account.company,'Client Company');assert.equal((await h.call({action:'redeem',invite:a.invite})).status,401);const saved=await h.store.read('business_accounts',a.accountId);assert.equal(saved.members[0].inviteHash,undefined);assert.equal(saved.acquisition.channel,'b2b');});
test('anonymous reads denied; cross-site and missing-origin writes denied',async()=>{const h=setup();assert.equal((await h.call()).status,401);assert.equal((await h.call({action:'create_account'},{url:'?staff=1',headers:{Origin:'https://evil.example'}})).status,403);assert.equal((await h.call({action:'create_account'},{url:'?staff=1',headers:{Origin:''}})).status,403);});
test('companies remain isolated even when a customer sends another account ID',async()=>{const h=setup(),a=await h.onboard('Alpha'),b=await h.onboard('Beta');const loaded=await h.call(null,{url:'?account='+b.accountId,cookie:a.cookie});assert.equal(loaded.data.account.id,a.accountId);assert.equal(loaded.data.account.company,'Alpha');assert.equal(loaded.data.projects.length,0);});
test('properties, idempotent requests, saved messages, no automatic bookings',async()=>{const h=setup(),a=await h.onboard();const p=await h.call({action:'save_property',name:'Unit 2',address:'100 Sample Avenue'},{cookie:a.cookie});assert.equal(p.status,200);const request={action:'request_service',requestId:uid(),propertyId:p.data.propertyId,service:'Garage cleanout',scope:'Remove approved contents.',payer:'Client',preferredDate:'2026-10-01'};assert.equal((await h.call(request,{cookie:a.cookie})).status,201);assert.equal((await h.call(request,{cookie:a.cookie})).data.duplicate,true);const msg={action:'message',messageId:uid(),body:'Please confirm the date.'};assert.equal((await h.call(msg,{cookie:a.cookie})).status,201);assert.equal((await h.call(msg,{cookie:a.cookie})).data.duplicate,true);const result=(await h.call(null,{cookie:a.cookie})).data;assert.equal(result.requests.length,1);assert.equal(result.requests[0].status,'submitted');assert.equal(result.requests[0].referralAccountId,a.accountId);assert.equal(result.projects.length,0);assert.equal(result.messages.length,1);});
test('billing and viewer roles cannot request work or invite administrators',async()=>{const h=setup(),a=await h.onboard();for(const role of ['billing','viewer']){const inv=await h.call({action:'invite_member',name:role,email:role+'@example.com',role},{cookie:a.cookie});const redeemed=await h.call({action:'redeem',invite:inv.data.invite});const cookie=redeemed.cookie.split(';')[0];assert.equal((await h.call({action:'save_property',name:'X',address:'X'},{cookie})).status,403);assert.equal((await h.call({action:'invite_member',name:'Escalate',email:'new@example.com',role:'admin'},{cookie})).status,403);if(role==='viewer')assert.equal((await h.call({action:'message',messageId:uid(),body:'No'},{cookie})).status,403);}});
test('staff cannot see other sales accounts; crew is not B2B staff',async()=>{const h=setup();await h.onboard();h.setStaff({user:'sales2',role:'sales',businessAccess:false});assert.equal((await h.call(null,{url:'?staff=1'})).data.accounts.length,0);h.setStaff({user:'crew1',role:'crew',businessAccess:false});assert.equal((await h.call(null,{url:'?staff=1'})).status,403);});
test('linking requires explicit staff authorization and canonical tenant markers',async()=>{const h=setup(),a=await h.onboard(),b=await h.onboard();const p=(await h.call({action:'save_property',name:'Warehouse',address:'5 Sample Road'},{cookie:a.cookie})).data.propertyId;await h.store.commit([{collection:'jobs',id:'job_one',data:{type:'job',total:1000,estimate:{amount:1000,status:'sent'},invoice:{number:'I-1',status:'ready'},initialSource:'Meta'}}]);const input={action:'link_project',propertyId:p,jobId:'job_one',sharingAuthorized:true};assert.equal((await h.call(input,{cookie:a.cookie})).status,403);assert.equal((await h.call({...input,sharingAuthorized:false},{url:a.staffUrl})).status,400);assert.equal((await h.call(input,{url:a.staffUrl})).status,200);const j=await h.store.read('jobs','job_one');assert.equal(j.initialSource,'Meta');assert.equal(j.businessAccountId,a.accountId);const snapshot=(await h.call(null,{cookie:a.cookie})).data;assert.equal(snapshot.projects[0].total,1000);assert.equal(snapshot.projects[0].balance,1000);assert.equal((await h.call({action:'open_project',jobId:'job_one'},{cookie:b.cookie})).status,403);const open=await h.call({action:'open_project',jobId:'job_one'},{cookie:a.cookie});assert.equal(open.status,200);assert.match(open.cookie,/biz_/);assert.equal(open.data.url,'/customer-portal');});
test('revoking a member invalidates existing business sessions',async()=>{const h=setup(),a=await h.onboard();const invited=await h.call({action:'invite_member',role:'viewer',name:'Viewer',email:'view@example.com'},{cookie:a.cookie});const login=await h.call({action:'redeem',invite:invited.data.invite});const cookie=login.cookie.split(';')[0],memberId=invited.data.invite.split('.')[1];assert.equal((await h.call(null,{cookie})).status,200);assert.equal((await h.call({action:'revoke_member',memberId},{cookie:a.cookie})).status,200);assert.equal((await h.call(null,{cookie})).status,401);});
test('last active admin cannot revoke themselves; logout invalidates stored session',async()=>{const h=setup(),a=await h.onboard();const saved=await h.store.read('business_accounts',a.accountId);assert.equal((await h.call({action:'revoke_member',memberId:saved.members[0].id},{cookie:a.cookie})).status,409);assert.equal((await h.call({action:'logout'},{cookie:a.cookie})).status,200);assert.equal((await h.call(null,{cookie:a.cookie})).status,401);});
test('invitation expiry and session expiry are enforced',async()=>{const h=setup();const created=await h.call({action:'create_account',company:'Expiry',name:'Admin',email:'admin@expiry.example'},{url:'?staff=1'});h.advance(49*3600000);assert.equal((await h.call({action:'redeem',invite:created.data.invite})).status,401);const a=await h.onboard();h.advance(8*86400000);assert.equal((await h.call(null,{cookie:a.cookie})).status,401);});
test('project projection hides drafts, internal notes and unverified balances',()=>{const aid=uid(),pid=uid(),account={id:aid,projects:[{jobId:'job',propertyId:pid}]},link=account.projects[0],job={id:'job',businessAccountId:aid,businessPropertyId:pid,notes:'staff only',estimate:{status:'draft'},invoice:{status:'draft',number:'INV'}};const finance={total:1200,paid:200,balance:1000};const draft=projectView(account,link,job,finance,true);assert.equal(draft.total,null);assert.equal(draft.balance,null);assert.equal(draft.invoiceNumber,'');assert.equal(draft.notes,undefined);job.estimate.status='sent';job.invoice.status='ready';assert.equal(projectView(account,link,job,finance,true).balance,null);job.businessAccountId=uid();assert.equal(projectView(account,link,job,finance,false).unavailable,true);});
test('delegated actor binds member version and role mapping',()=>{const accountId=uid(),member={id:uid(),version:2,role:'billing',status:'active'};const actor=businessActor(accountId,member);assert.deepEqual(parseBusinessActor(actor),{accountId,memberId:member.id,version:2});assert.equal(rights(member).pay,true);assert.equal(rights(member).decide,false);assert.throws(()=>activeMember({status:'active',members:[member]},member.id,1),/access has changed/);});
test('raw account invitation hashes and audit metadata never reach client DTOs',()=>{const account={id:uid(),company:'Private',billingEmail:'bill@example.com',status:'active',members:[{id:uid(),name:'Admin',email:'admin@example.com',role:'admin',status:'active',inviteHash:'secret'}],properties:[],requests:[],messages:[],projects:[],ownerStaff:'zacb',acquisition:{private:'internal'}};const dto=accountView(account,account.members[0],[]);assert.equal(JSON.stringify(dto).includes('secret'),false);assert.equal(dto.account.ownerStaff,undefined);assert.equal(dto.account.acquisition,undefined);});
test('atomic writes reject stale versions and never partially link a job',async()=>{const store=new MemoryStore(),id=uid();await store.commit([{collection:'business_accounts',id,data:{company:'Original'}}]);const stale=await store.read('business_accounts',id);await store.commit([{collection:'business_accounts',id,data:{company:'Changed'},version:stale._version}]);await assert.rejects(()=>store.commit([{collection:'jobs',id:'job',data:{businessAccountId:id}},{collection:'business_accounts',id,data:{company:'Stale'},version:stale._version}]),/Conflict/);assert.equal(await store.read('jobs','job'),null);});
test('reused request IDs cannot silently replace a different scope',async()=>{const h=setup(),a=await h.onboard();const p=(await h.call({action:'save_property',name:'Property',address:'Example street'},{cookie:a.cookie})).data.propertyId;const request={action:'request_service',requestId:uid(),propertyId:p,service:'Cleanout',scope:'Original scope',payer:'Client'};assert.equal((await h.call(request,{cookie:a.cookie})).status,201);assert.equal((await h.call({...request,scope:'Changed scope'},{cookie:a.cookie})).status,409);});
test('invalid calendar dates fail without saving a request',async()=>{const h=setup(),a=await h.onboard();const p=(await h.call({action:'save_property',name:'Property',address:'Example street'},{cookie:a.cookie})).data.propertyId;for(const preferredDate of ['2026-02-31','2026-13-01'])assert.equal((await h.call({action:'request_service',requestId:uid(),propertyId:p,service:'Cleanout',scope:'Work',payer:'Client',preferredDate},{cookie:a.cookie})).status,400);});
test('unissued quotes cannot be opened through the project handoff',async()=>{const h=setup(),a=await h.onboard();const p=(await h.call({action:'save_property',name:'Property',address:'Example street'},{cookie:a.cookie})).data.propertyId;await h.store.commit([{collection:'jobs',id:'draft_job',data:{type:'job',total:1000,estimate:{status:'draft'}}}]);await h.call({action:'link_project',jobId:'draft_job',propertyId:p,sharingAuthorized:true},{url:a.staffUrl});assert.equal((await h.call({action:'open_project',jobId:'draft_job'},{cookie:a.cookie})).status,409);});
// Evaluate the exact access helper with dependency stubs; no provider credentials
// or real customer records are used by this regression test.
import { readFileSync } from 'node:fs';
const accessSource=readFileSync(new URL('../functions/_lib/customer-portal-access.js',import.meta.url),'utf8').replace(/^import .*;\n/gm,'').replace('export async function readCustomerPortalContext','async function readCustomerPortalContext');
const accessHelper=new Function('readJob','sameOperationalProperty','verifiedAccountRoot','readBusinessProjectViewer',accessSource+'\nreturn readCustomerPortalContext;')(null,()=>false,()=>{throw new Error('Should not load a homeowner root');},null);
test('business handoff strips family collaborators, account wallet and internal notes',async()=>{const job={id:'shared',__updateTime:'v1',customerAccountOwnerJobId:'unshared_root',notes:'Internal staff note',customerCollaborators:[{name:'Private person'}],giftWallet:{cards:[{amount:500}]},garageGuard:{plan:'black'}};const result=await accessHelper({}, {jobId:'shared',actorId:'biz_test'}, {read:async()=>job,businessRead:async()=>({name:'Billing User',permissions:{view:true,pay:true,decide:false,rebook:false}})});assert.equal(result.accountJobId,'shared');assert.equal(result.job.notes,'');assert.equal(result.job.customerCollaborators[0].name,'Billing User');assert.equal(result.job.giftWallet.cards.length,0);assert.deepEqual(result.job.garageGuard,{});assert.equal(result.session.permissions.decide,false);});
test('business project access is rechecked on every delegated request',async()=>{let calls=0;const options={read:async()=>({id:'shared'}),businessRead:async()=>{calls++;if(calls>1)throw Object.assign(new Error(),{status:403,publicMessage:'Access revoked'});return {name:'Client',permissions:{view:true}};}};await accessHelper({}, {jobId:'shared',actorId:'biz_test'},options);await assert.rejects(()=>accessHelper({}, {jobId:'shared',actorId:'biz_test'},options),e=>e.status===403&&e.code==='CUSTOMER_PORTAL_BUSINESS_ACCESS');assert.equal(calls,2);});
test('a business project grant never becomes a homeowner owner session',async()=>{const session={jobId:'shared',actorId:'biz_test',permissions:{view:true,decide:true,pay:true}};const result=await accessHelper({},session,{read:async()=>({id:'shared'}),businessRead:async()=>({name:'Viewer',permissions:{view:true,decide:false,pay:false,rebook:false}})});assert.equal(result.session.actorId,'biz_test');assert.equal(result.session.permissions.pay,false);assert.equal(result.session.permissions.decide,false);});
test('prototype names are not accepted as account roles',async()=>{const h=setup(),a=await h.onboard();assert.equal((await h.call({action:'invite_member',role:'__proto__',name:'Wrong role',email:'wrong@example.com'},{cookie:a.cookie})).status,400);});
test('workspace size limit fails before any write',async()=>{const h=setup(),a=await h.onboard();const saved=await h.store.read('business_accounts',a.accountId);saved.largeHistory='x'.repeat(760000);await h.store.commit([{collection:'business_accounts',id:a.accountId,data:saved,version:saved._version}]);assert.equal((await h.call({action:'save_property',name:'New property',address:'Test address'},{cookie:a.cookie})).status,409);assert.equal((await h.store.read('business_accounts',a.accountId)).properties.length,0);});
