import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {syncNativeSchedule} from '../functions/_lib/operations-schedule-sync.js';
import {createHubSessionCookie} from '../functions/_lib/hub-session.js';
import {mutateScheduledVisit,resolveScheduledVisit,bindScheduledProvider,linkScheduledCustomer} from '../functions/_lib/operations-scheduling.js';
const actor={id:'verified-grant',kind:'integration',role:'integration',workspace:'egc'};
function fixture(){
 const rows=new Map([['customers/customer-a',{id:'customer-a',name:'Synthetic customer',highlevelContactId:'contact-a',revision:'customer-r1'}]]);let revision=0;
 const store={customers:async providerId=>[...rows.entries()].filter(([k,v])=>k.startsWith('customers/')&&v.highlevelContactId===providerId).map(([,v])=>structuredClone(v)),read:async(c,id)=>structuredClone(rows.get(`${c}/${id}`)||null),day:async date=>[...rows.entries()].filter(([k,v])=>k.startsWith('jobs/')&&v.date===date).map(([,v])=>structuredClone(v)),commit:async writes=>{
   for(const w of writes){const prior=rows.get(`${w.collection}/${w.id}`);if(w.revision?prior?.revision!==w.revision:Boolean(prior))throw Object.assign(new Error('schedule_revision_conflict'),{status:409});}
   for(const w of writes)rows.set(`${w.collection}/${w.id}`,{...rows.get(`${w.collection}/${w.id}`),...structuredClone(w.patch),id:w.id,revision:`r${++revision}`});return{};
 }};
 const input=(extra={})=>({command:'schedule.mutate',requestId:randomUUID(),mode:'create',portalCustomerId:'customer-a',kind:'walkthrough',changes:{date:'2026-09-23',time:'10:00',endTime:'11:00'},...extra});
 return{rows,store,input};
}
test('native verified provider link creates one exact customer/project and claims shared sender',async()=>{const f=fixture();f.rows.set('jobs/native',{id:'native',type:'walkthrough',highlevelContactId:'contact-new',date:'2026-09-23',time:'12:00',endTime:'13:00',status:'scheduled',revision:'v1'});const r=await linkScheduledCustomer(f.store,actor,{portalVisitId:'native',expectedRevision:'v1',providerContact:{id:'contact-new',email:'synthetic@example.invalid'}});assert.equal(r.visit.portalCustomerId,'ghl_contact-new');assert.equal(r.visit.portalProjectId,'project_native');assert.equal(f.rows.get('jobs/native').providerSyncOwner,'operations');assert.equal(f.rows.get('projects/project_native').sourceRecordId,'native');});
test('native exact provider contact reuses unique customer; ambiguous mapping fails before writes',async()=>{const f=fixture();const visit={id:'native',type:'walkthrough',highlevelContactId:'contact-a',date:'2026-09-23',time:'12:00',endTime:'13:00',status:'scheduled',revision:'v1'};f.rows.set('jobs/native',visit);f.rows.set('customers/duplicate',{id:'duplicate',highlevelContactId:'contact-a',revision:'d1'});await assert.rejects(linkScheduledCustomer(f.store,actor,{portalVisitId:'native',expectedRevision:'v1',providerContact:{id:'contact-a'}}),/ambiguous/);assert.equal(f.rows.get('jobs/native').customerId,undefined);f.rows.delete('customers/duplicate');const r=await linkScheduledCustomer(f.store,actor,{portalVisitId:'native',expectedRevision:'v1',providerContact:{id:'contact-a'}});assert.equal(r.visit.portalCustomerId,'customer-a');});
test('native missing provider link requires exact verified contact evidence without conflicting PII',async()=>{const f=fixture();f.rows.set('jobs/native',{id:'native',type:'walkthrough',phone:'2025550100',email:'a@example.invalid',revision:'v1'});await assert.rejects(linkScheduledCustomer(f.store,actor,{portalVisitId:'native',expectedRevision:'v1',providerContact:{id:'contact-a',phone:'+12025550100',email:'different@example.invalid'}}),/matching_requires_review/);await assert.rejects(linkScheduledCustomer(f.store,{...actor,kind:'human',role:'owner'},{portalVisitId:'native',expectedRevision:'v1',providerContact:{id:'contact-a'}}),/requires_integration/);});
test('job created from exact walkthrough shares its authoritative project',async()=>{const f=fixture(),walk=await mutateScheduledVisit(f.store,actor,f.input());const job=await mutateScheduledVisit(f.store,actor,f.input({kind:'job',sourceWalkthroughId:walk.visit.portalVisitId,changes:{date:'2026-09-24',time:'10:00',endTime:'11:00'}}));assert.equal(job.visit.portalProjectId,walk.visit.portalProjectId);assert.equal(f.rows.get('jobs/'+job.visit.portalVisitId).sourceWalkthroughId,walk.visit.portalVisitId);assert.equal([...f.rows.keys()].filter(k=>k.startsWith('projects/')).length,1);});
test('native signed gateway preserves exact visit and stable logical operation, no browser schedule fields',async()=>{const env={EGC_OPERATIONS_API_ORIGIN:'https://api.example.test',EGC_OPERATIONS_PORTAL_SIGNING_SECRET:'s'.repeat(40)},requests=[];const fetcher=async(url,init)=>{requests.push(JSON.parse(init.body));return new Response(JSON.stringify({ok:true,authority:'employee_hub',portalVisitId:'native',providerSync:'verified',appointmentId:'provider-one'}),{status:200});};for(let i=0;i<2;i++)await syncNativeSchedule(env,{user:'manager'},{portalVisitId:'native',requestId:'schedule:native:saved-revision',contactProviderId:'contact-a'},fetcher);for(const request of requests){const encoded=request.envelope.split('.')[0],claims=JSON.parse(Buffer.from(encoded,'base64url'));assert.equal(claims.request.body.requestId,'schedule:native:saved-revision');assert.equal(claims.actor.id,'hub-schedule:manager');assert.equal(claims.request.body.portalVisitId,'native');assert.equal(claims.request.body.startTime,undefined);}});
test('native gateway unknown or unverified outcomes cannot masquerade as synchronized',async()=>{const env={EGC_OPERATIONS_API_ORIGIN:'https://api.example.test',EGC_OPERATIONS_PORTAL_SIGNING_SECRET:'s'.repeat(40)},input={portalVisitId:'native',requestId:'stable'};await assert.rejects(syncNativeSchedule(env,{user:'manager'},input,async()=>{throw new Error('token-secret');}),/outcome_unknown/);await assert.rejects(syncNativeSchedule(env,{user:'manager'},input,async()=>new Response(JSON.stringify({ok:true,authority:'employee_hub',portalVisitId:'other',providerSync:'verified'}))),/response_unverified/);});
test('real native schedule route uses signed durable sender and never calls legacy provider calendar write',async()=>{
 const {onRequestPost}=await import('../functions/api/highlevel.js'),original=globalThis.fetch,calls=[];
 const env={HUB_SESSION_SECRET:'test-session',HUB_AUTH_USERS_JSON:JSON.stringify({ZacB:{passwordHash:'test-only',role:'owner',displayName:'Synthetic'}}),HIGHLEVEL_API_KEY:'synthetic',HIGHLEVEL_LOCATION_ID:'location',EGC_OPERATIONS_ENABLED:'true',EGC_OPERATIONS_API_ORIGIN:'https://api.example.test',EGC_OPERATIONS_PORTAL_SIGNING_SECRET:'s'.repeat(40)};
 const cookie=(await createHubSessionCookie(env,'ZacB')).split(';')[0];
 globalThis.fetch=async(url,init={})=>{calls.push({url:String(url),init});if(String(url)==='https://api.example.test/operations/rpc')return new Response(JSON.stringify({ok:true,authority:'employee_hub',portalVisitId:'native',providerSync:'verified',appointmentId:'verified-event'}));return new Response('{}');};
 try{const request=new Request('https://easygaragecleaning.com/api/highlevel',{method:'POST',headers:{Origin:'https://easygaragecleaning.com',Cookie:cookie,'Content-Type':'application/json'},body:JSON.stringify({tool:'schedule',job_id:'native',silent_update:true,idempotency_key:'native-stable',start_time:'2026-10-01T16:00:00Z',end_time:'2026-10-01T17:00:00Z',highlevel_contact_id:'contact-a',client:{name:'Synthetic'}})});const response=await onRequestPost({request,env}),result=await response.json();assert.equal(response.status,200);assert.equal(result.appointmentId,'verified-event');assert.equal(calls.filter(c=>c.url.includes('/operations/rpc')).length,1);assert.ok(!calls.some(c=>c.url.includes('/calendars/')));}finally{globalThis.fetch=original;}
});
test('canonical Hub create records exact customer, native date lock and durable audit receipt',async()=>{
 const f=fixture(),input=f.input(),r=await mutateScheduledVisit(f.store,actor,input);assert.equal(r.authority,'employee_hub');assert.equal(r.visit.portalCustomerId,'customer-a');assert.equal(r.visit.startTime,'2026-09-23T16:00:00.000Z');assert.equal(r.visit.syncStatus,'pending');assert.equal(r.visit.portalProjectId,'project_'+r.visit.portalVisitId);assert.equal(f.rows.get('projects/'+r.visit.portalProjectId).sourceRecordId,r.visit.portalVisitId);assert.equal(f.rows.get('jobs/_egc_schedule_lock_2026-09-23').entries[0].id,r.visit.portalVisitId);assert.equal([...f.rows.values()].filter(x=>x.recordType==='schedule_operation').length,1);
});
test('same logical request is replayed without another visit or lock entry',async()=>{const f=fixture(),input=f.input(),a=await mutateScheduledVisit(f.store,actor,input),b=await mutateScheduledVisit(f.store,actor,input);assert.equal(a.visit.portalVisitId,b.visit.portalVisitId);assert.equal(b.replayed,true);assert.equal(f.rows.get('jobs/_egc_schedule_lock_2026-09-23').entries.length,1);});
test('concurrent identical retries have one receipt, concurrent different slot claims cannot overlap',async()=>{const f=fixture(),input=f.input();const same=await Promise.all(Array.from({length:6},()=>mutateScheduledVisit(f.store,actor,input)));assert.equal(new Set(same.map(x=>x.visit.portalVisitId)).size,1);const g=fixture();const results=await Promise.allSettled(Array.from({length:6},()=>mutateScheduledVisit(g.store,actor,g.input())));assert.equal(results.filter(x=>x.status==='fulfilled').length,1);assert.equal([...g.rows.values()].filter(x=>x.type==='walkthrough').length,1);});
test('stale revision and cross-customer changes are rejected',async()=>{const f=fixture(),r=await mutateScheduledVisit(f.store,actor,f.input());await assert.rejects(mutateScheduledVisit(f.store,actor,f.input({mode:'update',portalVisitId:r.visit.portalVisitId,expectedRevision:'stale'})),/revision_conflict/);f.rows.set('customers/customer-b',{id:'customer-b',revision:'r0'});await assert.rejects(mutateScheduledVisit(f.store,actor,f.input({mode:'update',portalVisitId:r.visit.portalVisitId,portalCustomerId:'customer-b',expectedRevision:r.visit.revision})),/customer_link/);});
test('reschedule atomically releases old day lock and preserves scope/payment data',async()=>{const f=fixture(),r=await mutateScheduledVisit(f.store,actor,f.input()),row=f.rows.get(`jobs/${r.visit.portalVisitId}`);row.scope={keep:['synthetic']};row.deposit={status:'paid',amount:20};const moved=await mutateScheduledVisit(f.store,actor,f.input({mode:'update',portalVisitId:row.id,expectedRevision:row.revision,changes:{date:'2026-09-24',time:'12:00',endTime:'13:00'}}));assert.deepEqual(f.rows.get(`jobs/${row.id}`).scope,{keep:['synthetic']});assert.equal(f.rows.get(`jobs/${row.id}`).deposit.amount,20);assert.equal(f.rows.get('jobs/_egc_schedule_lock_2026-09-23').entries.length,0);assert.equal(f.rows.get('jobs/_egc_schedule_lock_2026-09-24').entries[0].id,row.id);assert.equal(moved.visit.date,'2026-09-24');});
test('cancel retains visit/customer/history and releases occupied slot',async()=>{const f=fixture(),r=await mutateScheduledVisit(f.store,actor,f.input());const c=await mutateScheduledVisit(f.store,actor,f.input({mode:'cancel',portalVisitId:r.visit.portalVisitId,expectedRevision:r.visit.revision,changes:{}}));assert.equal(c.visit.status,'cancelled');assert.equal(f.rows.get('jobs/_egc_schedule_lock_2026-09-23').entries.length,0);assert.equal([...f.rows.values()].filter(x=>x.recordType==='schedule_operation').length,2);assert.equal((await resolveScheduledVisit(f.store,r.visit.portalVisitId)).visit.portalCustomerId,'customer-a');});
test('missing explicit customer mapping is never guessed by phone or name',async()=>{const f=fixture();f.rows.set('jobs/legacy',{id:'legacy',type:'walkthrough',customer:'Synthetic customer',phone:'5555550100',revision:'v1'});await assert.rejects(resolveScheduledVisit(f.store,'legacy'),/customer_link_missing/);await assert.rejects(mutateScheduledVisit(f.store,actor,f.input({portalCustomerId:'unknown'})),/customer_not_found/);});
test('invalid and ambiguous DST times fail without creating a visit',async()=>{const f=fixture();for(const changes of [{date:'2026-02-30',time:'10:00',endTime:'11:00'},{date:'2026-11-01',time:'01:15',endTime:'01:45'},{date:'2026-03-08',time:'02:15',endTime:'03:15'}])await assert.rejects(mutateScheduledVisit(f.store,actor,f.input({changes})),/time_invalid/);assert.equal([...f.rows.values()].filter(x=>x.type).length,0);});
test('legacy scheduled records outside lock entries still prevent collision',async()=>{const f=fixture();f.rows.set('jobs/legacy',{id:'legacy',type:'job',date:'2026-09-23',time:'10:30',endTime:'12:30',status:'scheduled'});await assert.rejects(mutateScheduledVisit(f.store,actor,f.input()),/slot_conflict/);});
test('changed payload under same request cannot reuse its receipt',async()=>{const f=fixture(),input=f.input();await mutateScheduledVisit(f.store,actor,input);await assert.rejects(mutateScheduledVisit(f.store,actor,{...input,changes:{...input.changes,title:'Different'}}),/idempotency_conflict/);});
test('old request after another edit cannot certify or synchronize the new schedule',async()=>{const f=fixture(),input=f.input(),r=await mutateScheduledVisit(f.store,actor,input);await mutateScheduledVisit(f.store,actor,f.input({mode:'update',portalVisitId:r.visit.portalVisitId,expectedRevision:r.visit.revision,changes:{time:'12:00',endTime:'13:00'}}));await assert.rejects(mutateScheduledVisit(f.store,actor,input),/changed_since_operation/);});
test('unknown commit outcome is reconciled by receipt before returning success',async()=>{const f=fixture(),original=f.store.commit;f.store.commit=async writes=>{await original(writes);throw new Error('response lost');};const r=await mutateScheduledVisit(f.store,actor,f.input());assert.equal(r.ok,true);assert.equal([...f.rows.values()].filter(x=>x.type==='walkthrough').length,1);});
test('only exact verified provider data attaches; it cannot rewrite native schedule',async()=>{const f=fixture(),r=await mutateScheduledVisit(f.store,actor,f.input());const input={operationId:randomUUID(),portalVisitId:r.visit.portalVisitId,expectedRevision:r.visit.revision,event:{id:'provider-event',contactId:'contact-a',calendarId:'calendar',startTime:r.visit.startTime,endTime:r.visit.endTimeInstant,appointmentStatus:'confirmed'}};await assert.rejects(bindScheduledProvider(f.store,{...actor,kind:'human',role:'owner'},input),/requires_integration/);await assert.rejects(bindScheduledProvider(f.store,actor,{...input,event:{...input.event,contactId:'other'}}),/identity_conflict/);await assert.rejects(bindScheduledProvider(f.store,actor,{...input,event:{...input.event,startTime:'2026-09-23T18:00:00Z'}}),/state_conflict/);const bound=await bindScheduledProvider(f.store,actor,input);assert.equal(bound.visit.highlevelAppointmentId,'provider-event');assert.equal(bound.visit.time,'10:00');assert.equal(bound.visit.syncStatus,'synced');assert.equal((await bindScheduledProvider(f.store,actor,input)).replayed,true);});
