import test from 'node:test';
import assert from 'node:assert/strict';
import {portalCalendar,portalJob,portalEvidence,localInstant} from '../functions/_lib/operations-portal-records.js';
import {signOperationsEnvelope,verifyOperationsEnvelope} from '../functions/_lib/operations-envelope.js';
import {sameOrigin,onRequestPost as gateway} from '../functions/api/operations.js';
import {onRequestPost as native} from '../functions/api/operations-portal.js';
const key='isolated-webcrypto-test-key-01234567890123456789';
const claims=()=>({v:1,iss:'portal',aud:'egc-portal',iat:Math.floor(Date.now()/1000),nonce:crypto.randomUUID(),actor:{id:'test-owner',role:'owner',kind:'human',workspace:'egc'},request:{requestId:crypto.randomUUID(),body:{command:'portal.job',jobId:'portal-a'}}});
const value=v=>typeof v==='string'?{stringValue:v}:v===null?{nullValue:null}:typeof v==='boolean'?{booleanValue:v}:typeof v==='number'?{integerValue:String(v)}:Array.isArray(v)?{arrayValue:{values:v.map(value)}}:{mapValue:{fields:Object.fromEntries(Object.entries(v).map(([k,x])=>[k,value(x)]))}};
const doc=(id,fields={})=>({name:'projects/test/databases/(default)/documents/jobs/'+id,updateTime:'2026-09-18T18:00:00Z',fields:Object.fromEntries(Object.entries({type:'job',date:'2026-09-18',time:'10:00',endTime:'11:00',customer:'Synthetic',...fields}).map(([k,x])=>[k,value(x)]))});
const range={startDate:'2026-09-18',endDate:'2026-09-20',timeZone:'America/Denver',offset:0,limit:50};
const response=body=>new Response(JSON.stringify(body),{status:200,headers:{'Content-Type':'application/json'}});

test('portable HMAC verifies exact claims and rejects actor/payload tampering',async()=>{const c=claims(),t=await signOperationsEnvelope(c,key);assert.deepEqual(await verifyOperationsEnvelope(t,key,'egc-portal'),c);const [p,s]=t.split('.');const other=JSON.parse(Buffer.from(p,'base64url').toString());other.actor.id='forged';await assert.rejects(verifyOperationsEnvelope(Buffer.from(JSON.stringify(other)).toString('base64url')+'.'+s,key,'egc-portal'));});
test('portable HMAC denies expiry, audience mismatch and missing key',async()=>{const c=claims(),t=await signOperationsEnvelope(c,key);await assert.rejects(verifyOperationsEnvelope(t,key,'egc-operations'));await assert.rejects(verifyOperationsEnvelope(t,key,'egc-portal',Date.now()+120000));await assert.rejects(verifyOperationsEnvelope(t,'short','egc-portal'));});
test('portal native endpoint is off by default and unsigned requests are unauthorized',async()=>{const req=()=>new Request('https://portal.test/api/operations-portal',{method:'POST',body:'{}'});assert.equal((await native({request:req(),env:{}})).status,503);assert.equal((await native({request:req(),env:{EGC_OPERATIONS_ENABLED:'true',EGC_OPERATIONS_PORTAL_SIGNING_SECRET:key}})).status,401);});
test('signed portal endpoint never accepts a write command or wrong workspace',async()=>{const env={EGC_OPERATIONS_ENABLED:'true',EGC_OPERATIONS_PORTAL_SIGNING_SECRET:key};for(const [body,workspace,status] of [[{command:'task.create'},'egc',400],[{command:'portal.job',jobId:'a'},'other',403]]){const c=claims();c.request.body=body;c.actor.workspace=workspace;const request=new Request('https://portal.test/api/operations-portal',{method:'POST',body:JSON.stringify({envelope:await signOperationsEnvelope(c,key)})});assert.equal((await native({request,env})).status,status);}});
test('same-origin checks reject absent or forged origins before touching session/storage',async()=>{for(const origin of ['', 'https://attacker.test']){const request=new Request('https://portal.test/api/operations',{method:'POST',headers:{Origin:origin,'Content-Type':'application/json'},body:'{}'});assert.equal(sameOrigin(request),false);assert.equal((await gateway({request,env:{}})).status,403);}assert.equal(sameOrigin(new Request('https://portal.test/api/operations',{headers:{Origin:'https://portal.test'}})),true);});
test('DST ambiguity is returned for review rather than assigned an invented instant',()=>{assert.equal(localInstant('2026-09-18','10:00'),'2026-09-18T16:00:00.000Z');assert.equal(localInstant('2026-11-01','01:30'),null);assert.equal(localInstant('2026-03-08','02:30'),null);assert.equal(localInstant('2026-09-31','10:00'),null);assert.equal(localInstant('2026-09-18','24:00'),null);});
test('calendar exhausts source pages, preserves actual IDs and excludes encrypted/metadata records',async()=>{const pages=[{documents:[doc('visit-a',{type:'walkthrough'}),doc('secure_secret',{recordType:'employee_hub_v2',sealedPayload:'never return'})],nextPageToken:'page2'},{documents:[doc('job-a',{sourceWalkthroughId:'visit-a'}),doc('_egc_lock',{recordType:'schedule_lock'})]}];let count=0;const r=await portalCalendar({},range,async(_env,url)=>{assert.ok(url.includes('mask.fieldPaths'));assert.ok(!url.includes('sealedPayload'));return response(pages[count++]);});assert.equal(count,2);assert.equal(r.total,2);assert.deepEqual(r.items.map(x=>x.id).sort(),['job-a','visit-a']);assert.equal(r.items.find(x=>x.id==='job-a').sourceWalkthroughId,'visit-a');assert.equal(r.authority,'employee_hub');assert.equal(JSON.stringify(r).includes('never return'),false);});
test('calendar does not invent a job association for a walkthrough',async()=>{const r=await portalCalendar({},range,async()=>response({documents:[doc('visit-a',{type:'walkthrough'})]}));assert.equal(r.items[0].jobId,null);assert.equal(r.items[0].sourceRevision,'2026-09-18T18:00:00Z');});
test('Hub calendar and exact job reads retain provider sync evidence and actual event dates',async()=>{const fields={customerId:'customer',projectId:'project',highlevelAppointmentId:'provider-event',highlevelCalendarId:'calendar',providerAppointmentStatus:'confirmed',syncStatus:'synced',syncedAt:'2026-09-18T17:00:00Z',createdAt:'2026-09-16T18:00:00Z',completedAt:'2026-09-18T18:00:00Z'};const fetcher=async(_env,url)=>response(String(url).includes('?')?{documents:[doc('visit-a',fields)]}:doc('visit-a',fields));const cal=await portalCalendar({},range,fetcher),detail=await portalJob({},'visit-a',fetcher);for(const row of [cal.items[0],detail.job]){assert.equal(row.highlevelAppointmentId,'provider-event');assert.equal(row.syncStatus,'synced');assert.equal(row.createdAt,fields.createdAt);assert.equal(row.completedAt,fields.completedAt);}assert.equal(cal.items[0].portalCustomerId,'customer');});
test('exact Hub job exposes explicit approval and completion timestamps for canonical reconciliation',async()=>{const fields={type:'cleanout',customerApproval:{status:'approved',approvedAt:'2026-09-16T17:00:00Z',amount:139},postJobChecklist:{completedAt:'2026-09-18T18:00:00Z'},updatedAt:'2026-09-19T18:00:00Z'};const detail=await portalJob({},'native-job',async()=>response(doc('native-job',fields)));assert.equal(detail.job.type,'job');assert.equal(detail.job.sourceType,'cleanout');assert.equal(detail.job.soldAt,'2026-09-16T17:00:00.000Z');assert.equal(detail.job.completedAt,'2026-09-18T18:00:00.000Z');assert.equal(detail.financials.quote.amountCents,13900);});
test('pagination, inclusive start and exclusive end are explicit',async()=>{const r=await portalCalendar({},{...range,limit:1},async()=>response({documents:[doc('a'),doc('b',{date:'2026-09-19'}),doc('c',{date:'2026-09-20'})]}));assert.equal(r.items.length,1);assert.equal(r.total,2);assert.equal(r.nextOffset,1);});
test('calendar preserves multi-day dispatch end times and includes intervals crossing the window start',async()=>{const r=await portalCalendar({},range,async(_env,url)=>{assert.ok(new URL(url).searchParams.getAll('mask.fieldPaths').includes('endDate'));return response({documents:[doc('spanning',{date:'2026-09-17',endDate:'2026-09-19',endTime:'16:00'})]});});assert.equal(r.total,1);assert.equal(r.items[0].localEndDate,'2026-09-19');assert.equal(r.items[0].endAt,'2026-09-19T22:00:00.000Z');assert.equal(r.items[0].timeNeedsReview,false);});
test('partial or stalled source reads fail instead of returning a false complete calendar',async()=>{await assert.rejects(portalCalendar({},range,async()=>new Response('{}',{status:503})),/portal_calendar_unavailable/);await assert.rejects(portalCalendar({},range,async()=>response({nextPageToken:'same'})),/pagination_stalled/);await assert.rejects(portalCalendar({},range,async()=>response({documents:{bad:true}})),/invalid_response/);});
test('missing schedule dates are explicit exceptions and invalid times remain visible',async()=>{const r=await portalCalendar({},range,async()=>response({documents:[doc('invalid-date',{date:'nonsense'}),doc('missing-time',{time:''})]}));assert.equal(r.coverage.complete,false);assert.equal(r.exceptions[0].recordId,'invalid-date');assert.equal(r.items[0].timeNeedsReview,true);});
test('exact job reads cannot leak vault records, select another job or trust a stored forged ID',async()=>{let fetches=0;for(const id of ['../other','secure_secret','_egc_lock'])await assert.rejects(portalJob({},id,async()=>{fetches++;return response({});}));assert.equal(fetches,0);const r=await portalJob({},'right',async()=>response(doc('right',{id:'forged',jobInstructions:'Keep everything',sealedPayload:'private',salesPassword:'private'})));assert.equal(r.job.id,'right');assert.equal(r.job.scope,'Keep everything');assert.equal(r.job.scopeApproval,'not_explicit_in_source');assert.equal(JSON.stringify(r).includes('private'),false);await assert.rejects(portalJob({},'right',async()=>response(doc('wrong'))),/not_found/);});
test('non-Denver or invalid date ranges are refused before provider access',async()=>{for(const extra of [{timeZone:'UTC'},{startDate:'2026-02-31'},{endDate:'2026-09-17'},{limit:0}])await assert.rejects(portalCalendar({},{...range,...extra},async()=>{throw new Error('must not fetch');}),e=>e.status===400);});
test('contact-scoped Hub evidence includes unscheduled accepted work and exact receipt provenance',async()=>{let count=0;const pages=[{documents:[doc('unscheduled',{type:'cleanout',highlevelContactId:'contact-a',date:'',time:'',customerApproval:{status:'approved',approvedAt:'2026-09-18T18:00:00Z',amount:139},payment:{verified:true,amount:139,lastAmount:139,lastReceivedAt:'2026-09-19T18:00:00Z',recordedBy:'owner',reference:'cash-139',method:'offline_or_processor'}})],nextPageToken:'next'},{documents:[doc('unrelated',{highlevelContactId:'contact-b'}),doc('test-row',{highlevelContactId:'contact-a',isTest:true}),doc('secure_secret',{highlevelContactId:'contact-a',recordType:'employee_hub_v2',sealedPayload:'never expose'})]}];const r=await portalEvidence({},{contactProviderIds:['contact-a']},async()=>response(pages[count++]));assert.equal(count,2);assert.equal(r.coverage.complete,true);assert.equal(r.records.length,1);assert.equal(r.records[0].id,'unscheduled');assert.equal(r.records[0].startAt,null);assert.equal(r.records[0].soldAt,'2026-09-18T18:00:00.000Z');assert.equal(r.records[0].financials.staffPayments[0].reference,'cash-139');assert.equal(JSON.stringify(r).includes('never expose'),false);});
test('Hub evidence fails on incomplete scans and invalid contact requests instead of false empty evidence',async()=>{for(const contactProviderIds of [[],['../wrong'],Array(501).fill('contact')])await assert.rejects(portalEvidence({},{contactProviderIds},async()=>{throw new Error('must not fetch')}),e=>e.status===400);await assert.rejects(portalEvidence({},{contactProviderIds:['contact']},async()=>response({nextPageToken:'stalled'})),/pagination_stalled/);await assert.rejects(portalEvidence({},{contactProviderIds:['contact']},async()=>new Response('{}',{status:503})),/evidence_unavailable/);});

test('native evidence exposes original kind, exact scope, supporting notes and full scheduled interval without credential fields',async()=>{
  const fields={type:'walkthrough',highlevelContactId:'contact-a',customerId:'customer-a',projectId:'project-a',date:'2026-09-27',endDate:'2026-09-28',time:'09:30',endTime:'14:30',createdAt:'2026-09-17T22:54:46Z',jobInstructions:'Move garage items to room',scope:{relocate:['garage','workout items'],apiKey:'private'},operationalScope:{text:'Rotate tool cabinet',updatedBy:'owner',approvalKind:'staff_operational_instructions'},serviceType:'Garage organization',notes:'Estimate was separately booked',operationNotes:[{id:'note-a',createdAt:'2026-09-18T18:00:00Z',body:'Reviewed execution scope',actorId:'owner'}],sealedPayload:'private',wallet:{secret:'private'},payment:{clientSecret:'private'}};
  const result=await portalEvidence({},{contactProviderIds:['contact-a']},async(_env,url)=>{
    const mask=new URL(url).searchParams.getAll('mask.fieldPaths');for(const field of ['scope','jobInstructions','operationalScope','serviceType','notes','operationNotes','endDate'])assert.ok(mask.includes(field));for(const field of ['sealedPayload','wallet','salesPassword'])assert.ok(!mask.includes(field));
    return response({documents:[doc('visit-a',fields),doc('job-a',{type:'cleanout',highlevelContactId:'contact-a',sourceWalkthroughId:'visit-a'}),doc('unrelated',{highlevelContactId:'other'})]});
  });
  assert.equal(result.total,2);assert.equal(result.truncated,false);const visit=result.records.find(r=>r.id==='visit-a');assert.equal(visit.kind,'walkthrough');assert.equal(visit.sourceType,'walkthrough');assert.equal(visit.createdAt,fields.createdAt);assert.equal(visit.endAt,'2026-09-28T20:30:00.000Z');assert.deepEqual(visit.scope,{relocate:['garage','workout items']});assert.equal(visit.operationNotes[0].body,'Reviewed execution scope');assert.equal(visit.operationalScope.text,'Rotate tool cabinet');assert.equal(visit.financials.eligible,false);assert.equal(JSON.stringify(result).includes('private'),false);
});

test('oversized operational content reports its field truncation separately from exact record coverage',async()=>{
  const result=await portalEvidence({},{contactProviderIds:['contact-a']},async()=>response({documents:[doc('job-a',{highlevelContactId:'contact-a',jobInstructions:'x'.repeat(20001),operationNotes:Array.from({length:101},(_,i)=>({id:'note-'+i,body:'scope'}))})]}));
  assert.equal(result.coverage.complete,true);assert.equal(result.records[0].jobInstructions.length,20000);assert.equal(result.records[0].operationNotes.length,100);assert.deepEqual(result.records[0].contentCoverage,{complete:false,truncatedFields:['jobInstructions','operationNotes']});
});

test('native evidence retains the original booking time persisted by adoption rather than import time',async()=>{
  const original='2026-09-17T22:54:50Z',result=await portalEvidence({},{contactProviderIds:['contact-a']},async(_env,url)=>{
    assert.ok(new URL(url).searchParams.getAll('mask.fieldPaths').includes('adoptionOriginalBookingAt'));
    return response({documents:[doc('adopted',{highlevelContactId:'contact-a',createdAt:'2026-09-22T08:00:00Z',adoptionOriginalBookingAt:original,originalBookingAt:'2026-09-22T08:00:00Z'})]});
  });assert.equal(result.records[0].originalBookingAt,original);
});
