import test from 'node:test';
import assert from 'node:assert/strict';
import {applyRecordingApproval,resolveRecordingIdentity} from '../functions/_lib/operations-recording-approval.js';
import {onRequestPost as gateway} from '../functions/api/operations-recordings.js';
import {encodeFirestoreFields} from '../functions/_lib/firestore-job.js';
const recordingId='10000000-0000-4000-a000-000000000001',requestId='20000000-0000-4000-a000-000000000002';
const actor={id:'synthetic-owner',role:'owner',kind:'human',workspace:'egc'};
const command={recordingId,requestId,fingerprint:'a'.repeat(64),portalJobId:'visit-1',portalVisitId:'visit-1',portalCustomerId:'customer-1',portalProjectId:null,expectedRevision:'revision-1',extraction:{itemsKeep:['Bike'],pricingNotes:[],proposedActions:[]}};
function fixture(){const docs=new Map([['jobs/visit-1',{type:'walkthrough',customerId:'customer-1',priceQuoted:1900,acceptance:{acceptedAt:'original'}}],['customers/customer-1',{name:'Synthetic'}]]);const writes=[];let conflict=false;
const fetcher=async(_env,url,options={})=>{const path=String(url).split('/documents/')[1];if(String(url).endsWith(':commit')){const body=JSON.parse(options.body);writes.push(body);if(conflict)return Response.json({error:'conflict'},{status:409});for(const w of body.writes){assert.ok(w.currentDocument);if(w.currentDocument.exists===false)docs.set(w.update.name.split('/documents/')[1],Object.fromEntries(Object.entries(w.update.fields).map(([k,v])=>[k,v.stringValue??v.mapValue??null])));}return Response.json({writeResults:[]});}const value=docs.get(path);return value?Response.json({name:'projects/test/databases/(default)/documents/'+path,updateTime:'revision-1',fields:encodeFirestoreFields(value)}):Response.json({}, {status:404});};return{docs,writes,fetcher,setConflict:()=>{conflict=true;}};}
test('recording source identity is exact and project absence stays explicit',async()=>{const f=fixture();const result=await resolveRecordingIdentity({},'visit-1',f.fetcher);assert.equal(result.portalVisitId,'visit-1');assert.equal(result.portalCustomerId,'customer-1');assert.equal(result.portalProjectId,null);await assert.rejects(resolveRecordingIdentity({},'secure_secret',f.fetcher));});
test('missing customer or mismatched visit association cannot be inferred',async()=>{const f=fixture();delete f.docs.get('jobs/visit-1').customerId;await assert.rejects(resolveRecordingIdentity({},'visit-1',f.fetcher),/customer_link_missing/);f.docs.set('jobs/job-1',{type:'job',customerId:'customer-1',sourceWalkthroughId:'visit-1'});f.docs.set('jobs/visit-1',{type:'walkthrough',customerId:'other-customer'});await assert.rejects(resolveRecordingIdentity({},'job-1',f.fetcher),/visit_job_mismatch/);});
test('staff review is atomic CAS plus unique receipt and does not overwrite signed price or scope',async()=>{const f=fixture();const result=await applyRecordingApproval({},command,actor,f.fetcher);assert.equal(result.ok,true);const writes=f.writes[0].writes;assert.equal(writes.length,2);assert.deepEqual(writes[0].currentDocument,{updateTime:'revision-1'});assert.deepEqual(writes[1].currentDocument,{exists:false});assert.deepEqual(writes[0].updateMask.fieldPaths,['reviewedWalkthroughScope','updatedAt']);assert.equal(writes[0].update.fields.priceQuoted,undefined);assert.equal(writes[0].update.fields.acceptance,undefined);});
test('known accepted approval replays without another write; changed payload cannot reuse it',async()=>{const f=fixture();f.docs.set('operation_recording_approvals/'+recordingId,{fingerprint:command.fingerprint,portalJobId:command.portalJobId,appliedAt:'saved'});assert.equal((await applyRecordingApproval({},command,actor,f.fetcher)).alreadyApplied,true);assert.equal(f.writes.length,0);await assert.rejects(applyRecordingApproval({},{...command,fingerprint:'b'.repeat(64)},actor,f.fetcher),/approval_conflict/);});
test('stale source and concurrent CAS conflicts fail without a guessed retry',async()=>{const f=fixture();await assert.rejects(applyRecordingApproval({},{...command,expectedRevision:'stale'},actor,f.fetcher),/source_revision_conflict/);assert.equal(f.writes.length,0);f.setConflict();await assert.rejects(applyRecordingApproval({},command,actor,f.fetcher),/source_revision_conflict/);assert.equal(f.writes.length,1);});
test('integration or sales identity cannot approve and gateway rejects cross-origin writes',async()=>{for(const denied of [{...actor,role:'sales'},{...actor,role:'integration',kind:'integration'}])await assert.rejects(applyRecordingApproval({},command,denied,fixture().fetcher),e=>e.status===403);const response=await gateway({request:new Request('https://hub.test/api/operations-recordings',{method:'POST',headers:{Origin:'https://attacker.test'},body:'{}'}),env:{}});assert.equal(response.status,403);});
