import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { createStaffInvitationService,staffTokenHash,namedStaffRole } from '../functions/_lib/staff-invitation-service.js';
import { handleStaffSetup } from '../functions/api/staff-setup.js';
import { staffAllowed,staffCanAccess } from '../functions/_lib/business-hub-core.js';
async function setup(){
 let clock=Date.UTC(2026,8,23,18),counter=0;const rows=new Map(),token='a'.repeat(43),m={id:'isolated-demo',username:'demo.sales',firstName:'Demo',lastName:'Sales',email:'demo@example.invalid',role:'sales',approvedBy:'zacb',tokenHash:await staffTokenHash(token),createdAt:new Date(clock).toISOString(),expiresAt:new Date(clock+48*3600000).toISOString()};
 const store={read:async u=>structuredClone(rows.get(u)||null),list:async()=>[...rows.values()].map(r=>r.account),create:async a=>{if(rows.has(a.username))throw Error('That username is already registered');rows.set(a.username,{account:structuredClone(a),version:String(++counter)});},password:async()=>({passwordHash:'isolated-hash',passwordSalt:'isolated-salt'})};
 const service=createStaffInvitationService({store,manifests:[m],now:()=>clock});return {service,store,rows,m,token,invite:m.id+'.'+token,advance:ms=>clock+=ms};
}
const credentials={email:'demo@example.invalid',password:'isolated-test-password-2026',confirmPassword:'isolated-test-password-2026'};
test('inspection is read-only and reveals only the invitation-bound identity',async()=>{const h=await setup();for(let i=0;i<3;i++){const item=await h.service.inspect(h.invite);assert.equal(item.username,h.m.username);assert.equal(item.status,'invited');assert.equal(item.tokenHash,undefined);}assert.equal(h.rows.size,0);});
test('activation creates one restricted account and consumes the link once',async()=>{const h=await setup(),r=await h.service.redeem(h.invite,credentials);assert.equal(r.loginUrl,'/business-hub?staff=1');assert.equal(r.activated,true);const a=h.rows.get(h.m.username).account;assert.equal(a.status,'approved');assert.equal(a.businessAccess,false);assert.equal(a.invitation.tokenHash,undefined);assert.equal(namedStaffRole(a),'sales');await assert.rejects(()=>h.service.redeem(h.invite,credentials),e=>e.status===410);await assert.rejects(()=>h.service.inspect(h.invite),e=>e.status===410);});
test('two browsers racing to redeem have exactly one winner',async()=>{const h=await setup(),r=await Promise.allSettled([h.service.redeem(h.invite,credentials),h.service.redeem(h.invite,credentials)]);assert.equal(r.filter(x=>x.status==='fulfilled').length,1);assert.equal(r.filter(x=>x.status==='rejected').length,1);assert.equal(h.rows.size,1);});
test('wrong, malformed and expired tokens never create an account',async()=>{const h=await setup();for(const token of ['invalid',h.m.id+'.'+'b'.repeat(43),h.invite+'.extra'])await assert.rejects(()=>h.service.inspect(token),e=>e.status===410);h.advance(49*3600000);await assert.rejects(()=>h.service.redeem(h.invite,credentials),e=>e.status===410);assert.equal(h.rows.size,0);});
test('wrong email and invalid passwords do not consume the invitation',async()=>{const h=await setup();for(const input of [{...credentials,email:'other@example.invalid'},{...credentials,password:'short'},{...credentials,confirmPassword:'different'}])await assert.rejects(()=>h.service.redeem(h.invite,input),e=>e.status===400);assert.equal((await h.service.inspect(h.invite)).status,'invited');assert.equal(h.rows.size,0);});
test('existing identities and configured staff are never replaced',async()=>{const h=await setup();h.rows.set('old.name',{account:{username:'old.name',email:h.m.email,status:'approved'},version:'old'});await assert.rejects(()=>h.service.redeem(h.invite,credentials),e=>e.status===409);assert.equal(h.rows.size,1);const s=createStaffInvitationService({store:h.store,manifests:[h.m],staticUsernameExists:()=>true,now:()=>Date.parse(h.m.createdAt)});await assert.rejects(()=>s.inspect(h.invite),e=>e.status===409);});
test('forged role fields cannot grant manager or sales access',()=>{for(const a of [{role:'sales'},{role:'owner'},{role:'sales',username:'demo',email:'demo@example.invalid',invitation:{kind:'named_staff_v1',approvedBy:'zacb',username:'other',email:'demo@example.invalid',consumedAt:'today'}}])assert.equal(namedStaffRole(a),'crew');});
test('HTTP rejects public provisioning, identity overrides, CSRF and oversized bodies',async()=>{const h=await setup();const request=(p,extra={})=>new Request('https://easygaragecleaning.com/api/staff-setup',{method:'POST',headers:{Origin:'https://easygaragecleaning.com','X-EGC-Staff-Setup':'1','Content-Type':'application/json',...extra},body:JSON.stringify(p)});for(const p of [{action:'provision',invitationId:h.m.id},{action:'redeem',invite:h.invite,...credentials,role:'owner'}])assert.equal((await handleStaffSetup(request(p),h.service)).status,400);assert.equal((await handleStaffSetup(request({action:'inspect',invite:h.invite},{Origin:'https://evil.invalid'}),h.service)).status,403);assert.equal((await handleStaffSetup(request({action:'inspect',invite:'a'.repeat(5000)}),h.service)).status,413);const get=await handleStaffSetup(new Request('https://easygaragecleaning.com/api/staff-setup'),h.service);assert.equal(get.headers.get('Cache-Control'),'no-store');assert.equal(h.rows.size,0);});
// The real account crypto and session code run against isolated Firestore mocks.
function encryptedAdapter(){
 const documents=new Map();let version=0;const env={HUB_SESSION_SECRET:'isolated-session-secret-'.repeat(3),EMPLOYEE_DATA_SECRET:'isolated-vault-secret-'.repeat(3)};
 const fire=async(e,input,options={})=>{const u=new URL(input),method=options.method||'GET';if(u.pathname.endsWith(':runQuery'))return Response.json(documents.size?[...documents.values()].map(document=>({document})):[{readTime:'2026-09-23T18:00:00Z'}]);const key=decodeURIComponent(u.pathname.split('/').pop()),prior=documents.get(key);if(method==='GET')return prior?Response.json(prior):new Response('',{status:404});if(method==='PATCH'){if(u.searchParams.get('currentDocument.exists')==='false'&&prior||u.searchParams.has('currentDocument.updateTime')&&prior?.updateTime!==u.searchParams.get('currentDocument.updateTime'))return new Response('',{status:409});const doc={...JSON.parse(options.body),name:'projects/egcw-1ec83/databases/(default)/documents/jobs/'+key,updateTime:'revision-'+(++version)};documents.set(key,doc);return Response.json(doc);}throw Error('Unexpected method');};
 const source=readFileSync(new URL('../functions/_lib/employee-accounts.js',import.meta.url),'utf8').replace(/^import .*;\n/gm,'').replace(/export /g,'');
 const account=new Function('firestoreFetch','firebaseServiceAccountConfigured','employeeVaultSecret','employeeVaultReadOnly','namedStaffRole',source+'\nreturn {employeeInvitationStore,authenticateEmployeeAccount,getEmployeeSessionProfile,reviewEmployeeApplication,listEmployeeApplications};')(fire,()=>true,e=>e.EMPLOYEE_DATA_SECRET,()=>false,namedStaffRole);
 const hubSource=readFileSync(new URL('../functions/_lib/hub-session.js',import.meta.url),'utf8').replace(/^import .*;\n/gm,'').replace(/export /g,'');
 const hub=new Function('authenticateEmployeeAccount','getEmployeeSessionProfile','pbkdf2','sha256',hubSource+'\nreturn {createHubSessionToken,verifyHubSessionToken,authenticateHubCredential};')(account.authenticateEmployeeAccount,account.getEmployeeSessionProfile,()=>{throw Error('No fallback expected');},null);
 return {env,documents,account,hub};
}
test('real encrypted activation works with normal password login, signed restoration and revocation',async()=>{const h=await setup(),a=encryptedAdapter(),service=createStaffInvitationService({store:a.account.employeeInvitationStore(a.env),manifests:[h.m],now:()=>Date.parse(h.m.createdAt)});await service.redeem(h.invite,credentials);const profile=await a.hub.authenticateHubCredential(a.env,h.m.username,credentials.password);assert.equal(profile.role,'sales');assert.equal(profile.businessAccess,false);assert.equal(staffAllowed(profile),true);assert.equal(staffCanAccess(profile,{ownerStaff:'other'}),false);assert.equal(await a.hub.authenticateHubCredential(a.env,h.m.username,'wrong-password'),null);const token=await a.hub.createHubSessionToken(a.env,h.m.username,Date.now(),profile);const restored=await a.hub.verifyHubSessionToken(a.env,token);assert.equal(restored.role,'sales');assert.equal(restored.businessAccess,false);const raw=JSON.stringify([...a.documents.values()]);assert.equal(raw.includes(credentials.password),false);assert.equal(raw.includes(h.token),false);assert.equal(raw.includes(h.m.email),false);const listed=await a.account.listEmployeeApplications(a.env);assert.equal(listed[0].invitation,undefined);await a.account.reviewEmployeeApplication(a.env,h.m.username,'rejected','zacb');assert.equal(await a.hub.verifyHubSessionToken(a.env,token),null);await assert.rejects(()=>service.redeem(h.invite,credentials),e=>e.status===410);});
test('real encrypted create-only storage permits exactly one concurrent activation',async()=>{const h=await setup(),a=encryptedAdapter(),service=createStaffInvitationService({store:a.account.employeeInvitationStore(a.env),manifests:[h.m],now:()=>Date.parse(h.m.createdAt)});const r=await Promise.allSettled([service.redeem(h.invite,credentials),service.redeem(h.invite,credentials)]);assert.equal(r.filter(x=>x.status==='fulfilled').length,1);assert.equal(a.documents.size,1);});
test('setup scrubs token fragments and never sends them to trackers or browser storage',()=>{const script=readFileSync(new URL('../staff-setup.js',import.meta.url),'utf8');assert.match(script,/history.replaceState/);assert.doesNotMatch(script,/localStorage|sessionStorage|analytics|googletag|facebook/);const page=readFileSync(new URL('../functions/staff-setup.js',import.meta.url),'utf8');assert.match(page,/work in progress/);assert.match(page,/no-referrer/);});
