import {afterEach,beforeEach,describe,expect,it,vi} from 'vitest';
import type {Actor,Command} from '@egc/operations';
import {reconcileExistingBookingAdoption,verifyBookingAdoption,type AdoptionCandidate} from './booking-adoption.js';
const now=new Date('2026-09-22T07:30:00Z'),until=new Date('2026-10-06T07:30:00Z'),startAt='2026-09-23T20:15:00.000Z',endAt='2026-09-23T20:45:00.000Z';
const contactId='aa111111-1111-4111-8111-111111111111',jobId='bb111111-1111-4111-8111-111111111111',appointmentId='cc111111-1111-4111-8111-111111111111';
const event=()=>({id:'provider-appointment',contactId:'provider-contact',locationId:'location',calendarId:'walkthrough-calendar',appointmentStatus:'confirmed',title:'EGC Free Walkthrough',startTime:startAt,endTime:endAt,address:'100 Synthetic Street',dateAdded:'2026-09-21T12:00:00Z'});
function candidate(local=false):AdoptionCandidate{return {source:local?'local_job':'ghl_appointment',sourceId:local?jobId:'provider-appointment',contact:{id:contactId,provider:'ghl',providerId:'provider-contact',tags:[],raw:{}},lead:{id:'lead',doNotContact:false},snapshot:{state:'WALKTHROUGH_VERBALLY_BOOKED',pipelineDisposition:'active'},appointments:local?[]:[{id:appointmentId,providerId:'provider-appointment',calendarId:'walkthrough-calendar',appointmentStartAt:startAt,appointmentEndAt:endAt,appointmentCreatedAt:'2026-09-21T12:00:00Z'}],jobs:[{id:jobId,contactId,appointmentId:local?null:appointmentId,serviceType:'Free garage walkthrough',status:'scheduled',scheduledAt:startAt,estimatedLaborHours:'0.50',serviceAddress:'100 Synthetic Street',createdAt:'2026-09-21T12:01:00Z'}],events:local?[{eventId:'egcev_source',eventType:'walkthrough_verbally_booked',occurredAt:'2026-09-21T12:00:00Z',confidence:.99,humanReviewNeeded:false,details:{scheduledAt:startAt,occurredAtVerified:true},evidence:[{sourceType:'message',sourceRecordId:'customer-sms',excerpt:'Tuesday at 2:15 works. Address is 100 Synthetic Street.',humanReviewNeeded:false}]}]:[],evidence:local?[{sourceType:'message',sourceRecordId:'customer-sms',status:'complete'}]:[],assertions:[]};}
function provider(local=false){return {locationId:'location',getContact:vi.fn(async()=>({contact:{id:'provider-contact',locationId:'location',name:'Synthetic Customer',phone:'+15555550199',tags:[] as string[]}})),getAppointment:vi.fn(async()=>({event:event()})),getCalendars:vi.fn(async()=>({calendars:[{id:'walkthrough-calendar',name:'EGC Free Walkthrough'}]})),getCalendarEvents:vi.fn(async()=>({events:local?[]:[event()]}))};}
function context(p=provider()){return {provider:p,calendars:[{id:'walkthrough-calendar',name:'EGC Free Walkthrough'}],visits:[],now,until,env:{}};}
function store(c=candidate()){const saved=new Map<string,Record<string,unknown>>();return {saved,load:vi.fn(async()=>({candidates:[structuredClone(c)],complete:true})),get:vi.fn(async(key:string)=>saved.get(key)??null),save:vi.fn(async(key:string,value:Record<string,unknown>)=>{saved.set(key,value);})};}
function portal(){let proof:Extract<Command,{command:'schedule.adopt'}>['proof']|undefined;return vi.fn(async(_actor:Actor,command:Command):Promise<Record<string,unknown>>=>{
 if(command.command==='schedule.adopt'){proof=command.proof;return{ok:true,authority:'employee_hub',jobId:'hub-visit',portalVisitId:'hub-visit',portalCustomerId:'hub-customer',contactProviderId:proof.contactProviderId,kind:proof.kind,startAt:proof.startAt,endAt:proof.endAt,source:{type:proof.source,id:proof.sourceId,revision:proof.sourceRevision},adopted:true,replayed:false,duplicate:false};}
 if(command.command==='portal.job')return{authority:'employee_hub',job:{id:'hub-visit',highlevelContactId:'provider-contact',kind:'walkthrough',status:'scheduled',address:'100 Synthetic Street',highlevelAppointmentId:'provider-appointment',highlevelCalendarId:'walkthrough-calendar',startAt,endAt,normalizedLocalJobId:jobId,normalizedLocalAppointmentId:appointmentId}};
 throw new Error('unexpected write');
 });}
beforeEach(()=>{vi.useFakeTimers();vi.setSystemTime(now);vi.stubGlobal('fetch',vi.fn().mockRejectedValue(new Error('No external calls in test')));});afterEach(()=>{vi.useRealTimers();vi.unstubAllGlobals();});
describe('verified existing booking adoption',()=>{
 it('defaults to dry run, exact provider reads and original booking time without customer writes',async()=>{const s=store(),p=provider(),hub=portal();const result=await reconcileExistingBookingAdoption(hub,{env:{},store:s,provider:p,visits:[],portalComplete:true,providerComplete:true});expect(result).toMatchObject({dryRun:true,counts:{ready:1,adopted:0},plans:[{sourceId:'provider-appointment',startAt,originalBookingAt:'2026-09-21T12:00:00.000Z',localJobId:jobId,normalizedLocalAppointmentId:appointmentId}]});expect(p.getContact).toHaveBeenCalledWith('provider-contact');expect(p.getAppointment).toHaveBeenCalledWith('provider-appointment');expect(hub).not.toHaveBeenCalled();expect(s.save).not.toHaveBeenCalled();expect(fetch).not.toHaveBeenCalled();expect(JSON.stringify(result)).not.toContain('+15555550199');});
 it.each(['LOST','DO_NOT_CONTACT','JOB_COMPLETED','CASH_COLLECTED'])('rejects terminal %s state before any provider call',async state=>{const c=candidate(),p=provider();c.snapshot.state=state;expect(await verifyBookingAdoption(c,context(p))).toMatchObject({status:'blocked',reasons:['customer_excluded_or_terminal']});expect(p.getContact).not.toHaveBeenCalled();});
 it.each(['lost','walkthrough_negative_outcome','job_completed','revenue_collected'])('respects durable user-confirmed %s despite active provider record',async field=>{const c=candidate();c.assertions=[{field,value:true,status:'pending_reconciliation'}];expect(await verifyBookingAdoption(c,context())).toMatchObject({status:'blocked',reasons:['terminal_user_confirmed_outcome']});});
 it.each([{field:'operational_state',value:'CASH_COLLECTED'},{field:'walkthrough.outcome',value:'went_badly'},{field:'walkthrough_outcome',value:'negative'},{field:'collected_revenue_cents',value:72500},{field:'walkthrough_completed',value:true}])('honors exact durable assertion aliases before the canonical snapshot catches up: %j',async assertion=>{const c=candidate(),p=provider();c.assertions=[{...assertion,status:'pending_reconciliation'}];expect(await verifyBookingAdoption(c,context(p))).toMatchObject({status:'blocked',reasons:['terminal_user_confirmed_outcome']});expect(p.getContact).not.toHaveBeenCalled();});
 it('rejects DNC, internal/vendor, incomplete identity and fresh provider DNC',async()=>{for(const tags of [['dnc'],['test'],['vendor']]){const c=candidate();c.contact.tags=tags;expect((await verifyBookingAdoption(c,context())).status).toBe('blocked');}const c=candidate();c.snapshot={};expect((await verifyBookingAdoption(c,context())).reasons).toEqual(['canonical_customer_identity_missing']);const p=provider();p.getContact.mockResolvedValue({contact:{id:'provider-contact',locationId:'location',name:'Customer',phone:'',tags:['dnc']}});expect((await verifyBookingAdoption(candidate(),context(p))).reasons).toEqual(['customer_excluded_or_terminal']);});
 it('rejects wrong contact/location and appointment customer identity',async()=>{const p=provider();p.getContact.mockResolvedValue({contact:{id:'wrong',locationId:'location',name:'Customer',phone:'',tags:[]}});expect((await verifyBookingAdoption(candidate(),context(p))).reasons).toEqual(['provider_contact_identity_mismatch']);p.getContact.mockResolvedValue({contact:{id:'provider-contact',locationId:'foreign',name:'Customer',phone:'',tags:[]}});expect((await verifyBookingAdoption(candidate(),context(p))).status).toBe('blocked');const p2=provider();p2.getAppointment.mockResolvedValue({event:{...event(),contactId:'wrong'}});expect((await verifyBookingAdoption(candidate(),context(p2))).reasons).toEqual(['provider_appointment_identity_mismatch']);});
 it('rejects cancelled, moved, missing address/end and paid-job purpose mismatch',async()=>{for(const patch of [{appointmentStatus:'cancelled'},{startTime:'2026-09-24T20:15:00Z'},{endTime:''}]){const p=provider();p.getAppointment.mockResolvedValue({event:{...event(),...patch}});expect((await verifyBookingAdoption(candidate(),context(p))).status).toBe('blocked');}const c=candidate();c.jobs[0]!.serviceType='Garage organization service';expect((await verifyBookingAdoption(c,context())).reasons).toEqual(['local_provider_purpose_or_schedule_conflict']);const noAddress=candidate();noAddress.jobs[0]!.serviceAddress=null;const p=provider();p.getAppointment.mockResolvedValue({event:{...event(),address:''}});expect((await verifyBookingAdoption(noAddress,context(p))).reasons).toEqual(['source_schedule_address_or_purpose_incomplete']);});
 it('refuses duplicates and incomplete provider calendar scans',async()=>{for(const list of [{events:[event(),{...event(),id:'duplicate'}]},{events:[event()],nextPageToken:'more'},{events:[{id:'incomplete'}]},{events:[]}]){const p=provider();p.getCalendarEvents.mockResolvedValue(list as Awaited<ReturnType<typeof p.getCalendarEvents>>);expect((await verifyBookingAdoption(candidate(),context(p))).status).toBe('blocked');}});
 it('does not invent a local-only booking from a scheduled job fallback',async()=>{const c=candidate(true);c.events[0]!.evidence=[{sourceType:'job',sourceRecordId:jobId,excerpt:'Local walkthrough scheduled'}];expect((await verifyBookingAdoption(c,{...context(provider(true)),env:{EGC_BOOKING_ADOPT_LOCAL_JOB_IDS:jobId}})).reasons).toEqual(['local_job_missing_content_backed_commitment']);});
 it('requires completed content extraction and the exact local job allowlist',async()=>{const c=candidate(true),p=provider(true);expect((await verifyBookingAdoption(c,context(p))).reasons).toEqual(['local_job_requires_reviewed_allowlist']);c.evidence[0]!.status='partial';expect((await verifyBookingAdoption(c,{...context(p),env:{EGC_BOOKING_ADOPT_LOCAL_JOB_IDS:jobId}})).reasons).toEqual(['local_job_missing_content_backed_commitment']);});
 it('verifies local-only content and schedule without fabricating a provider appointment or booking date',async()=>{const c=candidate(true);c.events[0]!.details={occurredAtVerified:false};const result=await verifyBookingAdoption(c,{...context(provider(true)),env:{EGC_BOOKING_ADOPT_LOCAL_JOB_IDS:jobId}});expect(result).toMatchObject({status:'ready',proof:{source:'local_job',localJobId:jobId,providerAppointmentId:null,providerCalendarId:null,providerStatus:null,originalBookingAt:null,sourceCreatedAt:'2026-09-21T12:01:00.000Z',startAt,endAt}});});
 it('rejects a newly present provider booking for a local-only proposal',async()=>{const r=await verifyBookingAdoption(candidate(true),{...context(provider()),env:{EGC_BOOKING_ADOPT_LOCAL_JOB_IDS:jobId}});expect(r.reasons).toEqual(['duplicate_or_unmirrored_provider_booking']);});
 it('checks unknown-purpose calendars for duplicate bookings too',async()=>{const p=provider(true);p.getCalendarEvents.mockResolvedValueOnce({events:[]}).mockResolvedValueOnce({events:[{...event(),calendarId:'misc'}]});const ctx={...context(p),calendars:[...context(p).calendars,{id:'misc',name:'Other appointments'}],env:{EGC_BOOKING_ADOPT_LOCAL_JOB_IDS:jobId}};expect((await verifyBookingAdoption(candidate(true),ctx)).reasons).toEqual(['duplicate_or_unmirrored_provider_booking']);expect(p.getCalendarEvents).toHaveBeenCalledTimes(2);});
 it('preserves unknown provider booking creation time without substituting mirror import time',async()=>{const c=candidate();c.appointments[0]!.appointmentCreatedAt=null;c.appointments[0]!.createdAt=now;const p=provider();p.getAppointment.mockResolvedValue({event:{...event(),dateAdded:''}});expect(await verifyBookingAdoption(c,context(p))).toMatchObject({status:'ready',proof:{originalBookingAt:null,sourceCreatedAt:null}});});
 it('recognizes an exact existing Hub appointment and rejects cross-customer binding',async()=>{const visit={id:'hub-existing',kind:'walkthrough' as const,status:'scheduled',highlevelContactId:'provider-contact',startAt,endAt,address:'100 Synthetic Street',highlevelAppointmentId:'provider-appointment'};expect(await verifyBookingAdoption(candidate(),{...context(),visits:[visit]})).toMatchObject({status:'already_in_hub',portalVisitId:'hub-existing'});expect((await verifyBookingAdoption(candidate(),{...context(),visits:[{...visit,highlevelContactId:'wrong'}]})).reasons).toEqual(['hub_source_binding_conflict']);});
 it('blocks any write with incomplete Hub/provider coverage while exposing the verified dry-run source',async()=>{for(const coverage of [{portalComplete:false,providerComplete:true},{portalComplete:true,providerComplete:false}]){const hub=portal(),s=store();const r=await reconcileExistingBookingAdoption(hub,{...coverage,env:{EGC_BOOKING_ADOPT_EXISTING:'true'},store:s,provider:provider(),visits:[]});expect(r.counts.blocked).toBe(1);expect(hub).not.toHaveBeenCalled();expect(s.save).not.toHaveBeenCalled();}});
 it('rechecks provider and current customer state before sending a signed internal adoption',async()=>{const s=store(),p=provider(),hub=portal();const r=await reconcileExistingBookingAdoption(hub,{env:{EGC_BOOKING_ADOPT_EXISTING:'true'},store:s,provider:p,visits:[],portalComplete:true,providerComplete:true});expect(r.counts.adopted).toBe(1);expect(s.load).toHaveBeenCalledTimes(2);expect(p.getContact).toHaveBeenCalledTimes(2);expect(p.getAppointment).toHaveBeenCalledTimes(2);expect(hub).toHaveBeenCalledWith({id:'booking-adoption-worker',kind:'integration',role:'integration',workspace:'egc'},expect.objectContaining({command:'schedule.adopt',requestId:expect.stringMatching(/^[a-f0-9-]{36}$/),proof:expect.objectContaining({sourceId:'provider-appointment',originalBookingAt:'2026-09-21T12:00:00.000Z'})}));expect([...s.saved.values()][0]).toMatchObject({phase:'adopted',localJobId:jobId,normalizedLocalAppointmentId:appointmentId});});
 it('blocks state changes between plan and execution',async()=>{const s=store(),newState=candidate();newState.assertions=[{field:'job_completed',value:true}];s.load.mockResolvedValueOnce({candidates:[candidate()],complete:true}).mockResolvedValueOnce({candidates:[newState],complete:true});const hub=portal(),r=await reconcileExistingBookingAdoption(hub,{env:{EGC_BOOKING_ADOPT_EXISTING:'true'},store:s,provider:provider(),visits:[],portalComplete:true,providerComplete:true});expect(r.plans[0]).toMatchObject({status:'failed',reasons:['adoption_source_changed']});expect(hub).not.toHaveBeenCalled();});
 it('reuses a stable request after an ambiguous Hub response and reads a durable accepted mapping on replay',async()=>{const s=store(),p=provider(),hub=portal(),calls:string[]=[];hub.mockImplementationOnce(async(_actor,command)=>{if(command.command==='schedule.adopt')calls.push(command.requestId);throw new Error('private network response');});const options={env:{EGC_BOOKING_ADOPT_EXISTING:'true'},store:s,provider:p,visits:[],portalComplete:true,providerComplete:true};expect((await reconcileExistingBookingAdoption(hub,options)).counts.failed).toBe(1);expect([...s.saved.values()][0]?.phase).toBe('pending');expect((await reconcileExistingBookingAdoption(hub,options)).counts.adopted).toBe(1);const writes=hub.mock.calls.filter(([,c])=>c.command==='schedule.adopt');expect(writes).toHaveLength(2);expect(writes[1]?.[1]).toMatchObject({requestId:calls[0]});expect((await reconcileExistingBookingAdoption(hub,options)).counts.already_in_hub).toBe(1);expect(hub.mock.calls.filter(([,c])=>c.command==='schedule.adopt')).toHaveLength(2);});
 it('does not persist an accepted mapping for a wrong-customer receipt',async()=>{const hub=portal();hub.mockResolvedValueOnce({ok:true,authority:'employee_hub',jobId:'wrong',portalVisitId:'wrong',contactProviderId:'different'});const s=store(),r=await reconcileExistingBookingAdoption(hub,{env:{EGC_BOOKING_ADOPT_EXISTING:'true'},store:s,provider:provider(),visits:[],portalComplete:true,providerComplete:true});expect(r.plans[0]?.reasons).toEqual(['adoption_receipt_identity_mismatch']);expect([...s.saved.values()][0]?.phase).toBe('pending');});
 it('leaves mapping pending when exact Hub readback has a different schedule or local identity',async()=>{const real=portal(),hub=vi.fn(async(a:Actor,c:Command)=>c.command==='portal.job'?{authority:'employee_hub',job:{id:'hub-visit',highlevelContactId:'provider-contact',kind:'walkthrough',startAt,endAt,normalizedLocalJobId:'wrong'}}:real(a,c)),s=store();const r=await reconcileExistingBookingAdoption(hub,{env:{EGC_BOOKING_ADOPT_EXISTING:'true'},store:s,provider:provider(),visits:[],portalComplete:true,providerComplete:true});expect(r.plans[0]?.reasons).toEqual(['adoption_readback_mismatch']);expect([...s.saved.values()][0]?.phase).toBe('pending');});
 it('does not leak arbitrary provider errors in persisted plan diagnostics',async()=>{const p=provider();p.getContact.mockRejectedValue(new Error('token=secret customer@example.invalid'));const r=await reconcileExistingBookingAdoption(portal(),{env:{},store:store(),provider:p,visits:[],portalComplete:true,providerComplete:true});expect(r.plans[0]?.reasons).toEqual(['adoption_verification_unavailable']);expect(JSON.stringify(r)).not.toContain('secret');});
 it.each(['schedule_adoption_slot_conflict','schedule_adoption_terminal_tombstone','schedule_adoption_idempotency_conflict'])('retains finite Hub %s diagnostics without private exception details',async code=>{const hub=portal();hub.mockRejectedValueOnce(Object.assign(new Error('token=secret private payload'),{code}));const r=await reconcileExistingBookingAdoption(hub,{env:{EGC_BOOKING_ADOPT_EXISTING:'true'},store:store(),provider:provider(),visits:[],portalComplete:true,providerComplete:true});expect(r.plans[0]?.reasons).toEqual([code]);expect(JSON.stringify(r)).not.toContain('secret');});
 it.each([{status:'cancelled'},{highlevelAppointmentId:'changed'},{highlevelCalendarId:'different'},{address:'Different location'}])('rejects changed exact Hub readback %j',async patch=>{const real=portal(),hub=vi.fn(async(a:Actor,c:Command)=>{const r=await real(a,c);return c.command==='portal.job'?{...r,job:{...(r.job as object),...patch}}:r;}),s=store();const r=await reconcileExistingBookingAdoption(hub,{env:{EGC_BOOKING_ADOPT_EXISTING:'true'},store:s,provider:provider(),visits:[],portalComplete:true,providerComplete:true});expect(r.plans[0]?.reasons).toEqual(['adoption_readback_mismatch']);expect([...s.saved.values()][0]?.phase).toBe('pending');});
});
