import {afterEach,beforeEach,describe,expect,it,vi} from 'vitest';
import Fastify from 'fastify';
const service=vi.hoisted(()=>({getCanonicalReport:vi.fn(),getCustomerTimeline:vi.fn(),getCustomerStateDiagnostics:vi.fn(),reconcileCustomerState:vi.fn()}));
vi.mock('@egc/customer-state',()=>service);
import {registerIntelligenceRoutes} from './intelligence.js';
const contactId='ac178de9-8156-42b8-818c-83e21c12c099', auth={authorization:'Bearer isolated-internal-token'}, since='2026-09-15T06:00:00Z',until='2026-09-22T06:00:00Z';
const apps:ReturnType<typeof Fastify>[]=[];
beforeEach(()=>{vi.resetAllMocks();vi.stubGlobal('fetch',vi.fn().mockRejectedValue(new Error('External sends disabled in this test')));});
afterEach(async()=>{for(const app of apps.splice(0))await app.close();vi.unstubAllGlobals();});
async function setup(){const app=Fastify();apps.push(app);await registerIntelligenceRoutes(app,async(request,reply)=>{if(request.headers.authorization!==auth.authorization)await reply.code(401).send({error:'unauthorized'});});return app;}
describe('canonical intelligence HTTP boundary',()=>{
 it.each([['GET',`/intelligence/report?since=${since}&until=${until}`],['GET',`/intelligence/customer/${contactId}`],['GET','/intelligence/diagnostics'],['POST','/intelligence/reconcile']] as const)('requires authentication before %s %s reaches source data',async(method,url)=>{const app=await setup(),r=await app.inject({method,url,...(method==='POST'?{payload:{}}:{})});expect(r.statusCode).toBe(401);for(const fn of Object.values(service))expect(fn).not.toHaveBeenCalled();expect(fetch).not.toHaveBeenCalled();});
 it('keeps activity and cohort windows distinct and preserves incomplete coverage',async()=>{const app=await setup(),report={authority:'canonical_customer_event_ledger',periodActivity:{jobsSold:{count:2}},cohort:{denominator:47},coverage:{complete:false,missingCustomers:[{contactId}]}};service.getCanonicalReport.mockResolvedValue(report);const r=await app.inject({method:'GET',url:`/intelligence/report?since=${since}&until=${until}&cohortSince=2026-09-01T06:00:00Z&cohortUntil=2026-10-01T06:00:00Z`,headers:auth});expect(r.statusCode).toBe(200);expect(r.json()).toEqual(report);expect(service.getCanonicalReport).toHaveBeenCalledWith({since,until,cohortSince:'2026-09-01T06:00:00Z',cohortUntil:'2026-10-01T06:00:00Z',refresh:true});expect(service.reconcileCustomerState).not.toHaveBeenCalled();expect(fetch).not.toHaveBeenCalled();});
 it('rejects malformed IDs, timestamps and unexpected reconciliation options before adapters',async()=>{const app=await setup();for(const url of ['/intelligence/customer/not-a-uuid','/intelligence/report?since=tomorrow&until=yesterday'])expect((await app.inject({method:'GET',url,headers:auth})).statusCode).toBe(400);for(const payload of [{maxContacts:501},{contactIds:['not-a-uuid']},{sendSms:true},{dryRun:false}])expect((await app.inject({method:'POST',url:'/intelligence/reconcile',headers:auth,payload})).statusCode).toBe(400);for(const fn of Object.values(service))expect(fn).not.toHaveBeenCalled();});
 it('reconciles exact bounded contacts without any message or Meta send path',async()=>{const app=await setup();service.reconcileCustomerState.mockResolvedValue({inspected:1,failed:0});const r=await app.inject({method:'POST',url:'/intelligence/reconcile',headers:auth,payload:{contactIds:[contactId],since,until,useAI:false,maxContacts:1}});expect(r.statusCode).toBe(200);expect(service.reconcileCustomerState).toHaveBeenCalledWith({contactIds:[contactId],since,until,useAI:false,maxContacts:1});expect(fetch).not.toHaveBeenCalled();});
 it('returns exact customer identity and diagnostics rather than empty success on provider failure',async()=>{const app=await setup();service.getCustomerTimeline.mockResolvedValue({contactId,coverage:{complete:false}});expect((await app.inject({method:'GET',url:`/intelligence/customer/${contactId}`,headers:auth})).json()).toEqual({contactId,coverage:{complete:false}});expect(service.getCustomerTimeline).toHaveBeenCalledWith({contactId});service.getCustomerStateDiagnostics.mockRejectedValue(new Error('token=synthetic-private customer@example.invalid'));const r=await app.inject({method:'GET',url:'/intelligence/diagnostics',headers:auth});expect(r.statusCode).toBe(503);expect(r.json()).toEqual({error:'customer_diagnostics_unavailable'});expect(r.body).not.toContain('synthetic-private');});
 it('bounds reconciliation request size before execution',async()=>{const app=await setup();const r=await app.inject({method:'POST',url:'/intelligence/reconcile',headers:auth,payload:{contactIds:[contactId],extra:'x'.repeat(65000)}});expect(r.statusCode).toBe(413);expect(service.reconcileCustomerState).not.toHaveBeenCalled();});
});
