import {afterEach,beforeEach,describe,expect,it,vi} from 'vitest';
import Fastify from 'fastify';
const service=vi.hoisted(()=>({getCanonicalReport:vi.fn(),getOperationalEventEvidence:vi.fn(),getCustomerTimeline:vi.fn(),getCustomerStateDiagnostics:vi.fn(),reconcileCustomerState:vi.fn()}));
vi.mock('@egc/customer-state',()=>service);
import {registerIntelligenceRoutes} from './intelligence.js';
const contactId='ac178de9-8156-42b8-818c-83e21c12c099', auth={authorization:'Bearer isolated-internal-token'}, since='2026-09-15T06:00:00Z',until='2026-09-22T06:00:00Z';
const apps:ReturnType<typeof Fastify>[]=[];
beforeEach(()=>{vi.resetAllMocks();vi.stubGlobal('fetch',vi.fn().mockRejectedValue(new Error('External sends disabled in this test')));});
afterEach(async()=>{for(const app of apps.splice(0))await app.close();vi.unstubAllGlobals();});
async function setup(){const app=Fastify();apps.push(app);await registerIntelligenceRoutes(app,async(request,reply)=>{if(request.headers.authorization!==auth.authorization)await reply.code(401).send({error:'unauthorized'});});return app;}
describe('canonical intelligence HTTP boundary',()=>{
 it.each([['GET',`/intelligence/report?since=${since}&until=${until}`],['GET',`/intelligence/events?since=${since}&until=${until}`],['GET',`/intelligence/customer/${contactId}`],['GET','/intelligence/diagnostics'],['POST','/intelligence/reconcile']] as const)('requires authentication before %s %s reaches source data',async(method,url)=>{const app=await setup(),r=await app.inject({method,url,...(method==='POST'?{payload:{}}:{})});expect(r.statusCode).toBe(401);for(const fn of Object.values(service))expect(fn).not.toHaveBeenCalled();expect(fetch).not.toHaveBeenCalled();});
 it('keeps activity and cohort windows distinct and preserves complete report structure and incomplete coverage',async()=>{const app=await setup(),report={authority:'canonical_customer_event_ledger',periodActivity:{jobsSold:{count:2,eventIds:['original-event']}},cohort:{denominator:47},coverage:{complete:false,missingCustomers:[{contactId}]},countedEventsPage:{offset:100,limit:200,total:301,nextOffset:300},countedEvents:[{evidence:[{excerpt:'x'.repeat(2000)}]}]};service.getCanonicalReport.mockResolvedValue(report);const r=await app.inject({method:'GET',url:`/intelligence/report?since=${since}&until=${until}&cohortSince=2026-09-01T06:00:00Z&cohortUntil=2026-10-01T06:00:00Z&evidenceOffset=100&evidenceLimit=200`,headers:auth});expect(r.statusCode).toBe(200);expect(r.json()).toEqual(report);expect(service.getCanonicalReport).toHaveBeenCalledWith({since,until,cohortSince:'2026-09-01T06:00:00Z',cohortUntil:'2026-10-01T06:00:00Z',evidenceOffset:100,evidenceLimit:200,refresh:true});expect(service.reconcileCustomerState).not.toHaveBeenCalled();expect(fetch).not.toHaveBeenCalled();});
 it('rejects malformed IDs, timestamps and unexpected reconciliation options before adapters',async()=>{const app=await setup();for(const url of ['/intelligence/customer/not-a-uuid','/intelligence/report?since=tomorrow&until=yesterday'])expect((await app.inject({method:'GET',url,headers:auth})).statusCode).toBe(400);for(const payload of [{maxContacts:501},{contactIds:['not-a-uuid']},{sendSms:true},{dryRun:false}])expect((await app.inject({method:'POST',url:'/intelligence/reconcile',headers:auth,payload})).statusCode).toBe(400);for(const fn of Object.values(service))expect(fn).not.toHaveBeenCalled();});
 it('reconciles exact bounded contacts without any message or Meta send path',async()=>{const app=await setup();service.reconcileCustomerState.mockResolvedValue({inspected:1,failed:0});const r=await app.inject({method:'POST',url:'/intelligence/reconcile',headers:auth,payload:{contactIds:[contactId],since,until,useAI:false,maxContacts:1}});expect(r.statusCode).toBe(200);expect(service.reconcileCustomerState).toHaveBeenCalledWith({contactIds:[contactId],since,until,useAI:false,maxContacts:1});expect(fetch).not.toHaveBeenCalled();});
 it('returns exact customer identity and diagnostics rather than empty success on provider failure',async()=>{const app=await setup();service.getCustomerTimeline.mockResolvedValue({contactId,coverage:{complete:false}});expect((await app.inject({method:'GET',url:`/intelligence/customer/${contactId}`,headers:auth})).json()).toEqual({contactId,coverage:{complete:false}});expect(service.getCustomerTimeline).toHaveBeenCalledWith({contactId});service.getCustomerStateDiagnostics.mockRejectedValue(new Error('token=synthetic-private customer@example.invalid'));const r=await app.inject({method:'GET',url:'/intelligence/diagnostics',headers:auth});expect(r.statusCode).toBe(503);expect(r.json()).toEqual({error:'customer_diagnostics_unavailable'});expect(r.body).not.toContain('synthetic-private');});
 it('bounds reconciliation request size before execution',async()=>{const app=await setup();const r=await app.inject({method:'POST',url:'/intelligence/reconcile',headers:auth,payload:{contactIds:[contactId],extra:'x'.repeat(65000)}});expect(r.statusCode).toBe(413);expect(service.reconcileCustomerState).not.toHaveBeenCalled();});
 it('retrieves exact repeated IDs including undated outcomes and preserves every original source pointer',async()=>{const app=await setup(),first=`egcev_${'a'.repeat(64)}`,second=`egcev_${'b'.repeat(64)}`,page={period:{since,until},events:[{eventId:first,details:{occurredAtVerified:false},evidence:[{sourceType:'user_confirmed',sourceRecordId:'original-message',excerpt:'Exact original long text '.repeat(30),sourcePointer:{threadId:'original-thread'}}]}],page:{offset:0,limit:2,total:1,nextOffset:null}};service.getOperationalEventEvidence.mockResolvedValue(page);const r=await app.inject({method:'GET',url:`/intelligence/events?since=${since}&until=${until}&eventIds=${first}&eventIds=${second}&limit=2`,headers:auth});expect(r.statusCode).toBe(200);expect(r.json()).toEqual(page);expect(service.getOperationalEventEvidence).toHaveBeenCalledWith({since,until,offset:0,limit:2,eventIds:[first,second]});expect(service.getCanonicalReport).not.toHaveBeenCalled();expect(service.reconcileCustomerState).not.toHaveBeenCalled();expect(fetch).not.toHaveBeenCalled();});
 it('follows page offsets without re-extracting and supports a single exact ID',async()=>{const app=await setup(),eventId=`egcev_${'c'.repeat(64)}`;service.getOperationalEventEvidence.mockResolvedValue({events:[],page:{offset:200,limit:100,total:200,nextOffset:null}});expect((await app.inject({method:'GET',url:`/intelligence/events?since=${since}&until=${until}&offset=200`,headers:auth})).statusCode).toBe(200);expect(service.getOperationalEventEvidence).toHaveBeenLastCalledWith({since,until,offset:200,limit:100});expect((await app.inject({method:'GET',url:`/intelligence/events?since=${since}&until=${until}&eventIds=${eventId}`,headers:auth})).statusCode).toBe(200);expect(service.getOperationalEventEvidence).toHaveBeenLastCalledWith({since,until,offset:0,limit:100,eventIds:[eventId]});});
 it('rejects invalid windows, pages, fuzzy IDs and unknown options before evidence reads',async()=>{const app=await setup();for(const suffix of ['offset=-1','offset=1.5','offset=9007199254740992','offset=1e2','offset=','limit=0','limit=201','limit=','eventIds=Annette','eventIds=','unknown=true',`eventIds=${`egcev_${'a'.repeat(64)}`}suffix`,Array.from({length:201},()=>`eventIds=egcev_${'a'.repeat(64)}`).join('&')])expect((await app.inject({method:'GET',url:`/intelligence/events?since=${since}&until=${until}&${suffix}`,headers:auth})).statusCode,suffix).toBe(400);for(const path of [`events?since=${until}&until=${since}`,`report?since=${until}&until=${since}`,`report?since=${since}&until=${until}&cohortSince=${until}`,`report?since=${since}&until=${until}&evidenceOffset=-1`,`report?since=${since}&until=${until}&evidenceLimit=201`,'events?since=2026-09-21T23:00:00-06:00&until=2026-09-22T01:00:00Z'])expect((await app.inject({method:'GET',url:`/intelligence/${path}`,headers:auth})).statusCode,path).toBe(400);for(const fn of Object.values(service))expect(fn).not.toHaveBeenCalled();});
 it('does not expose private provider failures as an empty successful evidence page',async()=>{const app=await setup();service.getOperationalEventEvidence.mockRejectedValue(new Error('token=synthetic-private customer@example.invalid'));const r=await app.inject({method:'GET',url:`/intelligence/events?since=${since}&until=${until}`,headers:auth});expect(r.statusCode).toBe(503);expect(r.json()).toEqual({error:'event_evidence_unavailable'});expect(r.body).not.toContain('synthetic-private');});
});
