import {describe,it,expect,vi,afterEach} from 'vitest';
import {randomUUID} from 'node:crypto';
import Fastify from 'fastify';
import multipart from '@fastify/multipart';
import {walkthroughExtractionSchema} from '@egc/schemas';
import {fingerprint,signRecordingEnvelope,verifyRecordingEnvelope,stableUuid,type RecordingClaims} from './recording-contracts.js';
import {registerRecordingRoutes,type RecordingService} from './recordings.js';
const key='isolated-recording-signing-test-only-0123456789';
const claims=():RecordingClaims=>({v:1,iss:'portal',aud:'egc-recordings',iat:Math.floor(Date.now()/1000),nonce:randomUUID(),actor:{id:'test-owner',role:'owner',kind:'human',workspace:'egc'},request:{requestId:randomUUID(),body:{command:'recording.get',recordingId:randomUUID()}}});
const apps:ReturnType<typeof Fastify>[]=[];afterEach(async()=>{for(const a of apps.splice(0))await a.close();});
describe('recording authentication and request contracts',()=>{
it('binds the exact actor, payload, workspace and audience',()=>{const c=claims();expect(verifyRecordingEnvelope(signRecordingEnvelope(c,key),key,'egc')).toEqual(c);expect(()=>verifyRecordingEnvelope(signRecordingEnvelope(c,key),key,'other')).toThrow();expect(()=>verifyRecordingEnvelope(signRecordingEnvelope({...c,aud:'egc-operations'},key),key,'egc')).toThrow();expect(()=>verifyRecordingEnvelope(signRecordingEnvelope(c,key),key+'wrong','egc')).toThrow();expect(()=>verifyRecordingEnvelope(signRecordingEnvelope({...c,iat:c.iat-120},key),key,'egc')).toThrow();});
it('sales can read but only human owners/managers can approve',()=>{const c=claims();c.actor.role='sales';expect(verifyRecordingEnvelope(signRecordingEnvelope(c,key),key,'egc').actor.role).toBe('sales');c.request.body={command:'recording.approve',recordingId:randomUUID(),revision:new Date().toISOString(),extraction:walkthroughExtractionSchema.parse({}),actions:[]};expect(()=>verifyRecordingEnvelope(signRecordingEnvelope(c,key),key,'egc')).toThrow('human_manager_approval_required');c.actor={...c.actor,kind:'integration',role:'integration'};expect(()=>verifyRecordingEnvelope(signRecordingEnvelope(c,key),key,'egc')).toThrow();});
it('stable logical IDs and canonical fingerprints resist key ordering',()=>{expect(stableUuid('one')).toBe(stableUuid('one'));expect(stableUuid('one')).not.toBe(stableUuid('two'));expect(fingerprint({a:1,b:2})).toBe(fingerprint({b:2,a:1}));expect(fingerprint({a:1})).not.toBe(fingerprint({a:2}));});
it('proposals require source evidence and do not invent deadlines or owners',()=>{const extraction=walkthroughExtractionSchema.parse({proposedActions:[{title:'Call back',kind:'callback',commitment:'Call about timing',sourceQuote:'I will call you about timing',ownerMention:null,dueMention:null,confidence:0.9}]});expect(extraction.proposedActions[0]?.ownerMention).toBeNull();expect(()=>walkthroughExtractionSchema.parse({proposedActions:[{title:'Guessed task'}]})).toThrow();expect(walkthroughExtractionSchema.parse({}).proposedActions).toEqual([]);});
});
describe('recording HTTP boundary',()=>{
async function setup(enabled=true){const app=Fastify();apps.push(app);await app.register(multipart);const execute=vi.fn(async()=>({ok:true})),processNext=vi.fn(async()=>false),upload=vi.fn();await registerRecordingRoutes(app,{EGC_OPERATIONS_ENABLED:String(enabled),EGC_OPERATIONS_PORTAL_SIGNING_SECRET:key},{execute,processNext,upload}as unknown as RecordingService);return{app,execute,upload};}
it('unsigned request never reaches recording service',async()=>{const{app,execute}=await setup();const r=await app.inject({method:'POST',url:'/recordings/rpc',payload:{envelope:'bad'}});expect(r.statusCode).toBe(401);expect(execute).not.toHaveBeenCalled();});
it('disabled service is a truthful503 and leaks no signing configuration',async()=>{const{app,execute}=await setup(false);const r=await app.inject({method:'POST',url:'/recordings/rpc',payload:{}});expect(r.statusCode).toBe(503);expect(r.json().error).toBe('operations_not_enabled');expect(r.body).not.toContain(key);expect(execute).not.toHaveBeenCalled();});
it('verified Hub identity is passed through; server failures redact PII and secrets',async()=>{const{app,execute}=await setup(),c=claims();const good=await app.inject({method:'POST',url:'/recordings/rpc',payload:{envelope:signRecordingEnvelope(c,key),actor:{id:'forged'}}});expect(good.statusCode).toBe(200);expect(execute).toHaveBeenCalledWith(c);execute.mockRejectedValue(new Error('private customer content access_token=secret'));const failure=await app.inject({method:'POST',url:'/recordings/rpc',payload:{envelope:signRecordingEnvelope(c,key)}});expect(failure.statusCode).toBe(503);expect(failure.body).not.toMatch(/private|access_token|secret/);});
});
