import {afterEach,beforeEach,describe,it,expect,vi} from 'vitest';
import {randomUUID} from 'node:crypto';
import Fastify from 'fastify';
import multipart from '@fastify/multipart';
import {signServiceRequest,servicePublicKeySet,signRequest,SERVICE_ORIGINS,type OperationsService,type Actor} from '@egc/operations';
const state=vi.hoisted(()=>({nonces:new Set<string>(),fail:false}));
vi.mock('@egc/database',async()=>{const actual=await vi.importActual<typeof import('@egc/database')>('@egc/database');return{...actual,getDb:()=>({insert:()=>({values:(v:{issuer:string;nonce:string})=>({onConflictDoNothing:()=>({returning:async()=>{if(state.fail)throw Error('private storage failure');const key=v.issuer+v.nonce;if(state.nonces.has(key))return[];state.nonces.add(key);return[{id:'synthetic'}];}})})}),delete:()=>({where:async()=>undefined})})};});
import {registerOperationsRoutes} from './operations.js';
import {registerServiceKeyRoute,serviceAuthEnabled} from './service-bridge.js';
import {registerRecordingRoutes,type RecordingService} from './recordings.js';
const hubSecret='synthetic-hub-root-secret-01234567890123456789',apiSecret='synthetic-api-root-secret-01234567890123456789',mcpSecret='synthetic-mcp-root-secret-01234567890123456789';
const env={EGC_OPERATIONS_ENABLED:'true',EGC_OPERATIONS_SERVICE_AUTH:'v2',API_BEARER_TOKEN:apiSecret,EGC_OPERATIONS_MCP_SIGNING_SECRET:mcpSecret,EGC_OPERATIONS_WORKSPACE:'egc'};
const actor:Actor={id:'hub:synthetic-owner',kind:'human',role:'owner',workspace:'egc'};
const apps:ReturnType<typeof Fastify>[]=[];
beforeEach(async()=>{state.nonces.clear();state.fail=false;const keys=await servicePublicKeySet({service:'hub',rootSecret:hubSecret,workspace:'egc'});vi.stubGlobal('fetch',vi.fn(async(url:unknown)=>{expect(url).toBe(SERVICE_ORIGINS.hub+'/api/operations-service-keys');return new Response(JSON.stringify(keys),{headers:{'content-type':'application/json'}});}));});
afterEach(async()=>{for(const app of apps.splice(0))await app.close();vi.unstubAllGlobals();});
const token=(path='/operations/rpc',body:Record<string,unknown>={command:'status'},principal:Actor=actor,requestId=randomUUID())=>signServiceRequest({service:'hub',rootSecret:hubSecret,workspace:'egc',path,actor:principal,request:{requestId,body}});
async function setup(){const app=Fastify();apps.push(app);const execute=vi.fn(async(..._args:unknown[])=>({ok:true}));await registerOperationsRoutes(app,{env,service:{execute} as unknown as OperationsService});await registerServiceKeyRoute(app,env);return{app,execute};}
describe('API pinned service bridge',()=>{
 it('rejects a mistyped authentication mode instead of enabling legacy fallback',()=>{expect(()=>serviceAuthEnabled({EGC_OPERATIONS_SERVICE_AUTH:'V2'})).toThrow('service_auth_mode_invalid');});
 it('publishes only the exact public key set and no server credential',async()=>{const{app}=await setup();const response=await app.inject('/operations/service-keys');expect(response.statusCode).toBe(200);expect(response.json()).toMatchObject({protocol:'egc-service-auth-v2',issuer:SERVICE_ORIGINS.api});expect(response.json().keys[0]).not.toHaveProperty('d');expect(response.body).not.toContain(apiSecret);});
 it('passes verified Hub identity and blocks replay before a second execution',async()=>{const{app,execute}=await setup(),envelope=await token();expect((await app.inject({method:'POST',url:'/operations/rpc',payload:{envelope}})).statusCode).toBe(200);const duplicate=await app.inject({method:'POST',url:'/operations/rpc',payload:{envelope}});expect(duplicate.statusCode).toBe(409);expect(duplicate.json().error).toBe('service_request_replayed');expect(execute).toHaveBeenCalledTimes(1);expect(execute.mock.calls[0]?.[0]).toEqual(actor);});
 it('fresh transport retries preserve logical request identity',async()=>{const{app,execute}=await setup(),requestId=randomUUID();for(let n=0;n<2;n++)expect((await app.inject({method:'POST',url:'/operations/rpc',payload:{envelope:await token('/operations/rpc',{command:'status'},actor,requestId)}})).statusCode).toBe(200);expect(execute.mock.calls.map(call=>call[2])).toEqual([requestId,requestId]);});
 it('rejects wrong-path signatures and unapproved Hub integration capabilities',async()=>{const{app,execute}=await setup();for(const envelope of [await token('/recordings/rpc'),await token('/operations/rpc',{command:'status'},{id:'forged-integration',kind:'integration',role:'integration',workspace:'egc'})])expect((await app.inject({method:'POST',url:'/operations/rpc',payload:{envelope}})).statusCode).toBeGreaterThanOrEqual(400);expect(execute).not.toHaveBeenCalled();});
 it('allows only the existing session-scoped schedule integration command',async()=>{const{app,execute}=await setup(),principal:Actor={id:'hub-schedule:synthetic',kind:'integration',role:'integration',workspace:'egc'};const body={command:'schedule.sync_provider',portalVisitId:'synthetic-visit',requestId:randomUUID(),runAutomations:false};expect((await app.inject({method:'POST',url:'/operations/rpc',payload:{envelope:await token('/operations/rpc',body,principal)}})).statusCode).toBe(200);expect(execute).toHaveBeenCalledTimes(1);});
 it('retains the separate MCP issuer but never downgrades to legacy Hub authentication',async()=>{const{app}=await setup();for(const iss of ['mcp','portal'] as const){const envelope=signRequest({v:1,iss,aud:'egc-operations',iat:Math.floor(Date.now()/1000),nonce:randomUUID(),actor:{id:'mcp-integration',kind:'integration',role:'integration',workspace:'egc'},request:{requestId:randomUUID(),body:{command:'status'}}},mcpSecret);const response=await app.inject({method:'POST',url:'/operations/rpc',payload:{envelope}});expect(response.statusCode).toBe(iss==='mcp'?200:503);}});
 it('fails closed when durable replay storage is unavailable and redacts upstream errors',async()=>{const{app,execute}=await setup();state.fail=true;const response=await app.inject({method:'POST',url:'/operations/rpc',payload:{envelope:await token()}});expect(response.statusCode).toBe(503);expect(response.json().error).toBe('service_replay_store_unavailable');expect(response.body).not.toContain('private');expect(execute).not.toHaveBeenCalled();});
 it('binds recording commands to their own route and preserves manager approval checks',async()=>{const app=Fastify();apps.push(app);await app.register(multipart);const execute=vi.fn(async(..._args:unknown[])=>({ok:true}));await registerRecordingRoutes(app,env,{execute,processNext:vi.fn(async()=>false)} as unknown as RecordingService);const body={command:'recording.get',recordingId:randomUUID()};expect((await app.inject({method:'POST',url:'/recordings/rpc',payload:{envelope:await token('/recordings/rpc',body)}})).statusCode).toBe(200);expect((await app.inject({method:'POST',url:'/recordings/rpc',payload:{envelope:await token('/operations/rpc',body)}})).statusCode).toBe(401);expect(execute).toHaveBeenCalledTimes(1);});
});
