/** Only synthetic loopback fixtures; never point this at production. */
import test,{beforeEach,after} from 'node:test';
import assert from 'node:assert/strict';
import {getDb,schema} from '@egc/database';
import {eq,sql} from 'drizzle-orm';
import {ReliableAppointments} from '../dist/appointment-reliability.js';
import {postgresAppointmentStore} from '../dist/appointment-store.js';
const url=new URL(process.env.DATABASE_URL||'http://invalid');
if(process.env.EGC_OPERATIONS_TEST!=='isolated'||!['localhost','127.0.0.1'].includes(url.hostname)||url.pathname!=='/egc_operations_test'||!['postgres:','postgresql:'].includes(url.protocol))throw new Error('Only isolated loopback egc_operations_test is allowed');
const db=getDb(),originalFetch=globalThis.fetch;globalThis.fetch=async()=>{throw new Error('No provider HTTP in appointment integration tests');};
const payload={contactId:'synthetic-contact',calendarId:'synthetic-calendar',title:'Synthetic booking',startTime:'2026-10-01T16:00:00.000Z',endTime:'2026-10-01T17:00:00.000Z',appointmentStatus:'confirmed',toNotify:false};
function fixture(){const events=new Map();let writes=0;const provider={locationId:'synthetic-location',getCalendarEvents:async()=>({events:[...events.values()]}),getAppointment:async id=>{if(!events.has(id))throw new Error('not found');return{event:events.get(id)};},createAppointment:async p=>{writes++;const e={id:'synthetic-event',...p};events.set(e.id,e);return{event:e};},updateAppointment:async(id,p)=>{writes++;const e={...events.get(id),...p,id};events.set(id,e);return{event:e};}};return{events,provider,service:new ReliableAppointments(postgresAppointmentStore(db),provider),writes:()=>writes};}
beforeEach(async()=>{await db.execute(sql`truncate appointment_operations`);});
after(async()=>{globalThis.fetch=originalFetch;await db.$client.end({timeout:5});});
test('ten concurrent requests claim one durable ledger row and send once',async()=>{const f=fixture();const r=await Promise.allSettled(Array.from({length:10},()=>f.service.create(payload)));assert.ok(r.some(x=>x.status==='fulfilled'));assert.equal(f.writes(),1);const rows=await db.select().from(schema.appointmentOperations);assert.equal(rows.length,1);assert.equal(rows[0].status,'accepted');assert.equal(rows[0].attemptCount,1);});
test('new service instance replays accepted operation without another write',async()=>{const f=fixture(),a=await f.service.create(payload),b=await new ReliableAppointments(postgresAppointmentStore(db),f.provider).create(payload);assert.equal(a.operationId,b.operationId);assert.equal(f.writes(),1);assert.equal(b.source,'verified-replay');});
test('payload conflict under the same create key preserves accepted row',async()=>{const f=fixture();await f.service.create(payload);await assert.rejects(f.service.create({...payload,title:'changed'}),e=>e.code==='appointment_idempotency_payload_conflict');assert.equal(f.writes(),1);assert.equal((await db.select().from(schema.appointmentOperations))[0].status,'accepted');});
test('unknown create survives restart and expired lease without duplicate write',async()=>{const f=fixture();let attempts=0;f.provider.createAppointment=async()=>{attempts++;throw new Error('secret provider body');};await assert.rejects(f.service.create(payload),e=>e.code==='appointment_outcome_unknown');const [op]=await db.select().from(schema.appointmentOperations);await db.update(schema.appointmentOperations).set({status:'in_flight',leaseExpiresAt:new Date(0)}).where(eq(schema.appointmentOperations.id,op.id));await assert.rejects(new ReliableAppointments(postgresAppointmentStore(db),f.provider).create(payload),e=>e.code==='appointment_outcome_unknown');assert.equal(attempts,1);assert.ok(!JSON.stringify(await db.select().from(schema.appointmentOperations)).includes('secret provider body'));f.events.set('eventual',{id:'eventual',...payload});assert.equal((await f.service.reconcile(op.id)).event.id,'eventual');});
test('resource lock blocks later edits while a prior update outcome is unknown',async()=>{const f=fixture();f.events.set('existing',{id:'existing',...payload});let attempts=0;f.provider.updateAppointment=async()=>{attempts++;throw new Error('timeout');};await assert.rejects(f.service.update('existing',{title:'First'}),e=>e.code==='appointment_outcome_unknown');await assert.rejects(f.service.update('existing',{title:'Second'}),e=>e.code==='appointment_resource_has_unresolved_operation');assert.equal(attempts,1);});
test('late failure cannot downgrade concurrently accepted operation',async()=>{const f=fixture(),r=await f.service.create(payload),store=postgresAppointmentStore(db);await store.finish(r.operationId,'unknown',{lastError:'stale_timeout'});const row=await store.get(r.operationId);assert.equal(row.status,'accepted');assert.equal(row.lastError,null);});
test('failed read preflight can safely retry because no write began',async()=>{const f=fixture();let reads=0;f.provider.getCalendarEvents=async()=>{if(!reads++)throw new Error('outage');return{events:[...f.events.values()]};};await assert.rejects(f.service.create(payload),e=>e.code==='appointment_preflight_unavailable');assert.equal(f.writes(),0);await f.service.create(payload);assert.equal(f.writes(),1);assert.equal((await db.select().from(schema.appointmentOperations))[0].attemptCount,2);});
