import {beforeEach,describe,expect,it,vi} from 'vitest';
import type {McpServer} from '@modelcontextprotocol/server';
import type {ZodType} from 'zod/v4';
const service=vi.hoisted(()=>({getCanonicalReport:vi.fn(),getCustomerTimeline:vi.fn(),getCustomerStateDiagnostics:vi.fn(),reconcileCustomerState:vi.fn(),recordUserConfirmedOutcome:vi.fn()}));
const meta=vi.hoisted(()=>({conversionStatus:vi.fn(),previewConversions:vi.fn(),syncConversions:vi.fn(),retryConversions:vi.fn(),sendTestEvent:vi.fn()}));
vi.mock('@egc/customer-state',()=>service);vi.mock('@egc/meta-conversions',()=>meta);
import {registerCustomerStateTools,canonicalFunnel,CUSTOMER_STATE_WRITE_TOOLS} from '../src/customer-state-tools.js';
import {requiredToolScope} from '../src/tool-access.js';
import {operationsPrincipal} from '../src/operations.js';
type Registration={config:{inputSchema:ZodType;annotations:{readOnlyHint:boolean;idempotentHint?:boolean};securitySchemes:Array<{type:string;scopes:string[]}>},handler:(input:unknown)=>Promise<unknown>};
const tools=new Map<string,Registration>(),contactId='ac178de9-8156-42b8-818c-83e21c12c099',from='2026-09-15T06:00:00Z',to='2026-09-22T06:00:00Z';
async function call(name:string,input:unknown={}){const t=tools.get(`egc.${name}`)!;return t.handler(t.config.inputSchema.parse(input));}
beforeEach(()=>{vi.resetAllMocks();tools.clear();registerCustomerStateTools({registerTool:(name:string,config:Registration['config'],handler:Registration['handler'])=>tools.set(name,{config,handler})} as unknown as McpServer);});
describe('canonical customer-state MCP boundary',()=>{
 it('maps both durable mutations to enforced write scope and all reads to read scope',()=>{expect(tools.size).toBe(5);for(const[name,{config}]of tools){const write=(CUSTOMER_STATE_WRITE_TOOLS as readonly string[]).includes(name);expect(requiredToolScope(name)).toBe(write?'egc:write':'egc:read');expect(config.annotations.readOnlyHint).toBe(!write);expect(config.securitySchemes).toEqual([{type:'oauth2',scopes:write?['egc:read','egc:write']:['egc:read']}]);}});
 it('passes separate activity/cohort windows and keeps canonical authority, evidence and coverage',async()=>{service.getCanonicalReport.mockResolvedValue({coverage:{complete:false},countedEvents:[{eventId:'source-linked-event'}]});const r=await call('operational_report',{from,to,cohortFrom:'2026-09-01T06:00:00Z',cohortTo:to});expect(service.getCanonicalReport).toHaveBeenCalledWith({since:from,until:to,cohortSince:'2026-09-01T06:00:00Z',cohortUntil:to,refresh:true});expect(r).toMatchObject({structuredContent:{result:{walkthroughAuthority:'employee_hub',coverage:{complete:false},countedEvents:[{eventId:'source-linked-event'}]}}});expect(meta.syncConversions).not.toHaveBeenCalled();});
 it('rejects reversed windows and invalid contact IDs before service calls',async()=>{await expect(call('operational_report',{from:to,to:from})).rejects.toThrow('invalid_report_window');await expect(call('customer_timeline',{contactId:'bad'})).rejects.toThrow();expect(service.getCanonicalReport).not.toHaveBeenCalled();expect(service.getCustomerTimeline).not.toHaveBeenCalled();});
 it('returns customer and Meta diagnostics without sending any event',async()=>{service.getCustomerStateDiagnostics.mockResolvedValue({verballyBookedProviderMissing:[{contactId}]});meta.conversionStatus.mockResolvedValue({counts:{accepted:3,pending:2,failed:1}});const r=await call('customer_state_diagnostics');expect(r).toMatchObject({structuredContent:{result:{customers:{verballyBookedProviderMissing:[{contactId}]},meta:{counts:{accepted:3,pending:2,failed:1}}}}});expect(meta.conversionStatus).toHaveBeenCalledWith({days:7,limit:100});expect(meta.syncConversions).not.toHaveBeenCalled();expect(meta.retryConversions).not.toHaveBeenCalled();});
 it('refuses a user assertion without a verified actor and ignores caller-forged actor identity',async()=>{const input={contactId,field:'job_completed',value:true,exactText:'Customer work is complete.',sourceReference:'original-message-id',actorId:'forged-owner'};await expect(call('record_user_confirmed_outcome',input)).rejects.toThrow('verified_principal_required');expect(service.recordUserConfirmedOutcome).not.toHaveBeenCalled();service.recordUserConfirmedOutcome.mockResolvedValue({assertionId:'durable-1'});await operationsPrincipal.run({id:'verified-owner',role:'owner',kind:'human',workspace:'egc'},()=>call('record_user_confirmed_outcome',input));expect(service.recordUserConfirmedOutcome).toHaveBeenCalledWith({contactId,field:'job_completed',value:true,exactText:input.exactText,sourceReference:'original-message-id',actorId:'verified-owner'});expect(service.recordUserConfirmedOutcome.mock.calls[0]?.[0]).not.toHaveProperty('occurredAt');expect(service.recordUserConfirmedOutcome.mock.calls[0]?.[0]).not.toHaveProperty('valueCents');});
 it('preserves original assertion times/source/value on replay without manufacturing payment amounts',async()=>{const input={contactId,field:'job_sold',value:true,exactText:'Accepted the $139 quote.',sourceReference:'original-sms-acceptance-id',assertedAt:'2026-09-21T16:53:38Z',occurredAt:'2026-09-21T16:53:38Z',valueCents:13900,currency:'USD'};for(let i=0;i<2;i++)await operationsPrincipal.run({id:'owner',role:'owner',kind:'human',workspace:'egc'},()=>call('record_user_confirmed_outcome',input));expect(service.recordUserConfirmedOutcome.mock.calls[0]).toEqual(service.recordUserConfirmedOutcome.mock.calls[1]);expect(service.recordUserConfirmedOutcome).toHaveBeenLastCalledWith({...input,actorId:'owner'});expect(meta.syncConversions).not.toHaveBeenCalled();});
 it('deduplicates verbal/formal cohort customers and keeps Meta calls read-only',async()=>{const metric=(contactIds:string[])=>({numerator:contactIds.length,contactIds});service.getCanonicalReport.mockResolvedValue({cohort:{denominator:3,window:{since:from,until:to},metrics:{walkthroughsVerballyBooked:metric(['one','two']),walkthroughsFormallyBooked:metric(['one']),twoWayContacts:metric(['one','two']),humanOutreach:metric(['one','two','three'])}},customers:[{contactId:'one',leadCreatedAt:'2026-09-16T10:00:00Z',state:'WALKTHROUGH_BOOKED'}]});meta.conversionStatus.mockResolvedValue({});meta.previewConversions.mockResolvedValue({});const r=await canonicalFunnel(7);expect(r.counts.booked).toBe(2);expect(r.counts.bookedAfterTwoWayContact).toBe(2);expect(r.total).toBe(3);expect(meta.syncConversions).not.toHaveBeenCalled();expect(meta.retryConversions).not.toHaveBeenCalled();});
 it('bounds reconciliation to exact contacts and disallows negative financial assertions',async()=>{await call('reconcile_customer_state',{contactIds:[contactId],useAI:false,maxContacts:1});expect(service.reconcileCustomerState).toHaveBeenCalledWith({contactIds:[contactId],useAI:false,maxContacts:1});await expect(call('record_user_confirmed_outcome',{contactId,field:'revenue_collected',value:true,exactText:'Received money',sourceReference:'source',valueCents:-1})).rejects.toThrow();expect(service.recordUserConfirmedOutcome).not.toHaveBeenCalled();expect(meta.syncConversions).not.toHaveBeenCalled();});
});
