import {beforeEach,describe,expect,it,vi} from 'vitest';
import type {McpServer} from '@modelcontextprotocol/server';
import type {ZodType} from 'zod/v4';
const service=vi.hoisted(()=>({getCanonicalReport:vi.fn(),getOperationalEventEvidence:vi.fn(),getCustomerTimeline:vi.fn(),getCustomerStateDiagnostics:vi.fn(),reconcileCustomerState:vi.fn(),recordUserConfirmedOutcome:vi.fn()}));
const meta=vi.hoisted(()=>({conversionStatus:vi.fn(),previewConversions:vi.fn(),syncConversions:vi.fn(),retryConversions:vi.fn(),sendTestEvent:vi.fn()}));
vi.mock('@egc/customer-state',async()=>({...service,formatOperationalBriefing:(await import('../../../services/customer-state/src/briefing.js')).formatOperationalBriefing}));vi.mock('@egc/meta-conversions',()=>meta);
import {registerCustomerStateTools,canonicalFunnel,CUSTOMER_STATE_WRITE_TOOLS} from '../src/customer-state-tools.js';
import {requiredToolScope} from '../src/tool-access.js';
import {operationsPrincipal} from '../src/operations.js';
type Registration={config:{inputSchema:ZodType;annotations:{readOnlyHint:boolean;idempotentHint?:boolean};securitySchemes:Array<{type:string;scopes:string[]}>},handler:(input:unknown)=>Promise<unknown>};
const tools=new Map<string,Registration>(),contactId='ac178de9-8156-42b8-818c-83e21c12c099',from='2026-09-15T06:00:00Z',to='2026-09-22T06:00:00Z';
const eventId=`egcev_${'a'.repeat(64)}`;
function report(extra:Record<string,unknown>={}){return {period:{since:from,until:to},periodActivity:{},cohort:{denominator:0,window:{since:from,until:to},metrics:{}},customers:[],pipelines:{walkthrough:[],videoQuote:[],directJob:[]},countedEvents:[],confirmedOutcomesWithUnknownTime:[],reviewRequiredEvents:[],...extra};}
function event(id=eventId){return {eventId:id,contactId,eventType:'job_sold',occurredAt:from,confidence:1,humanReviewNeeded:false,nextAction:null,valueCents:null,currency:null,valueVerified:false,details:{},evidence:[{sourceType:'call_transcript',sourceRecordId:'original-call',excerpt:'Exact accepted work evidence'.repeat(30),sourcePointer:{callId:'original-call'}}]};}
async function call(name:string,input:unknown={}){const t=tools.get(`egc.${name}`)!;return t.handler(t.config.inputSchema.parse(input));}
beforeEach(()=>{vi.resetAllMocks();tools.clear();registerCustomerStateTools({registerTool:(name:string,config:Registration['config'],handler:Registration['handler'])=>tools.set(name,{config,handler})} as unknown as McpServer);});
describe('canonical customer-state MCP boundary',()=>{
 it('maps both durable mutations to enforced write scope and all reads to read scope',()=>{expect(tools.size).toBe(6);for(const[name,{config}]of tools){const write=(CUSTOMER_STATE_WRITE_TOOLS as readonly string[]).includes(name);expect(requiredToolScope(name)).toBe(write?'egc:write':'egc:read');expect(config.annotations.readOnlyHint).toBe(!write);expect(config.securitySchemes).toEqual([{type:'oauth2',scopes:write?['egc:read','egc:write']:['egc:read']}]);}});
 it('passes separate activity/cohort windows and keeps canonical authority, evidence and coverage',async()=>{service.getCanonicalReport.mockResolvedValue(report({coverage:{complete:false},countedEvents:[event()]}));const r=await call('operational_report',{from,to,cohortFrom:'2026-09-01T06:00:00Z',cohortTo:to});expect(service.getCanonicalReport).toHaveBeenCalledWith({since:from,until:to,cohortSince:'2026-09-01T06:00:00Z',cohortUntil:to,evidenceOffset:0,evidenceLimit:100,refresh:true});expect(r).toMatchObject({structuredContent:{result:{walkthroughAuthority:'employee_hub',presentation:'compact_operational_briefing',coverage:{complete:false},countedEvents:[{eventId}]}}});expect(meta.syncConversions).not.toHaveBeenCalled();});
 it('rejects reversed windows and invalid contact IDs before service calls',async()=>{await expect(call('operational_report',{from:to,to:from})).rejects.toThrow('invalid_report_window');await expect(call('customer_timeline',{contactId:'bad'})).rejects.toThrow();expect(service.getCanonicalReport).not.toHaveBeenCalled();expect(service.getCustomerTimeline).not.toHaveBeenCalled();});
 it('returns customer and Meta diagnostics without sending any event',async()=>{service.getCustomerStateDiagnostics.mockResolvedValue({verballyBookedProviderMissing:[{contactId}]});meta.conversionStatus.mockResolvedValue({counts:{accepted:3,pending:2,failed:1}});const r=await call('customer_state_diagnostics');expect(r).toMatchObject({structuredContent:{result:{customers:{verballyBookedProviderMissing:[{contactId}]},meta:{counts:{accepted:3,pending:2,failed:1}}}}});expect(meta.conversionStatus).toHaveBeenCalledWith({days:7,limit:100});expect(meta.syncConversions).not.toHaveBeenCalled();expect(meta.retryConversions).not.toHaveBeenCalled();});
 it('refuses a user assertion without a verified actor and ignores caller-forged actor identity',async()=>{const input={contactId,field:'job_completed',value:true,exactText:'Customer work is complete.',sourceReference:'original-message-id',actorId:'forged-owner'};await expect(call('record_user_confirmed_outcome',input)).rejects.toThrow('verified_principal_required');expect(service.recordUserConfirmedOutcome).not.toHaveBeenCalled();service.recordUserConfirmedOutcome.mockResolvedValue({assertionId:'durable-1'});await operationsPrincipal.run({id:'verified-owner',role:'owner',kind:'human',workspace:'egc'},()=>call('record_user_confirmed_outcome',input));expect(service.recordUserConfirmedOutcome).toHaveBeenCalledWith({contactId,field:'job_completed',value:true,exactText:input.exactText,sourceReference:'original-message-id',actorId:'verified-owner'});expect(service.recordUserConfirmedOutcome.mock.calls[0]?.[0]).not.toHaveProperty('occurredAt');expect(service.recordUserConfirmedOutcome.mock.calls[0]?.[0]).not.toHaveProperty('valueCents');});
 it('preserves original assertion times/source/value on replay without manufacturing payment amounts',async()=>{const input={contactId,field:'job_sold',value:true,exactText:'Accepted the $139 quote.',sourceReference:'original-sms-acceptance-id',assertedAt:'2026-09-21T16:53:38Z',occurredAt:'2026-09-21T16:53:38Z',valueCents:13900,currency:'USD'};for(let i=0;i<2;i++)await operationsPrincipal.run({id:'owner',role:'owner',kind:'human',workspace:'egc'},()=>call('record_user_confirmed_outcome',input));expect(service.recordUserConfirmedOutcome.mock.calls[0]).toEqual(service.recordUserConfirmedOutcome.mock.calls[1]);expect(service.recordUserConfirmedOutcome).toHaveBeenLastCalledWith({...input,actorId:'owner'});expect(meta.syncConversions).not.toHaveBeenCalled();});
 it('deduplicates verbal/formal cohort customers and keeps Meta counts and calls read-only',async()=>{const metric=(contactIds:string[])=>({numerator:contactIds.length,contactIds});service.getCanonicalReport.mockResolvedValue(report({cohort:{denominator:3,window:{since:from,until:to},metrics:{walkthroughsVerballyBooked:metric(['one','two']),walkthroughsFormallyBooked:metric(['one']),twoWayContacts:metric(['one','two']),humanOutreach:metric(['one','two','three'])}},metaConversions:[{status:'accepted',count:12}],metaConversionsDuringPeriod:{acceptedEvents:2},periodActivity:{jobsSold:{count:4,unit:'distinct_customers',eventIds:[eventId],contactIds:['one','two','three','four']}}}));meta.conversionStatus.mockResolvedValue({counts:{accepted:12}});meta.previewConversions.mockResolvedValue({eligible:2});const r=await canonicalFunnel(7);expect(r.counts.booked).toBe(2);expect(r.counts.bookedAfterTwoWayContact).toBe(2);expect(r.total).toBe(3);expect(r.periodActivity.jobsSold).toMatchObject({count:4,unit:'distinct_customers',evidenceEventCount:1});expect(r.meta).toEqual({status:{counts:{accepted:12}},preview:{eligible:2}});expect(r.metaConversions).toEqual([{status:'accepted',count:12}]);expect(r.metaConversionsDuringPeriod).toEqual({acceptedEvents:2});expect(meta.syncConversions).not.toHaveBeenCalled();expect(meta.retryConversions).not.toHaveBeenCalled();});
 it('retrieves full original evidence after a compact bounded page without altering counts',async()=>{const fullEvent=event();service.getCanonicalReport.mockResolvedValue(report({periodActivity:{jobsSold:{count:2,unit:'distinct_customers',eventIds:[eventId,'second'],contactIds:[contactId,'second']}},countedEvents:[fullEvent],countedEventsPage:{offset:4,limit:1,total:8,nextOffset:5,fullSource:'customer_timeline_and_original_source_pointer'}}));const r=await call('operational_report',{from,to,evidenceOffset:4,evidenceLimit:1}) as {structuredContent:{result:Record<string,any>}};expect(service.getCanonicalReport).toHaveBeenCalledWith(expect.objectContaining({evidenceOffset:4,evidenceLimit:1}));expect(r.structuredContent.result.countedEventsPage).toMatchObject({offset:4,limit:1,total:8,nextOffset:5});expect(r.structuredContent.result.periodActivity.jobsSold.count).toBe(2);expect(r.structuredContent.result.countedEvents[0].evidence[0].excerpt.length).toBe(400);const fullPage={period:{since:from,until:to},events:[fullEvent],page:{offset:0,limit:1,total:1,nextOffset:null}};service.getOperationalEventEvidence.mockResolvedValue(fullPage);expect(await call('operational_event_evidence',{since:from,until:to,eventIds:[eventId],limit:1})).toMatchObject({structuredContent:{result:fullPage}});expect(service.getOperationalEventEvidence).toHaveBeenCalledWith({since:from,until:to,offset:0,limit:1,eventIds:[eventId]});expect(service.reconcileCustomerState).not.toHaveBeenCalled();expect(meta.syncConversions).not.toHaveBeenCalled();});
 it('rejects unsafe pages, fuzzy event identities and invalid cohort windows before reads',async()=>{for(const input of [{offset:-1},{offset:1.5},{offset:Number.MAX_SAFE_INTEGER+1},{limit:201},{limit:0},{eventIds:['customer-name']},{eventIds:[`${eventId}suffix`]},{eventIds:Array(201).fill(eventId)},{send:true},{since:to,until:from}])await expect(call('operational_event_evidence',{since:from,until:to,...input})).rejects.toThrow();for(const input of [{cohortFrom:to,cohortTo:from},{cohortFrom:to},{evidenceLimit:201},{evidenceOffset:-1}])await expect(call('operational_report',{from,to,...input})).rejects.toThrow();expect(service.getCanonicalReport).not.toHaveBeenCalled();expect(service.getOperationalEventEvidence).not.toHaveBeenCalled();});
 it('compares offset timestamps by their actual instant and preserves an explicitly empty event selection',async()=>{service.getOperationalEventEvidence.mockResolvedValue({events:[],page:{nextOffset:null}});await call('operational_event_evidence',{since:'2026-09-21T20:00:00-06:00',until:'2026-09-22T01:00:00-06:00',eventIds:[]});expect(service.getOperationalEventEvidence).toHaveBeenCalledWith({since:'2026-09-21T20:00:00-06:00',until:'2026-09-22T01:00:00-06:00',offset:0,limit:100,eventIds:[]});await expect(call('operational_event_evidence',{since:'2026-09-21T23:00:00-06:00',until:'2026-09-22T01:00:00Z'})).rejects.toThrow('invalid_report_window');});
 it('bounds reconciliation to exact contacts and disallows negative financial assertions',async()=>{await call('reconcile_customer_state',{contactIds:[contactId],useAI:false,maxContacts:1});expect(service.reconcileCustomerState).toHaveBeenCalledWith({contactIds:[contactId],useAI:false,maxContacts:1});await expect(call('record_user_confirmed_outcome',{contactId,field:'revenue_collected',value:true,exactText:'Received money',sourceReference:'source',valueCents:-1})).rejects.toThrow();expect(service.recordUserConfirmedOutcome).not.toHaveBeenCalled();expect(meta.syncConversions).not.toHaveBeenCalled();});
});
