import {describe,it,expect,vi} from "vitest";
import {randomUUID} from "node:crypto";
import {ReliableAppointments,AppointmentOperationError,appointmentMatches,appointmentDigest,type AppointmentStore,type AppointmentOperation,type AppointmentIntent,type AppointmentProvider} from "./appointment-reliability.js";

type Json=Record<string,unknown>;
const body=()=>({contactId:"synthetic-contact",calendarId:"walkthrough-calendar",title:"Synthetic walkthrough",startTime:"2026-09-23T16:00:00.000Z",endTime:"2026-09-23T17:00:00.000Z",appointmentStatus:"confirmed",toNotify:false});
class MemoryStore implements AppointmentStore {
  rows=new Map<string,AppointmentOperation>();
  async reserve(intent:AppointmentIntent) {
    const prior=[...this.rows.values()].find(r=>r.operationKey===intent.operationKey);
    if(prior){if(prior.payloadHash!==intent.payloadHash)throw new AppointmentOperationError("appointment_idempotency_payload_conflict",prior.id);return {...prior};}
    const row:AppointmentOperation={...intent,id:randomUUID(),status:"pending",response:null,lastError:null,attemptCount:0,leaseExpiresAt:null};this.rows.set(row.id,row);return {...row};
  }
  async get(id:string){const row=this.rows.get(id);return row?{...row}:null;}
  async claim(op:AppointmentOperation,now:Date){const row=this.rows.get(op.id)!;if([...this.rows.values()].some(r=>r.id!==row.id&&r.resourceKey===row.resourceKey&&["in_flight","unknown"].includes(r.status)))throw new AppointmentOperationError("appointment_resource_has_unresolved_operation");if(!["pending","failed"].includes(row.status))return false;Object.assign(row,{status:"in_flight",attemptCount:row.attemptCount+1,leaseExpiresAt:new Date(now.valueOf()+120000)});return true;}
  async finish(id:string,status:AppointmentOperation["status"],data:Parameters<AppointmentStore["finish"]>[2]){const row=this.rows.get(id)!;if(row.status==="accepted"&&status!=="accepted")return;Object.assign(row,{status,...data,...(status==="in_flight"?{}:{leaseExpiresAt:null}),...(status==="accepted"?{lastError:null}:{})});}
}
function fixture(){
  const store=new MemoryStore(),events=new Map<string,Json>();
  const provider:AppointmentProvider={locationId:"synthetic-location",getCalendarEvents:vi.fn(async()=>({events:[...events.values()]})),getAppointment:vi.fn(async id=>{const event=events.get(id);if(!event)throw new Error("404 synthetic");return {event};}),createAppointment:vi.fn(async payload=>{const event={id:"new-event",...payload};events.set("new-event",event);return {event};}),updateAppointment:vi.fn(async(id,payload)=>{const event={...events.get(id),...payload,id};events.set(id,event);return {event};})};
  const service=new ReliableAppointments(store,provider);return {store,events,provider,service};
}
const code=(promise:Promise<unknown>,expected:string)=>expect(promise).rejects.toMatchObject({code:expected});

describe("durable appointment creation",()=>{
  it("creates once, verifies by GET, then recovers the same ledger after restart",async()=>{const f=fixture();const first=await f.service.create(body());expect(first.source).toBe("created");const second=await new ReliableAppointments(f.store,f.provider).create(body());expect(second.operationId).toBe(first.operationId);expect(second.source).toBe("verified-replay");expect(f.provider.createAppointment).toHaveBeenCalledTimes(1);expect(f.provider.getAppointment).toHaveBeenCalledTimes(2);expect([...f.store.rows.values()][0]?.status).toBe("accepted");});
  it("competing calls have one durable claim and one provider create",async()=>{const f=fixture();const result=await Promise.allSettled(Array.from({length:10},()=>f.service.create(body())));expect(result.filter(r=>r.status==="fulfilled")).toHaveLength(1);expect(f.provider.createAppointment).toHaveBeenCalledTimes(1);expect(f.store.rows.size).toBe(1);});
  it("same business key with changed details fails before another provider write",async()=>{const f=fixture();await f.service.create(body());await code(f.service.create({...body(),title:"Changed scope"}),"appointment_idempotency_payload_conflict");expect(f.provider.createAppointment).toHaveBeenCalledTimes(1);});
  it("adopts one exact live event and never uses fuzzy title matches",async()=>{const f=fixture();f.events.set("existing",{id:"existing",...body()});expect((await f.service.create(body())).source).toBe("provider-preflight");expect(f.provider.createAppointment).not.toHaveBeenCalled();const g=fixture();g.events.set("existing",{id:"existing",...body(),title:"Synthetic walkthrough extra"});await code(g.service.create(body()),"appointment_existing_booking_conflict");expect(g.provider.createAppointment).not.toHaveBeenCalled();});
  it("multiple matching provider records require explicit review",async()=>{const f=fixture();for(const id of ["duplicate-a","duplicate-b"])f.events.set(id,{id,...body()});await code(f.service.create(body()),"appointment_ambiguous_matches");expect(f.provider.createAppointment).not.toHaveBeenCalled();});
  it("nearby but different start times do not silently match or create",async()=>{const f=fixture();f.events.set("nearby",{id:"nearby",...body(),startTime:"2026-09-23T16:01:00.000Z"});await code(f.service.create(body()),"appointment_existing_booking_conflict");expect(f.provider.createAppointment).not.toHaveBeenCalled();});
  it("cancelled events are never reused as a successful booking",async()=>{const f=fixture();f.events.set("cancelled",{id:"cancelled",...body(),appointmentStatus:"cancelled"});const result=await f.service.create(body());expect(result.event.id).toBe("new-event");expect(f.provider.createAppointment).toHaveBeenCalledTimes(1);});
  it("a cancelled accepted booking stays changed and cannot silently be recreated",async()=>{const f=fixture();await f.service.create(body());f.events.set("new-event",{id:"new-event",...body(),appointmentStatus:"cancelled"});await code(f.service.create(body()),"appointment_changed_since_acceptance");expect(f.provider.createAppointment).toHaveBeenCalledTimes(1);});
  it("provider preflight outage remains retryable but sends nothing",async()=>{const f=fixture();vi.mocked(f.provider.getCalendarEvents).mockRejectedValueOnce(new Error("secret provider response"));await code(f.service.create(body()),"appointment_preflight_unavailable");expect(f.provider.createAppointment).not.toHaveBeenCalled();expect([...f.store.rows.values()][0]?.lastError).toBe("appointment_preflight_unavailable");await f.service.create(body());expect(f.provider.createAppointment).toHaveBeenCalledTimes(1);});
  it("known exact Hub provider link must be verified and never replaced by a missing list result",async()=>{const f=fixture();vi.mocked(f.provider.getCalendarEvents).mockResolvedValue({events:[]});await code(f.service.create(body(),{},"linked-but-unavailable"),"appointment_preflight_unavailable");expect(f.provider.createAppointment).not.toHaveBeenCalled();f.events.set("linked-but-unavailable",{id:"linked-but-unavailable",...body()});expect((await f.service.create(body(),{},"linked-but-unavailable")).event.id).toBe("linked-but-unavailable");expect(f.provider.createAppointment).not.toHaveBeenCalled();});
  it("fresh request ID does not bypass an unresolved create for the same booking",async()=>{const f=fixture();vi.mocked(f.provider.createAppointment).mockRejectedValue(new Error("timeout"));await code(f.service.create(body(),{},null,"one"),"appointment_outcome_unknown");await code(f.service.create(body(),{},null,"two"),"appointment_resource_has_unresolved_operation");expect(f.provider.createAppointment).toHaveBeenCalledTimes(1);});
  it.each([{}, {events:{}}, {events:[{}]}, {events:[],nextPageToken:"more"}])("malformed or incomplete listing never means empty (%j)",async response=>{const f=fixture();vi.mocked(f.provider.getCalendarEvents).mockResolvedValue(response);await expect(f.service.create(body())).rejects.toBeInstanceOf(AppointmentOperationError);expect(f.provider.createAppointment).not.toHaveBeenCalled();});
  it("hydrates provider list summaries before deciding identity",async()=>{const f=fixture();f.events.set("existing",{id:"existing",...body()});vi.mocked(f.provider.getCalendarEvents).mockResolvedValue({events:[{id:"existing",title:body().title}]});expect((await f.service.create(body())).event.id).toBe("existing");expect(f.provider.createAppointment).not.toHaveBeenCalled();});
  it("does not mistake another contact's booking for this one",async()=>{const f=fixture();f.events.set("other",{id:"other",...body(),contactId:"other-contact"});expect((await f.service.create(body())).event.id).toBe("new-event");});
});

describe("uncertain provider outcomes",()=>{
  it("recovers a create that committed then timed out without resending",async()=>{const f=fixture();vi.mocked(f.provider.createAppointment).mockImplementation(async payload=>{f.events.set("remote-committed",{id:"remote-committed",...payload});throw new Error("provider timeout with secret");});const r=await f.service.create(body());expect(r.source).toBe("provider-recovery");expect(r.event.id).toBe("remote-committed");expect(f.provider.createAppointment).toHaveBeenCalledTimes(1);});
  it("eventual consistency never permits a second create, even after restart",async()=>{const f=fixture();vi.mocked(f.provider.createAppointment).mockRejectedValue(new Error("timeout"));await code(f.service.create(body()),"appointment_outcome_unknown");const row=[...f.store.rows.values()][0]!;expect(row.status).toBe("unknown");await code(new ReliableAppointments(f.store,f.provider).create(body()),"appointment_outcome_unknown");expect(f.provider.createAppointment).toHaveBeenCalledTimes(1);f.events.set("later",{id:"later",...body()});expect((await f.service.reconcile(row.id)).event.id).toBe("later");expect(f.provider.createAppointment).toHaveBeenCalledTimes(1);});
  it("malformed create response retains unknown, not failed/retryable",async()=>{const f=fixture();vi.mocked(f.provider.createAppointment).mockResolvedValue({success:true});await code(f.service.create(body()),"appointment_outcome_unknown");await code(f.service.create(body()),"appointment_outcome_unknown");expect(f.provider.createAppointment).toHaveBeenCalledTimes(1);expect([...f.store.rows.values()][0]?.status).toBe("unknown");});
  it("expired leases reconcile only and live leases return busy",async()=>{const f=fixture();vi.mocked(f.provider.createAppointment).mockRejectedValue(new Error("timeout"));await expect(f.service.create(body())).rejects.toThrow();const row=[...f.store.rows.values()][0]!;row.status="in_flight";row.leaseExpiresAt=new Date(Date.now()+60000);await code(f.service.reconcile(row.id),"appointment_operation_in_flight");row.leaseExpiresAt=new Date(0);await code(f.service.create(body()),"appointment_outcome_unknown");expect(f.provider.createAppointment).toHaveBeenCalledTimes(1);});
  it("raw errors, credentials and provider bodies never become ledger errors",async()=>{const f=fixture();const secret="Bearer production-token customer@email.invalid";vi.mocked(f.provider.createAppointment).mockRejectedValue(new Error(secret));await expect(f.service.create(body())).rejects.toThrow("appointment_outcome_unknown");expect(JSON.stringify([...f.store.rows.values()])).not.toContain(secret);});
});

describe("exact update/cancellation verification",()=>{
  it("verifies end time, description and address rather than only start/status",()=>{const actual={id:"existing",...body(),description:"Reviewed",address:"Synthetic address"};expect(appointmentMatches(actual,{endTime:body().endTime,description:"Reviewed",address:"Synthetic address"},"existing")).toBe(true);for(const change of [{endTime:"2026-09-23T18:00:00.000Z"},{description:"Different"},{address:"Different"},{assignedUserId:"owner"}])expect(appointmentMatches(actual,change,"existing")).toBe(false);expect(appointmentMatches(actual,{},"wrong-id")).toBe(false);});
  it("updates then verifies exact canonical response and replays without writing",async()=>{const f=fixture();f.events.set("existing",{id:"existing",...body()});const payload={endTime:"2026-09-23T18:00:00.000Z",address:"Synthetic address",description:"Reviewed scope"};const r=await f.service.update("existing",payload);expect(r.source).toBe("updated");await f.service.update("existing",payload);expect(f.provider.updateAppointment).toHaveBeenCalledTimes(1);});
  it("cancellation persists verified cancelled state and leaves history",async()=>{const f=fixture();f.events.set("existing",{id:"existing",...body()});const r=await f.service.update("existing",{appointmentStatus:"cancelled"});expect(r.event.appointmentStatus).toBe("cancelled");expect(f.events.has("existing")).toBe(true);expect([...f.store.rows.values()][0]?.kind).toBe("cancel");});
  it("unknown update blocks distinct later edits to the same appointment",async()=>{const f=fixture();f.events.set("existing",{id:"existing",...body()});vi.mocked(f.provider.updateAppointment).mockRejectedValue(new Error("timeout"));await code(f.service.update("existing",{title:"First"}),"appointment_outcome_unknown");await code(f.service.update("existing",{title:"Second"}),"appointment_resource_has_unresolved_operation");expect(f.provider.updateAppointment).toHaveBeenCalledTimes(1);});
  it("provider accepted false details remain unknown instead of success",async()=>{const f=fixture();f.events.set("existing",{id:"existing",...body()});vi.mocked(f.provider.updateAppointment).mockResolvedValue({event:{id:"existing",...body()}});await code(f.service.update("existing",{endTime:"2026-09-23T18:00:00.000Z"}),"appointment_outcome_unknown");expect([...f.store.rows.values()][0]?.status).toBe("unknown");});
  it("wrong contact is rejected before edit",async()=>{const f=fixture();f.events.set("existing",{id:"existing",...body()});await code(f.service.update("existing",{title:"First"},{contactProviderId:"different-contact"}),"appointment_provider_contact_mismatch");expect(f.provider.updateAppointment).not.toHaveBeenCalled();});
  it("explicit new request ID supports a deliberate repeated edit after intervening changes",async()=>{const f=fixture();f.events.set("existing",{id:"existing",...body()});await f.service.update("existing",{title:"First"},{},"one");await f.service.update("existing",{title:"Second"},{},"two");await code(f.service.update("existing",{title:"First"},{},"one"),"appointment_changed_since_acceptance");await f.service.update("existing",{title:"First"},{},"three");expect(f.provider.updateAppointment).toHaveBeenCalledTimes(3);});
  it("rejected invalid time intervals and inactive creates never write",async()=>{const f=fixture();for(const payload of [{...body(),appointmentStatus:"cancelled"},{...body(),endTime:body().startTime},{...body(),startTime:"bad"}])await expect(f.service.create(payload)).rejects.toBeInstanceOf(AppointmentOperationError);expect(f.store.rows.size).toBe(0);expect(f.provider.createAppointment).not.toHaveBeenCalled();});
  it("digest is deterministic and preserves payload changes",()=>{expect(appointmentDigest({b:2,a:1})).toBe(appointmentDigest({a:1,b:2}));expect(appointmentDigest(body())).not.toBe(appointmentDigest({...body(),endTime:null}));});
});
