import {afterEach,it,expect,vi} from "vitest";
import {randomUUID} from "node:crypto";
import {verifyRequest} from "@egc/operations";
import {operationsPrincipal,callOperations,registerOperationsTools,OPERATIONS_WRITE_TOOLS,LEGACY_MUTATIONS_DISABLED} from "./operations.js";
import type {McpServer} from "@modelcontextprotocol/server";
const env={...process.env};afterEach(()=>{process.env= {...env};});
const key='isolated-mcp-signing-key-not-production-0123456789';
const actor={id:'mcp-oauth-grant:test',role:'integration' as const,kind:'integration' as const,workspace:'egc'};
function configure(){process.env.EGC_OPERATIONS_ENABLED='true';process.env.EGC_OPERATIONS_API_ORIGIN='https://api.test';process.env.EGC_OPERATIONS_MCP_SIGNING_SECRET=key;}
it('disabled and missing principal cannot invoke backend',async()=>{const f=vi.fn();expect(await callOperations({command:'status'},randomUUID(),f)).toMatchObject({error:'operations_not_enabled'});configure();expect(await callOperations({command:'status'},randomUUID(),f)).toMatchObject({error:'verified_principal_required'});expect(f).not.toHaveBeenCalled();});
it('forwards only verified integration identity with stable logical request ID',async()=>{configure();const id=randomUUID();let observed:any;const f=vi.fn(async(_url:unknown,options:any)=>{observed=verifyRequest(JSON.parse(options.body).envelope,{mcp:key});return new Response('{"ok":true}',{status:200});});await operationsPrincipal.run(actor,()=>callOperations({command:'status'},id,f as unknown as typeof fetch));expect(observed.actor).toEqual(actor);expect(observed.request.requestId).toBe(id);expect(observed.iss).toBe('mcp');expect(observed.actor.kind).not.toBe('human');});
it('unknown outcome retains original ID and does not blind retry',async()=>{configure();const id=randomUUID(),f=vi.fn(async()=>{throw new Error('network timeout');});const r=await operationsPrincipal.run(actor,()=>callOperations({command:'status'},id,f));expect(r).toMatchObject({error:'operations_outcome_unknown',requestId:id});expect(f).toHaveBeenCalledTimes(1);});
it('two concurrent requests do not exchange principals',async()=>{configure();const seen:string[]=[];const f=vi.fn(async(_url:unknown,options:any)=>{await new Promise(r=>setTimeout(r,5));seen.push(verifyRequest(JSON.parse(options.body).envelope,{mcp:key}).actor.id);return new Response('{}');});await Promise.all(['one','two'].map(id=>operationsPrincipal.run({...actor,id},()=>callOperations({command:'status'},randomUUID(),f as unknown as typeof fetch))));expect(seen.sort()).toEqual(['one','two']);});
it('tool registry sources and side effects agree with middleware classifications',()=>{const tools:any[]=[];registerOperationsTools({registerTool:(name:any,definition:any)=>tools.push({name,...definition})} as unknown as McpServer);expect(tools.length).toBe(14);expect(new Set(tools.map(t=>t.name)).size).toBe(tools.length);for(const t of tools)expect(t.annotations.readOnlyHint).toBe(!OPERATIONS_WRITE_TOOLS.has(t.name));expect(tools.find(t=>t.name==='egc.calendar').description).toContain('NOT GHL');expect(tools.find(t=>t.name==='egc.daily_brief').annotations.readOnlyHint).toBe(true);for(const raw of ['send_sms','egc.ensure_booking','tasks.update','walkthroughs.approve'])expect(LEGACY_MUTATIONS_DISABLED.has(raw)).toBe(true);});
