import type {McpServer} from "@modelcontextprotocol/server";
import * as z from "zod/v4";
import {callOperations} from "./operations.js";
import {oauthSecurityMetadata,READ_SCOPE,WRITE_SCOPE} from "./oauth.js";
const result=(value:unknown)=>({content:[{type:"text" as const,text:JSON.stringify(value)}],structuredContent:{result:value}});
export function registerPortalRecordTools(server:McpServer){
 const write={annotations:{readOnlyHint:false,destructiveHint:false},...oauthSecurityMetadata([READ_SCOPE,WRITE_SCOPE])};
 const exact={requestId:z.string().uuid(),portalJobId:z.string().min(1).max(180),expectedRevision:z.string().min(1)};
 server.registerTool("egc.add_job_note",{description:"Append an explicitly authorized note to the exact authoritative Employee Hub job or walkthrough. Previous notes remain stored; supersedes may identify an earlier note correction. Requires the current Hub revision and stable request ID, verified by read-back. Does not send customer messages.",inputSchema:z.object({...exact,body:z.string().trim().min(1).max(10000),supersedes:z.string().uuid().optional()}),...write},async input=>result(await callOperations({command:"portal.note.add",...input},input.requestId)));
 server.registerTool("egc.update_job_operations",{description:"Update operational instructions or record dispatched, in-progress or completed state for the exact Hub record. Requires explicit user authorization, current revision and reason. Completion requires the actual occurrence timestamp and evidence; never infers a new sale, payment, customer acceptance or scope agreement.",inputSchema:z.object({...exact,changes:z.object({operationalScope:z.string().max(20000).optional(),status:z.enum(["dispatched","in_progress","completed"]).optional()}).strict(),reason:z.string().min(3).max(2000),occurredAt:z.string().datetime({offset:true}).optional(),completionEvidence:z.string().min(10).max(5000).optional()}),...write},async input=>result(await callOperations({command:"portal.job.edit",...input},input.requestId)));
 server.registerTool("egc.link_project",{description:"Establish a stable authoritative project for the exact saved Hub customer and job/walkthrough relationship. Never matches by name or latest job. Ambiguous source links fail for review. Preserves provider history and financial evidence.",inputSchema:z.object(exact),...write},async input=>result(await callOperations({command:"portal.project.ensure",...input},input.requestId)));
}
