import {afterEach,describe,expect,it,vi} from "vitest";
import type {McpServer} from "@modelcontextprotocol/server";
import {randomUUID} from "node:crypto";
const mocks=vi.hoisted(()=>({call:vi.fn(),enabled:vi.fn(()=>true)}));
vi.mock("./operations.js",()=>({callOperations:mocks.call,operationsEnabled:mocks.enabled}));
import {assertHubSchedule,readHubVisit,bindHubProvider,registerSchedulingTools} from "./scheduling-tools.js";
const visit={portalVisitId:"visit-a",portalCustomerId:"customer-a",revision:"r1",highlevelContactId:"contact-a",highlevelAppointmentId:"appointment-a",type:"walkthrough",startTime:"2026-09-23T16:00:00Z",endTimeInstant:"2026-09-23T17:00:00Z",status:"scheduled",title:"Walkthrough",address:"Synthetic address"};
const expected={contactId:"contact-a",startTime:visit.startTime,endTime:visit.endTimeInstant,appointmentStatus:"confirmed",title:visit.title,address:visit.address};
afterEach(()=>{vi.clearAllMocks();mocks.enabled.mockReturnValue(true);});
describe("canonical schedule bridge",()=>{
 it("rejects cross-customer/provider and mismatched native schedule before writes",()=>{expect(()=>assertHubSchedule(visit,expected,"appointment-a")).not.toThrow();for(const change of [{contactId:"different"},{startTime:"2026-09-24T16:00:00Z"},{endTime:"2026-09-23T18:00:00Z"},{appointmentStatus:"cancelled"},{title:"Another"},{address:"Another"}])expect(()=>assertHubSchedule(visit,{...expected,...change},"appointment-a")).toThrow();expect(()=>assertHubSchedule(visit,expected,"another-provider-id")).toThrow();});
 it("requires the actual Hub authority with stable source identity",async()=>{mocks.call.mockResolvedValue({authority:"ghl",visit});await expect(readHubVisit("visit-a")).rejects.toMatchObject({code:"schedule_authority_unavailable"});mocks.call.mockResolvedValue({authority:"employee_hub",visit:{...visit,portalVisitId:"wrong"}});await expect(readHubVisit("visit-a")).rejects.toMatchObject({code:"schedule_identity_unverified"});});
 it("provider binding uses current exact Hub revision and stable operation ID",async()=>{mocks.call.mockResolvedValueOnce({authority:"employee_hub",visit}).mockResolvedValueOnce({ok:true});const id=randomUUID();await bindHubProvider("visit-a",id,{id:"appointment-a"});expect(mocks.call.mock.calls[1]).toEqual([{command:"schedule.bind_provider",portalVisitId:"visit-a",operationId:id,expectedRevision:"r1",event:{id:"appointment-a"}},id]);});
 function registry(sync=vi.fn(async()=>({ok:true}))){const handlers=new Map<string,(args:any)=>Promise<any>>(),definitions=new Map<string,any>();registerSchedulingTools({registerTool:(name:string,definition:unknown,handler:any)=>{definitions.set(name,definition);handlers.set(name,handler);}} as unknown as McpServer,sync);return{handlers,definitions,sync};}
 const input=()=>({requestId:randomUUID(),mode:"create",portalCustomerId:"customer-a",kind:"walkthrough",changes:{date:"2026-09-23",time:"10:00",endTime:"11:00"},runAutomations:false});
 it("saves native state before provider sync and preserves request ID",async()=>{const r=registry(),i=input();mocks.call.mockImplementation(async()=>{expect(r.sync).not.toHaveBeenCalled();return{ok:true,authority:"employee_hub",visit};});const result=await r.handlers.get("egc.schedule_visit")!(i);expect(mocks.call.mock.calls[0]?.[1]).toBe(i.requestId);expect(r.sync).toHaveBeenCalledWith(visit,{requestId:i.requestId,runAutomations:false});expect(JSON.parse(result.content[0].text).provider.ok).toBe(true);expect(r.definitions.get("egc.schedule_visit").annotations.readOnlyHint).toBe(false);expect(r.definitions.get("egc.visit_get").annotations.readOnlyHint).toBe(true);});
 it("native failure never sends, provider failure truthfully preserves saved native state",async()=>{const r=registry();mocks.call.mockResolvedValue({error:"schedule_slot_conflict"});await r.handlers.get("egc.schedule_visit")!(input());expect(r.sync).not.toHaveBeenCalled();mocks.call.mockResolvedValue({ok:true,authority:"employee_hub",visit});r.sync.mockRejectedValue(new Error("provider secret"));const result=JSON.parse((await r.handlers.get("egc.schedule_visit")!(input())).content[0].text);expect(result.ok).toBe(true);expect(result.provider.ok).toBe(false);expect(result.provider.syncStatus).toBe("pending");expect(JSON.stringify(result)).not.toContain("provider secret");});
 it("disabled bridge cannot perform either native or provider writes",async()=>{const r=registry();mocks.enabled.mockReturnValue(false);await r.handlers.get("egc.schedule_visit")!(input());expect(mocks.call).not.toHaveBeenCalled();expect(r.sync).not.toHaveBeenCalled();});
});
