/* Test the real static gallery. No live analytics, CRM or customer writes. */
const {chromium}=require('playwright');
const fs=require('fs'),http=require('http'),path=require('path'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'../..'),report=path.join(root,'gallery-review');fs.mkdirSync(report,{recursive:true});
const mime={'.html':'text/html','.css':'text/css','.js':'text/javascript','.json':'application/json','.png':'image/png','.jpg':'image/jpeg','.webp':'image/webp','.ico':'image/x-icon'};
const server=http.createServer((req,res)=>{let p=decodeURIComponent(new URL(req.url,'http://localhost').pathname);if(p==='/')p='/index.html';if(p==='/before-after')p='/before-after.html';let f=path.resolve(root,'.'+p);if(!f.startsWith(root+'/')){res.writeHead(403);return res.end();}try{const b=fs.readFileSync(f);res.writeHead(200,{'Content-Type':mime[path.extname(f)]||'application/octet-stream'});res.end(b);}catch{res.writeHead(404);res.end();}});
const results=[];let browser;
async function test(name,fn){try{await fn();results.push({name,passed:true});}catch(e){results.push({name,passed:false,error:String(e)});}}
(async()=>{await new Promise(r=>server.listen(8765,'127.0.0.1',r));browser=await chromium.launch({headless:true});const ctx=await browser.newContext({viewport:{width:1440,height:1100}});await ctx.route('**/*',r=>new URL(r.request().url()).hostname==='127.0.0.1'?r.continue():r.abort());await ctx.route('**/analytics-loader.js*',r=>r.fulfill({status:200,contentType:'text/javascript',body:''}));const p=await ctx.newPage();p.setDefaultTimeout(8000);let errors=[];p.on('pageerror',e=>errors.push(String(e)));await p.goto('http://127.0.0.1:8765/before-after',{waitUntil:'networkidle'});const concepts=JSON.parse(fs.readFileSync(path.join(root,'before-after-concepts.json'))).concepts.length;await p.waitForFunction(n=>document.querySelectorAll('.gallery-card').length===3+n,concepts);
await test('Only approved fully available concepts appear',async()=>{assert.equal(await p.locator('.gallery-card').count(),3+concepts);assert.equal(await p.locator('.concept-badge').count(),concepts);assert.equal(await p.locator('#concept-disclosure').isVisible(),concepts>0);});
await test('Before/after buttons and keyboard slider',async()=>{await p.locator('[data-reveal="100"]').click();assert.equal(await p.locator('#compare-range').inputValue(),'100');await p.locator('[data-reveal="0"]').click();assert.equal(await p.locator('#compare-range').inputValue(),'0');await p.locator('#compare-range').focus();await p.keyboard.press('End');assert.equal(await p.locator('#compare-range').inputValue(),'100');await p.keyboard.press('Home');assert.equal(await p.locator('#compare-range').inputValue(),'0');await p.locator('[data-reveal="50"]').click();});
await test('Pointer comparison works',async()=>{await p.locator('#featured-compare').scrollIntoViewIfNeeded();const b=await p.locator('#featured-compare').boundingBox();await p.mouse.move(b.x+b.width*.75,b.y+b.height*.5);await p.mouse.down();await p.mouse.move(b.x+b.width*.25,b.y+b.height*.5);await p.mouse.up();assert(Math.abs(Number(await p.locator('#compare-range').inputValue())-25)<=1);await p.locator('[data-reveal="50"]').click();});
await test('Category filters, labels and count',async()=>{await p.locator('[data-filter="organization"]').click();assert.equal(await p.locator('.gallery-card:visible').count(),1);await p.locator('[data-filter="cleanout"]').click();assert.equal(await p.locator('.gallery-card:visible').count(),3);if(concepts){await p.locator('[data-filter="concept"]').click();assert.equal(await p.locator('.gallery-card:visible').count(),concepts);}await p.locator('[data-filter="all"]').click();assert.equal(await p.locator('.gallery-card:visible').count(),3+concepts);});
await test('Lightbox Escape and focus return',async()=>{const a=p.locator('[data-lightbox]').first();await a.click();assert(await p.locator('#photo-dialog').isVisible());await p.keyboard.press('Escape');assert.equal(await p.locator('#photo-dialog').isVisible(),false);assert(await a.evaluate(e=>document.activeElement===e));});
await test('Every gallery image decodes',async()=>{for(const image of await p.locator('main img').all()){await image.scrollIntoViewIfNeeded();await image.evaluate(e=>e.decode());assert(await image.evaluate(e=>e.naturalWidth>0));}});
await test('Booking CTAs are unchanged',async()=>{const hrefs=await p.locator('[data-cta]').evaluateAll(a=>a.map(e=>e.getAttribute('href')));assert.equal(hrefs.length,3);assert(hrefs.every(h=>h==='/book'));});
for(const width of [1440,390,320]){await test('No horizontal overflow at '+width+'px',async()=>{await p.setViewportSize({width,height:1000});assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));});if(width!==320){await p.evaluate(()=>{document.documentElement.style.scrollBehavior='auto';scrollTo(0,0);});await p.screenshot({path:path.join(report,`gallery-${width}.png`),fullPage:true});}}
await test('No-JavaScript fallback remains usable',async()=>{const nc=await browser.newContext({javaScriptEnabled:false});const np=await nc.newPage();await np.route('**/*',r=>new URL(r.request().url()).hostname==='127.0.0.1'?r.continue():r.abort());await np.goto('http://127.0.0.1:8765/before-after',{waitUntil:'domcontentloaded'});assert.equal(await np.locator('.gallery-card').count(),3);assert.equal(await np.locator('.nojs-links a').count(),2);assert.equal(await np.locator('#filter-bar').isVisible(),false);await nc.close();});
await test('No runtime JavaScript errors',async()=>assert.deepEqual(errors,[]));
fs.writeFileSync(path.join(report,'browser-results.json'),JSON.stringify({tests:results.length,passed:results.filter(x=>x.passed).length,results},null,2));console.log(JSON.stringify(results,null,2));if(results.some(x=>!x.passed))process.exitCode=1;
})().catch(e=>{console.error(e);process.exitCode=1;}).finally(async()=>{if(browser)await browser.close();server.close();});
