/* Frontend-only checks against the static fallback. No backend requests. */
const {chromium}=require('playwright');
const fs=require('node:fs');const path=require('node:path');const http=require('node:http');const assert=require('node:assert/strict');
const root=path.resolve(__dirname,'../..');const out=path.join(root,'showcase-review');fs.mkdirSync(out,{recursive:true});
const results=[];
async function check(name,fn){try{await fn();results.push({name,passed:true});}catch(error){results.push({name,passed:false,error:String(error)});}}
const mime={'.html':'text/html','.css':'text/css','.js':'text/javascript','.json':'application/json','.webp':'image/webp','.png':'image/png','.ico':'image/x-icon'};
const server=http.createServer((req,res)=>{let pathname=new URL(req.url,'http://localhost').pathname;if(pathname==='/before-after')pathname='/before-after.html';let target=path.resolve(root,'.'+pathname);if(!target.startsWith(root+path.sep)){res.writeHead(403);return res.end();}try{let bytes=fs.readFileSync(target);res.writeHead(200,{'Content-Type':mime[path.extname(target)]||'application/octet-stream'});res.end(bytes);}catch{res.writeHead(404);res.end('Not found');}});
(async()=>{
 await new Promise(r=>server.listen(0,'127.0.0.1',r));let origin='http://127.0.0.1:'+server.address().port;
 const browser=await chromium.launch({headless:true,args:['--no-sandbox']});const context=await browser.newContext({viewport:{width:1440,height:1000}});
 // Block all nonlocal requests: never send analytics or touch any customer/backend service.
 await context.route('**/*',route=>route.request().url().startsWith(origin)?route.continue():route.abort());
 const page=await context.newPage();page.setDefaultTimeout(10000);const errors=[];page.on('pageerror',e=>errors.push(String(e)));
 await page.goto(origin+'/before-after',{waitUntil:'networkidle'});
 await check('Six selected composites appear before the original 24 designs',async()=>{assert.equal(await page.locator('.showcase-card').count(),6);assert.equal(await page.locator('#gallery .card').count(),30);assert.equal(await page.locator('#gallery .card').first().getAttribute('data-showcase-id'),'park-and-work');assert.equal(await page.locator('#count').textContent(),'30 designs');});
 await check('Public wording is design inspiration, without repeated AI badges',async()=>{assert.equal(await page.locator('.public-hero .eyebrow').textContent(),'Garage design inspiration');assert.equal(await page.locator('.hero-copy .concept-note').textContent(),'Concept layouts for planning your space.');assert(!(await page.locator('body').innerText()).includes('AI-generated'));});
 await check('Six images decode, are distinct, and retain complete 4:3 compositions',async()=>{const sources=new Set();for(const image of await page.locator('.showcase-photo').all()){await image.scrollIntoViewIfNeeded();await image.evaluate(e=>e.decode());const v=await image.evaluate(e=>({src:e.src,w:e.naturalWidth,h:e.naturalHeight,rect:e.getBoundingClientRect().toJSON()}));sources.add(v.src);assert.equal(v.w/v.h,4/3);assert(Math.abs(v.rect.width/v.rect.height-4/3)<.02);}assert.equal(sources.size,6);});
 await check('Search includes new cards and clears back to all 30',async()=>{await page.locator('#search').fill('black metal');assert.equal(await page.locator('#gallery .card:visible').count(),6);await page.locator('#search').fill('no-matching-space-xyz');assert.equal(await page.locator('#empty').isVisible(),true);await page.locator('#search').fill('');assert.equal(await page.locator('#gallery .card:visible').count(),30);});
 await check('Composite viewer opens full image, closes with Escape, restores focus',async()=>{const b=page.locator('.showcase-card [data-expand]').first();await b.click();assert.equal(await page.locator('#viewer').isVisible(),true);assert.equal(await page.locator('#viewer-body>.showcase-photo').count(),1);assert.equal(await page.locator('#viewer-body input').count(),0);await page.keyboard.press('Escape');assert.equal(await page.locator('#viewer').isVisible(),false);assert(await b.evaluate(e=>document.activeElement===e));});
 await check('Original slider controls still work',async()=>{const card=page.locator('.card:not(.showcase-card)').first();await card.locator('[data-position="100"]').click();assert.equal(await card.locator('input').inputValue(),'100');await card.locator('[data-position="0"]').click();assert.equal(await card.locator('input').inputValue(),'0');await card.locator('[data-expand]').click();assert.equal(await page.locator('#viewer-body .comparison').count(),1);await page.keyboard.press('Escape');});
 for(const width of [1440,390,320])await check('No horizontal overflow at '+width+' pixels',async()=>{await page.setViewportSize({width,height:900});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));});
 await page.setViewportSize({width:1440,height:1100});await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:path.join(out,'desktop.png')});
 await page.setViewportSize({width:390,height:844});await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:path.join(out,'mobile.png')});
 await check('Unavailable showcase feed preserves the original usable gallery',async()=>{await page.route('**/gallery-showcase.json',route=>route.fulfill({status:503,body:''}));await page.reload({waitUntil:'networkidle'});assert.equal(await page.locator('.showcase-card').count(),0);assert.equal(await page.locator('.card').count(),24);await page.unroute('**/gallery-showcase.json');});
 await check('Internal preview is not relabeled or populated with public showcase cards',async()=>{await page.route('**/before-after.html',route=>route.fulfill({status:200,contentType:'text/html',body:fs.readFileSync(path.join(root,'before-after.html'),'utf8').replace('hero public-hero','hero')}));await page.goto(origin+'/before-after.html',{waitUntil:'networkidle'});assert.equal(await page.locator('.showcase-card').count(),0);assert((await page.locator('.hero-copy .concept-note').textContent()).includes('AI-generated'));});
 await check('No frontend runtime errors',async()=>assert.deepEqual(errors,[]));
 fs.writeFileSync(path.join(out,'results.json'),JSON.stringify({results},null,2));console.log(JSON.stringify(results,null,2));
 await browser.close();server.close();if(results.some(r=>!r.passed))process.exitCode=1;
})().catch(error=>{console.error(error);server.close();process.exitCode=1;});
