/**
 * Catalog seed module. Pages Functions read the seed catalog and the placeholder pricing settings from
 * functions/_data/catalog-seed.js, a plain-JavaScript copy of the two JSON files: a JSON import needs
 * `with { type: 'json' }` in Node, which the esbuild in older Wrangler releases cannot parse. The JSON
 * files stay the source; this regenerates the module from them.
 *   node scripts/catalog-seed.mjs            report; exit 1 when the module is stale
 *   node scripts/catalog-seed.mjs --write    rewrite functions/_data/catalog-seed.js
 * Read-only unless --write.
 */
import {readFileSync,writeFileSync,existsSync} from 'node:fs';
import {join} from 'node:path';
import {fileURLToPath,pathToFileURL} from 'node:url';

export const REPO_ROOT=fileURLToPath(new URL('..',import.meta.url));
export const MODULE='functions/_data/catalog-seed.js';
export const SOURCES={catalog:'functions/_data/garage-catalog.json',settings:'functions/_data/pricing-settings.defaults.json'};

// Compact JSON inside a string literal: bundles parse a string far faster than a 500 KB object
// literal, and catalog-store.js parses it only when the catalog is first needed.
export function catalogSeedModule(catalogText,settingsText){
  const compact=text=>JSON.stringify(JSON.stringify(JSON.parse(text)));
  return [
    `// Generated by scripts/catalog-seed.mjs from ${SOURCES.catalog} and`,
    `// ${SOURCES.settings}. Do not edit: change the JSON, then run`,
    '// node scripts/catalog-seed.mjs --write (tests/catalog-api.test.mjs fails while this file is stale).',
    `export const SEED_CATALOG_JSON = ${compact(catalogText)};`,
    `export const SEED_SETTINGS_JSON = ${compact(settingsText)};`,
    '',
  ].join('\n');
}

export function expectedSeedModule(root=REPO_ROOT){
  return catalogSeedModule(readFileSync(join(root,SOURCES.catalog),'utf8'),readFileSync(join(root,SOURCES.settings),'utf8'));
}

function main(){
  const write=process.argv.includes('--write'),path=join(REPO_ROOT,MODULE),expected=expectedSeedModule();
  if(write)writeFileSync(path,expected);
  const stale=!existsSync(path)||readFileSync(path,'utf8')!==expected;
  console.log(stale?`✗ ${MODULE} is stale; run node scripts/catalog-seed.mjs --write`:`${MODULE} matches the catalog JSON${write?' (written)':''}`);
  if(stale)process.exitCode=1;
}
if(process.argv[1]&&import.meta.url===pathToFileURL(process.argv[1]).href)main();
