// GENERATED by `node scripts/funnel-definitions.mjs --write` from functions/_data/funnel-definitions.data.json. Do not edit.
// definitionsHash as computed by the Hub (functions/_lib/funnel-definitions.js); src/index.test.ts proves the platform computes the same value.
export const hubDefinitionsHash = "cbf5e5f23096e257b149282d9b340bc6c783f765c0341d8a710f6e483d030a6b";
export const hubDefinitionsVersion = "2026-09-28.1";
