// GENERATED by `node scripts/funnel-definitions.mjs --write` from functions/_data/funnel-definitions.data.json. Do not edit.
// definitionsHash as computed by the Hub (functions/_lib/funnel-definitions.js); src/index.test.ts proves the platform computes the same value.
export const hubDefinitionsHash = "2623603f030695f31f62416a430098c7d29a8c7037a2a6796e1b15f2f3b16439";
export const hubDefinitionsVersion = "2026-09-28.3";
