// GENERATED by `node scripts/funnel-definitions.mjs --write` from functions/_data/funnel-definitions.data.json. Do not edit.
// definitionsHash as computed by the Hub (functions/_lib/funnel-definitions.js); src/index.test.ts proves the platform computes the same value.
export const hubDefinitionsHash = "18b0ee49912548aa973a65cefac01a946cc0e2b63aeb5007e8361503c1c1ec55";
export const hubDefinitionsVersion = "2026-09-28.4";
