FROM node:22-bookworm-slim
ENV NODE_ENV=production
WORKDIR /app
RUN corepack enable
COPY . .
RUN pnpm install --no-frozen-lockfile
RUN pnpm --filter @egc/database build \
 && pnpm --filter @egc/portal build
CMD ["pnpm", "--filter", "@egc/portal", "start"]
