/** Synthetic recording lifecycle against isolated PostgreSQL; all external I/O is mocked. */
import test,{beforeEach,after} from 'node:test';
import assert from 'node:assert/strict';
import {createHash,randomUUID} from 'node:crypto';
import {getDb,schema} from '@egc/database';
import {eq,sql} from 'drizzle-orm';
import {walkthroughExtractionSchema} from '@egc/schemas';
import {RecordingService} from '../dist/recordings.js';
const url=new URL(process.env.DATABASE_URL||'http://invalid');
if(process.env.EGC_OPERATIONS_TEST!=='isolated'||!['localhost','127.0.0.1'].includes(url.hostname)||url.pathname!=='/egc_operations_test'||!['postgres:','postgresql:'].includes(url.protocol))throw new Error('Only isolated loopback egc_operations_test is allowed');
const originalFetch=globalThis.fetch;globalThis.fetch=async()=>{throw new Error('External HTTP is forbidden in synthetic recording tests');};
const db=getDb(),actor={id:'test-owner',kind:'human',role:'owner',workspace:'egc'},env={EGC_OPERATIONS_WORKSPACE:'egc',EGC_PORTAL_ORIGIN:'https://synthetic.invalid',EGC_OPERATIONS_PORTAL_SIGNING_SECRET:'isolated-recording-test-signing-key-01234567890'};
const extraction=()=>walkthroughExtractionSchema.parse({itemsKeep:['Synthetic bicycle'],proposedActions:[{title:'Call about shelf placement',kind:'callback',commitment:'Call before work starts',sourceQuote:'I will call before work starts',ownerMention:null,dueMention:null,confidence:0.9}]});
const claims=(body,requestId=randomUUID())=>({v:1,iss:'portal',aud:'egc-recordings',iat:Math.floor(Date.now()/1000),nonce:randomUUID(),actor,request:{requestId,body}});
let service,stored,receipts,sourceRevision,transcribeFails,appliedCount,unknownAfterApply,storageFails;
const row=async id=>(await db.select().from(schema.walkthroughs).where(eq(schema.walkthroughs.id,id)))[0];
beforeEach(async()=>{await db.execute(sql`truncate operation_events,operation_approvals,operation_requests,operation_briefs,tasks,contacts,walkthroughs,audit_logs cascade`);stored=new Map();receipts=new Set();sourceRevision='source-v1';transcribeFails=false;storageFails=false;appliedCount=0;unknownAfterApply=false;
  const fetcher=async(url,options)=>{const token=JSON.parse(options.body).envelope,body=JSON.parse(Buffer.from(token.split('.')[0],'base64url')).request.body;
    if(body.command==='recording.resolve')return Response.json({identity:{authority:'employee_hub',portalJobId:'visit-synthetic',portalVisitId:'visit-synthetic',portalCustomerId:'customer-synthetic',portalProjectId:null,portalRevision:sourceRevision,highlevelContactId:null}});
    if(body.command==='recording.apply'){if(receipts.has(body.recordingId))return Response.json({ok:true,alreadyApplied:true});if(body.expectedRevision!==sourceRevision)return Response.json({error:'recording_source_revision_conflict'},{status:409});receipts.add(body.recordingId);appliedCount++;sourceRevision='source-v2';if(unknownAfterApply){unknownAfterApply=false;throw new Error('Unknown transport failure after commit');}return Response.json({ok:true});}
    if(body.command==='portal.members')return Response.json({authority:'employee_hub',members:[{id:actor.id}]});
    if(body.command==='portal.job')return Response.json({authority:'employee_hub',job:{id:'visit-synthetic',revision:sourceRevision,type:'walkthrough',highlevelContactId:null,sourceWalkthroughId:null,customer:'Synthetic',status:'scheduled'}});
    throw new Error('Unexpected synthetic provider command');};
  const io={put:async(key,bytes)=>{const records=await db.select().from(schema.walkthroughs);assert.equal(records.length,1,'durable recording must exist before storage/AI');if(storageFails)throw new Error('storage unavailable secret=value');stored.set(key,bytes);return key;},get:async key=>stored.get(key),transcribe:async()=>{if(transcribeFails)throw new Error('AI error with secret=value');return 'I will call before work starts. Keep the bicycle.';},extract:async()=>extraction()};
  service=new RecordingService(env,db,fetcher,io);
});
after(async()=>{globalThis.fetch=originalFetch;await db.$client.end({timeout:5});});
async function upload(id=randomUUID(),audio=Buffer.from('synthetic-audio')){return service.upload(claims({command:'recording.upload',portalJobId:'visit-synthetic',audioSha256:createHash('sha256').update(audio).digest('hex')},id),audio,'audio/webm');}
const get=id=>service.execute(claims({command:'recording.get',recordingId:id}));
async function draft(){const r=await upload();await service.processNext();return(await get(r.recording.id)).recording;}
const review=(r,extra={})=>({command:'recording.approve',recordingId:r.id,revision:r.revision,extraction:r.extraction,actions:[],...extra});
test('upload survives service reconstruction and suppresses duplicate logical recordings',async()=>{const requestId=randomUUID();const first=await upload(requestId);assert.equal(first.recording.status,'uploaded');assert.equal(first.recording.contactId,null);const again=await upload(requestId);assert.equal(again.recording.id,first.recording.id);assert.equal((await db.select().from(schema.walkthroughs)).length,1);await assert.rejects(upload(requestId,Buffer.from('different')),e=>e.code==='recording_upload_request_conflict');assert.equal(first.recording.audioObjectKey,undefined);});
test('failed upload retains durable record and retries original bytes without duplicate',async()=>{const requestId=randomUUID();storageFails=true;await assert.rejects(upload(requestId),e=>e.code==='recording_upload_failed');const [failed]=await db.select().from(schema.walkthroughs);assert.equal(failed.status,'failed');storageFails=false;assert.equal((await upload(requestId)).recording.id,failed.id);assert.equal((await row(failed.id)).status,'uploaded');});
test('transcription failure is safe, retryable and never applies scope or invents a job',async()=>{const r=await upload();transcribeFails=true;await service.processNext();assert.equal((await row(r.recording.id)).status,'failed');assert.equal((await row(r.recording.id)).lastErrorCode,'recording_processing_failed');await service.execute(claims({command:'recording.retry',recordingId:r.recording.id}));transcribeFails=false;await service.processNext();const d=await row(r.recording.id);assert.equal(d.status,'draft');assert.equal(d.attemptCount,2);assert.equal(appliedCount,0);assert.equal((await db.select().from(schema.jobs)).length,0);});
test('two processors claim one recording and stale recording revision cannot approve',async()=>{const r=await upload();const claimsResult=await Promise.all([service.processNext(),service.processNext()]);assert.equal(claimsResult.filter(Boolean).length,1);const d=(await get(r.recording.id)).recording;await assert.rejects(service.execute(claims(review(d,{revision:'2000-01-01T00:00:00.000Z'}))),e=>e.code==='recording_revision_conflict');assert.equal(appliedCount,0);});
test('unknown Hub approval outcome safely resumes identical review and creates one shared task',async()=>{const d=await draft();const action={title:'Call before work starts',kind:'callback',description:'Explicit synthetic promise',priority:'medium',assignedUserId:actor.id,dueAt:new Date(Date.now()+86400000).toISOString(),timeZone:'America/Denver',waitingOn:'none',reviewAt:null,portalJobId:'visit-synthetic',portalVisitId:'visit-synthetic',contactId:null,jobId:null,completionCondition:'Record call result',sourceEvidence:[],dependencies:[],draft:null};const c=claims(review(d,{actions:[action]}));unknownAfterApply=true;await assert.rejects(service.execute(c),e=>e.code==='recording_approval_outcome_unknown');assert.equal((await row(d.id)).status,'approval_pending');await assert.rejects(service.execute(claims(review(d,{extraction:{...d.extraction,itemsKeep:['Changed']}}))),e=>e.code==='recording_approval_request_conflict');const done=await service.execute(c);assert.equal(done.recording.status,'approved');await service.execute(c);assert.equal(appliedCount,1);assert.equal((await db.select().from(schema.tasks)).length,1);assert.equal((await db.select().from(schema.jobs)).length,0);assert.equal((await db.select().from(schema.auditLogs)).filter(e=>e.action==='recording.approve').length,1);});
test('source changes require explicit refreshed review; no automatic scope overwrite',async()=>{const d=await draft();sourceRevision='source-edited';await assert.rejects(service.execute(claims(review(d))),e=>e.code==='recording_source_revision_conflict');assert.equal(appliedCount,0);const refreshed=await service.execute(claims({command:'recording.refresh_source',recordingId:d.id}));assert.equal(refreshed.requiresNewReview,true);assert.equal(refreshed.recording.status,'draft');await service.execute(claims(review(refreshed.recording)));assert.equal(appliedCount,1);});
